import { base44 } from "@/api/base44Client";

const GUIDED_MEDITATIONS_SEED = [
  { id: "gm-1-morning-breath", title: "5-Min Morning Breath with God", description: "Begin your day by aligning your breath and heart with God's presence.", category: "breathing", duration_minutes: 5, image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Find a comfortable seated position. Let your shoulders relax and gently close your eyes. Take a slow breath in through your nose, and exhale through your mouth. As you breathe, remember that every breath is a gift from God.\n\nOn your next inhale, silently pray, \"Lord, fill me.\" On your exhale, pray, \"Lord, calm me.\" Continue this rhythm: breathing in His presence, breathing out your worries. If your mind wanders, gently bring it back to your breath and this simple prayer.\n\nPicture the light of Christ rising with the morning, filling your mind, your body, and your day with peace. You don't have to strive to earn His love—it already surrounds you. Rest in that truth for a few more breaths, knowing that God walks with you into this day." },
  { id: "gm-2-body-scan-stress", title: "10-Min Body Scan for Stress Release", description: "Release tension from your body while inviting God's peace into every part of you.", category: "stress_relief", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Lie down or sit comfortably, allowing your body to be supported. Close your eyes and take a deep breath in, then slowly exhale. Invite the Holy Spirit to be present with you in this moment.\n\nBegin by bringing your attention to your feet. Notice any tension or sensation there, and as you exhale, imagine God's peace flowing down, relaxing your feet and toes. Move your awareness slowly up through your legs, hips, and lower back, breathing out stress and breathing in His rest.\n\nContinue scanning through your chest, shoulders, arms, neck, and face. With each breath, release what you've been carrying alone and surrender it to God. Hear His gentle whisper: \"Come to Me, and I will give you rest.\" Let your whole body rest in that promise." },
  { id: "gm-3-loving-kindness", title: "15-Min Loving-Kindness in Christ", description: "Practice compassion rooted in the love of Jesus for you and others.", category: "compassion", duration_minutes: 15, image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit comfortably and close your eyes. Take a few slow breaths, inviting Jesus into this time. Remember that He loves you fully, right now, exactly as you are.\n\nBegin by placing a hand over your heart. Silently pray: \"Lord, may I rest in Your love. May I be safe in Your care. May I walk in Your peace.\" Let these words sink in as you breathe.\n\nNow bring to mind someone you care about. Picture them in God's light and pray: \"Lord, may they know Your love. May they be safe in Your hands. May they experience Your peace.\" Gradually widen your prayer to include people you struggle with, and even those you don't know. Trust that God's love is big enough for all. Rest in that love for a few more breaths." },
  { id: "gm-4-midday-mindful-checkin", title: "7-Min Midday Check-In with God", description: "Pause in the middle of your day to realign your heart with God's presence.", category: "mindfulness", duration_minutes: 7, image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800", ambient_url: "/ambient/calm_river.mp3", script: "Sit comfortably and let your shoulders drop away from your ears. Close your eyes or soften your gaze. Take a slow breath in and out, and simply acknowledge: \"God, I'm here with You.\"\n\nNotice how your body feels right now—any tightness, fatigue, or restlessness. Notice your thoughts and emotions without judging them. Offer them honestly to God: your frustrations, your hopes, your questions.\n\nAs you breathe, silently pray, \"Lord, meet me in this moment.\" With each inhale, receive His peace. With each exhale, release your need to control everything. Let this short pause be a reset, a reminder that you are not carrying this day alone. God is with you, even here, even now." },
  { id: "gm-5-sleep-prep", title: "10-Min Sleep in God's Care", description: "Let go of the day and rest in the safety of God's presence.", category: "sleep", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Lie down in a comfortable position and allow your body to sink into the bed. Close your eyes and take a slow, deep breath in… and a long, gentle breath out. Imagine God's hand resting over you in protection and love.\n\nAs you breathe, mentally lay down the events of the day at the feet of Jesus—your wins, your mistakes, your worries. You don't have to hold them anymore. Whisper, \"Lord, I give this day to You.\"\n\nWith each exhale, feel your muscles soften—your feet, legs, hips, back, shoulders, and face. Let God's peace cover you like a warm blanket. Trust that while you sleep, He does not. He watches over you, sings over you, and restores you. Rest in His care." },
  { id: "gm-6-quick-stress-reset", title: "7-Min Stress Reset with Scripture", description: "Release stress by breathing through God's promises.", category: "stress_relief", duration_minutes: 7, image_url: "https://images.unsplash.com/photo-1523419409543-3e4f83b9b8f2?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Sit comfortably with your feet grounded. Take a deep breath in through your nose and exhale slowly through your mouth. Bring to mind the verse: \"Cast all your anxiety on Him because He cares for you.\"\n\nOn each inhale, silently say, \"You care for me, Lord.\" On each exhale, imagine placing your worries into His hands. Feel your shoulders soften as you remember you are not meant to carry everything alone.\n\nIf stressful thoughts arise, don't fight them. Acknowledge them and gently return to your breath and the truth of God's care. Let His peace guard your heart and mind as you breathe with Him for these few minutes." },
  { id: "gm-7-morning-gratitude", title: "8-Min Morning Gratitude with God", description: "Start your day by thanking God for His goodness.", category: "gratitude", duration_minutes: 8, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Sit comfortably and take a few slow breaths. Begin by thanking God for the simple gift of this new day. Thank Him for breath in your lungs, for a mind that can think, and a heart that can feel.\n\nBring to mind three specific blessings—people, opportunities, or moments where you've seen His faithfulness. Speak them to Him in your heart: \"Thank You for…\" Let gratitude soften any anxiety about what's ahead.\n\nAs you breathe, let your heart say, \"This is the day the Lord has made; I will rejoice and be glad in it.\" Carry this posture of gratitude into whatever comes next." },
  { id: "gm-8-evening-reflection", title: "12-Min Evening Reflection with Jesus", description: "Review your day with Jesus, receiving grace and clarity.", category: "reflection", duration_minutes: 12, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Find a comfortable position and close your eyes. Take a few slow breaths, inviting Jesus into this moment. Ask Him, \"Lord, walk me back through my day.\"\n\nGently replay your day from morning to now. Notice moments of joy, frustration, distraction, and connection. Instead of judging yourself, simply notice and talk to Jesus about what you see.\n\nWhere you fell short, receive His grace. Where you saw His goodness, thank Him. Where you still feel confused or burdened, hand it to Him in prayer. End by resting in the truth that nothing in this day surprised Him, and His love for you has not changed." },
  { id: "gm-9-focus-reset", title: "6-Min Focus Reset in God's Presence", description: "Clear mental clutter and refocus your mind on God.", category: "focus", duration_minutes: 6, image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", ambient_url: "/ambient/calm_river.mp3", script: "Sit upright with your feet on the floor. Take a deep breath in and a slow breath out. Imagine placing all distractions at the feet of Jesus for a moment.\n\nChoose a simple phrase to anchor your focus, such as \"Be still and know that I am God.\" As you breathe, repeat this verse slowly in your mind. When your thoughts wander, gently return to the words and your breath.\n\nYou are not trying to empty your mind, but to re-center it on the One who holds all things together. Let His presence become the quiet center of your attention." },
  { id: "gm-10-heart-healing", title: "15-Min Heart Healing with the Lord", description: "Bring emotional pain to God and receive His comfort.", category: "healing", duration_minutes: 15, image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Sit or lie down in a position where you feel safe. Place a hand over your heart and take a slow breath in and out. Invite the Lord into the places that feel heavy or hurt.\n\nBring to mind a situation or feeling that has been weighing on you. You don't need to relive every detail—just acknowledge it before God. Tell Him honestly how you feel.\n\nAs you breathe, imagine His gentle presence surrounding that pain. Hear His words: \"I am close to the brokenhearted.\" With each exhale, release a little of the burden you've been carrying. Let Him hold what you no longer can. Rest in His compassion and nearness." },
  { id: "gm-11-calm-confidence", title: "10-Min Calm Confidence in Christ", description: "Stand in quiet confidence rooted in who God says you are.", category: "confidence", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1523419409543-3e4f83b9b8f2?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit tall, feeling the support beneath you. Take a deep breath in and a slow breath out. Remember that your identity is not in your performance, but in Christ.\n\nBring to mind a verse like, \"I am fearfully and wonderfully made,\" or \"I can do all things through Christ who strengthens me.\" As you breathe, repeat this truth slowly, letting it sink deeper than your doubts.\n\nPicture yourself standing with Jesus beside you, His hand on your shoulder, steadying you. Your confidence doesn't have to be loud; it can be a quiet knowing that you are loved, called, and equipped by God." },
  { id: "gm-12-social-anxiety", title: "9-Min Social Anxiety Surrender", description: "Bring your social fears to God and receive His peace.", category: "healing", duration_minutes: 9, image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", ambient_url: "/ambient/calm_river.mp3", script: "Sit comfortably and breathe slowly. Think of the social situations that make you feel nervous or small. Instead of hiding them, bring them honestly before God.\n\nTell Him what you fear—rejection, judgment, awkwardness. Then remember His promise: \"I will never leave you nor forsake you.\" Imagine Him standing beside you in every room you enter.\n\nAs you breathe, release the need to impress others and receive the freedom to simply be who God made you to be. Let His opinion of you matter most." },
  { id: "gm-13-pre-meeting-reset", title: "5-Min Pre-Meeting Reset with God", description: "Center your heart before an important meeting or conversation.", category: "focus", duration_minutes: 5, image_url: "https://images.unsplash.com/photo-1523419409543-3e4f83b9b8f2?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Take a few slow breaths. Bring the upcoming meeting or conversation to mind. Acknowledge any anxiety, pressure, or expectations you feel.\n\nPray simply: \"Lord, go before me. Give me wisdom, peace, and grace.\" Imagine Him already in the room, preparing hearts and guiding the outcome.\n\nAs you breathe, release the need to control everything. Trust that God is with you, and that your worth is not defined by how this meeting goes." },
  { id: "gm-14-creative-flow", title: "10-Min Creative Flow with the Creator", description: "Invite God into your creativity and work.", category: "mindfulness", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit comfortably and breathe deeply. Remember that God is the ultimate Creator, and He has placed creativity inside of you.\n\nBring your current project or idea to mind. Ask, \"Lord, inspire me. Show me what I can't see on my own.\" As you breathe, imagine His creativity flowing through you like a gentle stream.\n\nRelease perfectionism and fear of failure. Instead, focus on partnering with God in the process. Let this time reawaken joy and freedom in your creative work." },
  { id: "gm-15-walking-meditation", title: "12-Min Walking with Jesus", description: "Turn a simple walk into a prayerful time with Jesus.", category: "mindfulness", duration_minutes: 12, image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800", ambient_url: "/ambient/forest_birds.mp3", script: "As you walk, slow your pace slightly and become aware of your steps. With each step, imagine walking side by side with Jesus.\n\nNotice your surroundings—the sky, the trees, the sounds. Thank God for the beauty around you, even in small details. Let your walk become a moving conversation with Him.\n\nIf worries arise, talk to Him about them as you walk. If gratitude rises, express it. Let this simple act of walking become a reminder that you never walk alone." },
  { id: "gm-16-mindful-eating", title: "8-Min Mindful Eating with Gratitude", description: "Invite God into your relationship with food and your body.", category: "gratitude", duration_minutes: 8, image_url: "https://images.unsplash.com/photo-1543353071-873f17a7a088?w=800", ambient_url: "/ambient/calm_river.mp3", script: "Before you eat, pause and take a breath. Look at the food in front of you and thank God for His provision.\n\nAs you take each bite, slow down. Notice the flavors and textures. Let this be a moment of receiving, not rushing. If guilt or shame about food or your body arises, bring it to God honestly.\n\nRemember that your body is a temple of the Holy Spirit, and He cares about your nourishment and well-being. Let this meal be an act of gratitude, not punishment." },
  { id: "gm-17-parenting-patience", title: "9-Min Parenting Patience with God", description: "Refuel your patience and grace as a parent in God's presence.", category: "healing", duration_minutes: 9, image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Sit quietly and take a few deep breaths. Think about your children and the weight of responsibility you carry. Acknowledge the moments you felt impatient, overwhelmed, or guilty.\n\nBring those moments to God and hear Him say, \"My grace is sufficient for you.\" You are not parenting alone. Ask Him for fresh patience, wisdom, and tenderness.\n\nAs you breathe, picture His love flowing through you to your children. You won't be a perfect parent, but you can be a present one, anchored in His grace." },
  { id: "gm-18-morning-warrior", title: "10-Min Spiritual Warrior Morning", description: "Start your day spiritually armored and focused.", category: "confidence", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1523419409543-3e4f83b9b8f2?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit or stand tall. Take a deep breath and imagine putting on the armor of God—belt of truth, breastplate of righteousness, shoes of peace, shield of faith, helmet of salvation, and sword of the Spirit.\n\nAs you breathe, declare quietly: \"I am covered by God's protection. I am guided by His wisdom. I am strengthened by His Spirit.\" Picture yourself stepping into the day not in your own strength, but in His.\n\nLet this time remind you that you are not defenseless or alone. You are a beloved child of God, equipped for whatever comes." },
  { id: "gm-19-grief-and-hope", title: "15-Min Grief and Hope with God", description: "Bring your grief to God and hold onto hope in Him.", category: "healing", duration_minutes: 15, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Find a quiet place and sit or lie down. Take a few slow breaths. Acknowledge the grief you carry—loss, disappointment, or heartbreak. You don't have to minimize it here.\n\nTell God honestly how you feel. If tears come, let them. He is not uncomfortable with your pain. Remember that Jesus wept too, and He understands sorrow.\n\nAs you breathe, ask Him to hold your heart gently. You may not have all the answers, but you can rest in His presence. Let a small seed of hope remain: that He is still good, still near, and still writing your story." },
  { id: "gm-20-lunch-break-reset", title: "7-Min Lunch Break Reset with God", description: "Use your lunch break to reconnect with God and reset your mind.", category: "mindfulness", duration_minutes: 7, image_url: "https://images.unsplash.com/photo-1543353071-873f17a7a088?w=800", ambient_url: "/ambient/calm_river.mp3", script: "During your break, find a quiet spot if you can. Take a few slow breaths and let your shoulders relax. Acknowledge how the first half of your day has felt.\n\nInvite God into it: \"Lord, thank You for bringing me this far. Be with me in what's ahead.\" As you breathe, release any tension or frustration you've been holding.\n\nLet this short pause remind you that your value is not in your productivity, but in being God's child. Return to your day a little lighter, a little more aware of His presence." },
  { id: "gm-21-sabbath-slowdown", title: "12-Min Sabbath Slowdown", description: "Practice slowing your soul in God's rest.", category: "reflection", duration_minutes: 12, image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Sit or lie down in a restful position. Take a deep breath and exhale slowly. Reflect on God's invitation to rest, not as a reward, but as a gift.\n\nThink about the areas where you've been striving or pushing too hard. Offer them to God and hear Him say, \"Be still, and know that I am God.\" Let your body and mind slow down as you breathe.\n\nAllow this time to be unproductive in the world's eyes, but deeply fruitful in your soul. Rest is holy. Let God refresh you here." },
  { id: "gm-22-anger-release", title: "9-Min Anger Release with God", description: "Bring your anger to God instead of stuffing it down.", category: "healing", duration_minutes: 9, image_url: "https://images.unsplash.com/photo-1523419409543-3e4f83b9b8f2?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Sit and take a few deep breaths. Acknowledge the anger you feel—toward a situation, a person, or even yourself. You don't have to pretend it's not there.\n\nTell God honestly what you're angry about. He can handle your honesty. As you breathe, imagine placing that anger into His hands, not to deny it, but to let Him hold it with you.\n\nAsk Him for wisdom on what to do next, and for the strength to respond in love, not just reaction. Let your breath become a way of releasing what you cannot control." },
  { id: "gm-23-identity-in-christ", title: "10-Min Identity in Christ", description: "Meditate on who God says you are.", category: "confidence", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit comfortably and breathe slowly. Think about the labels the world has put on you—or that you've put on yourself. Notice how they make you feel.\n\nNow bring to mind truths from Scripture: \"I am a child of God. I am forgiven. I am chosen. I am loved.\" As you breathe, repeat one of these truths slowly, letting it sink deeper than the lies.\n\nPicture God speaking these words over you with tenderness and authority. Let your identity be anchored not in what you do, but in whose you are." },
  { id: "gm-24-couples-prayer", title: "12-Min Couples Prayer and Peace", description: "Slow down together and invite God into your relationship.", category: "compassion", duration_minutes: 12, image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", ambient_url: "/ambient/calm_river.mp3", script: "If possible, sit together and hold hands. Take a few slow breaths in unison. Acknowledge that God is present with both of you right now.\n\nTake turns silently thanking God for one thing about each other. Then, bring any tensions or worries in your relationship before Him. You don't have to fix everything in this moment—just be honest together.\n\nAsk God to strengthen your unity, deepen your love, and guide your steps. Let this time remind you that your relationship is not just between two people, but a cord of three strands with Him at the center." },
  { id: "gm-25-workday-commute", title: "8-Min Commute with Christ", description: "Turn your commute into a time of connection with God.", category: "mindfulness", duration_minutes: 8, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "As you travel, become aware of your breath and your surroundings. Instead of scrolling or rushing mentally, invite God into this in-between space.\n\nTalk to Him about what you're heading into or what you're coming from. Share your hopes, fears, and needs. Then spend a few moments simply listening in silence.\n\nLet this commute be more than just movement from point A to B. Let it be a reminder that God is with you in the ordinary moments too." },
  { id: "gm-26-sunday-reset", title: "10-Min Sunday Reset with God", description: "Reflect on the week and reset your heart for what's ahead.", category: "reflection", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit quietly and breathe slowly. Look back over the past week—its highs, lows, and everything in between. Invite God to show you where He was present, even if you missed it at the time.\n\nThank Him for His faithfulness, even in the small things. Confess where you drifted or tried to do life on your own. Receive His forgiveness and grace.\n\nAs you breathe, ask Him to prepare your heart for the week ahead. Let this be a moment of reset, not in your own strength, but in His." },
  { id: "gm-27-anxiety-night", title: "12-Min Night Anxiety Release", description: "Release nighttime anxiety into God's hands before sleep.", category: "sleep", duration_minutes: 12, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/soft_wind.mp3", script: "Lie down and take a few slow breaths. Notice the worries that tend to get louder at night. Instead of fighting them, bring them one by one to God.\n\nPicture placing each worry into His hands. With each exhale, say quietly, \"Lord, I trust You with this.\" You may need to repeat it, and that's okay.\n\nLet His peace guard your heart and mind as you prepare for sleep. You don't have to solve everything tonight. You can rest because He does not." },
  { id: "gm-28-morning-scripture-meditation", title: "10-Min Scripture Meditation", description: "Slowly meditate on a single verse with God.", category: "mindfulness", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800", ambient_url: "/ambient/calm_river.mp3", script: "Choose a verse such as, \"The Lord is my shepherd; I shall not want.\" Sit comfortably and breathe slowly.\n\nRepeat the verse in your mind, one phrase at a time. After each phrase, pause and notice what stands out. Ask God, \"What do You want me to see here?\"\n\nLet the verse move from your head to your heart. This is not about rushing through Scripture, but letting Scripture rest in you." },
  { id: "gm-29-gratitude-before-bed", title: "8-Min Gratitude Before Bed", description: "End your day by thanking God for His faithfulness.", category: "gratitude", duration_minutes: 8, image_url: "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800", ambient_url: "/ambient/warm_piano.mp3", script: "Lie down or sit comfortably. Take a few slow breaths and think back over your day. Ask God to highlight moments of grace, protection, or provision.\n\nName three things you're grateful for, big or small. Thank Him specifically for each one. Let gratitude soften any lingering frustration or disappointment.\n\nEnd by thanking Him simply for being with you today. Let that awareness carry you into rest." },
  { id: "gm-30-breath-of-the-spirit", title: "10-Min Breath of the Spirit", description: "Breathe deeply and invite the Holy Spirit to fill you.", category: "breathing", duration_minutes: 10, image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800", ambient_url: "/ambient/deep_space_pad.mp3", script: "Sit comfortably and close your eyes. Take a slow breath in and out. Invite the Holy Spirit to be present: \"Holy Spirit, fill me.\"\n\nAs you inhale, imagine breathing in His peace, wisdom, and strength. As you exhale, release fear, confusion, and striving. Let your breath become a prayer.\n\nYou are not empty; you are a temple of the Holy Spirit. Rest in that truth as you breathe with Him for these next few minutes." }
];

export async function resetReseedBackfill() {
  try {
    console.log("\n[Reset] Starting RESET + RESEED + BACKFILL…\n");

    // 1. DELETE ALL EXISTING MEDITATIONS
    console.log("[Reset] Deleting all existing meditations…");
    const existing = await base44.entities.Meditation.list();
    for (const med of existing) {
      await base44.entities.Meditation.delete(med.id);
    }
    console.log(`[Reset] ✓ Deleted ${existing.length} meditations`);

    // 2. DELETE ALL EXISTING TTS JOBS
    console.log("[Reset] Deleting all existing TTS jobs…");
    const existingJobs = await base44.entities.TTSJob.list();
    for (const job of existingJobs) {
      await base44.entities.TTSJob.delete(job.id);
    }
    console.log(`[Reset] ✓ Deleted ${existingJobs.length} TTS jobs`);

    // 3. RESEED ALL 30 MEDITATIONS
    console.log("[Reset] Reseeding all 30 meditations…");
    for (const med of GUIDED_MEDITATIONS_SEED) {
      await base44.entities.Meditation.create({
        id: med.id,
        title: med.title,
        description: med.description,
        category: med.category,
        duration_minutes: med.duration_minutes,
        image_url: med.image_url,
        script: med.script,
        ambient_url: med.ambient_url,
        status: "pending",
        tts_audio_url: null
      });
    }
    console.log(`[Reset] ✓ Reseeded ${GUIDED_MEDITATIONS_SEED.length} meditations`);

    // 4. QUEUE TTS JOBS FOR ALL 30
    console.log("[Reset] Queuing TTS jobs…");
    const seeded = await base44.entities.Meditation.list();
    for (const med of seeded) {
      await base44.entities.TTSJob.create({
        meditation_id: med.id,
        status: "pending",
        attempts: 0
      });
    }
    console.log(`[Reset] ✓ Queued ${seeded.length} TTS jobs`);

    console.log("\n[Reset] ✓ Reset + Reseed + Backfill completed successfully\n");

    return {
      success: true,
      message: "Reset + Reseed + Backfill completed successfully",
      meditationsCount: seeded.length,
      jobsQueued: seeded.length
    };
  } catch (err) {
    console.error("[Reset] Error:", err);
    throw err;
  }
}