import { useState, useEffect, useCallback } from 'react';

const STORAGE_KEY = 'anchor_grocery_list';

function load() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch {
    return [];
  }
}

function save(items) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
}

// Each item: { id, ingredient, recipeTitle, recipeId, category, checked }
function categorise(ingredient) {
  const n = ingredient.toLowerCase();
  if (/\b(chicken|beef|pork|fish|salmon|tuna|shrimp|turkey|lamb|bacon|sausage|egg|tofu|tempeh)\b/.test(n)) return 'Protein & Meat';
  if (/\b(tomato|lettuce|spinach|kale|onion|garlic|pepper|carrot|broccoli|celery|cucumber|zucchini|mushroom|avocado|potato|sweet potato|corn|peas|beans|lentil|apple|banana|berry|lemon|lime|orange|fruit|vegetable|herb|basil|cilantro|parsley|ginger)\b/.test(n)) return 'Produce';
  if (/\b(milk|cheese|yogurt|butter|cream|sour cream|parmesan|mozzarella|cheddar)\b/.test(n)) return 'Dairy';
  if (/\b(rice|pasta|bread|flour|oat|quinoa|grain|tortilla|cracker|cereal|couscous|barley|noodle)\b/.test(n)) return 'Grains & Bread';
  if (/\b(oil|olive oil|coconut oil|salt|pepper|spice|paprika|cumin|turmeric|cinnamon|oregano|thyme|sauce|vinegar|sugar|honey|maple|soy sauce|mustard|ketchup|mayo|stock|broth|tomato paste|coconut milk)\b/.test(n)) return 'Pantry & Spices';
  if (/\b(almond|walnut|cashew|peanut|seed|flax|chia|sunflower|pine nut)\b/.test(n)) return 'Nuts & Seeds';
  return 'Other';
}

export function useGroceryList() {
  const [items, setItems] = useState(load);

  useEffect(() => { save(items); }, [items]);

  const addRecipe = useCallback((recipe) => {
    setItems(prev => {
      const newItems = (recipe.ingredients || [])
        .filter(ing => !prev.some(i => i.ingredient.toLowerCase() === ing.toLowerCase() && i.recipeId === recipe.id))
        .map((ing, idx) => ({
          id: `${recipe.id}-${idx}-${Date.now()}`,
          ingredient: ing,
          recipeTitle: recipe.title,
          recipeId: recipe.id,
          category: categorise(ing),
          checked: false,
        }));
      return [...prev, ...newItems];
    });
  }, []);

  const removeRecipe = useCallback((recipeId) => {
    setItems(prev => prev.filter(i => i.recipeId !== recipeId));
  }, []);

  const toggleItem = useCallback((id) => {
    setItems(prev => prev.map(i => i.id === id ? { ...i, checked: !i.checked } : i));
  }, []);

  const removeItem = useCallback((id) => {
    setItems(prev => prev.filter(i => i.id !== id));
  }, []);

  const clearChecked = useCallback(() => {
    setItems(prev => prev.filter(i => !i.checked));
  }, []);

  const clearAll = useCallback(() => { setItems([]); }, []);

  const isRecipeAdded = useCallback((recipeId) => items.some(i => i.recipeId === recipeId), [items]);

  // Grouped by category, sorted
  const grouped = items.reduce((acc, item) => {
    const cat = item.category;
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(item);
    return acc;
  }, {});

  const CATEGORY_ORDER = ['Produce', 'Protein & Meat', 'Dairy', 'Grains & Bread', 'Pantry & Spices', 'Nuts & Seeds', 'Other'];
  const sortedGrouped = CATEGORY_ORDER.filter(c => grouped[c]).map(c => ({ category: c, items: grouped[c] }));

  const totalCount   = items.length;
  const checkedCount = items.filter(i => i.checked).length;

  const download = useCallback(() => {
    const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    let text = `🛒  GROCERY LIST\n`;
    text += `    ${date}\n`;
    text += `${'─'.repeat(40)}\n\n`;

    const ICONS = { 'Produce': '🥬', 'Protein & Meat': '🍗', 'Dairy': '🥛', 'Grains & Bread': '🌾', 'Pantry & Spices': '🧂', 'Nuts & Seeds': '🥜', 'Other': '📦' };

    sortedGrouped.forEach(({ category, items: catItems }) => {
      text += `${ICONS[category] || '•'}  ${category.toUpperCase()}\n`;
      text += `${'-'.repeat(30)}\n`;
      catItems.forEach(item => {
        text += `  ☐  ${item.ingredient}\n`;
        text += `       (${item.recipeTitle})\n`;
      });
      text += '\n';
    });

    text += `${'─'.repeat(40)}\n`;
    text += `Total items: ${totalCount}  ·  Generated by Prosperity Revived\n`;

    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `grocery-list-${new Date().toISOString().slice(0,10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [sortedGrouped, totalCount]);

  return { items, grouped: sortedGrouped, totalCount, checkedCount, addRecipe, removeRecipe, toggleItem, removeItem, clearChecked, clearAll, isRecipeAdded, download };
}
