export const GRACE_MOMENTS = [
  { message: "God's grace doesn't run out. Not today, not ever.", verse: "\u201cMy grace is sufficient for you, for my power is made perfect in weakness.\u201d \u2014 2 Corinthians 12:9" },
  { message: "You are loved not because of what you do, but because of who God says you are.", verse: "\u201cSee what great love the Father has lavished on us, that we should be called children of God!\u201d \u2014 1 John 3:1" },
  { message: "Your past doesn't define you. God's mercies are new every morning.", verse: "\u201cHis compassions never fail. They are new every morning; great is your faithfulness.\u201d \u2014 Lamentations 3:22-23" },
  { message: "Rest in this: you don't have to earn what has already been freely given.", verse: "\u201cFor it is by grace you have been saved, through faith \u2014 and this is not from yourselves, it is the gift of God.\u201d \u2014 Ephesians 2:8" },
  { message: "God is not disappointed in you. He is running toward you.", verse: "\u201cBut while he was still a long way off, his father saw him and was filled with compassion for him.\u201d \u2014 Luke 15:20" },
  { message: "Forgiveness isn't just offered once. It's woven into the nature of God.", verse: "\u201cIf we confess our sins, he is faithful and just and will forgive us our sins.\u201d \u2014 1 John 1:9" },
  { message: "You are held \u2014 even in the moments you feel most alone.", verse: "\u201cFor I am the Lord your God who takes hold of your right hand and says, Do not fear; I will help you.\u201d \u2014 Isaiah 41:13" },
  { message: "Grace says: come as you are. God will handle the rest.", verse: "\u201cCome to me, all you who are weary and burdened, and I will give you rest.\u201d \u2014 Matthew 11:28" },
  { message: "You don't have to be perfect for God to use you. He specializes in the broken.", verse: "\u201cWhen I am weak, then I am strong.\u201d \u2014 2 Corinthians 12:10" },
  { message: "God's love for you is not based on your performance today.", verse: "\u201cNeither height nor depth... will be able to separate us from the love of God.\u201d \u2014 Romans 8:39" },
  { message: "When you feel unworthy, remember: grace doesn't wait for worthiness.", verse: "\u201cBut God demonstrates his own love for us in this: While we were still sinners, Christ died for us.\u201d \u2014 Romans 5:8" },
  { message: "You are not your worst day. God sees the full story \u2014 and He's not done writing it.", verse: "\u201cBeing confident of this, that he who began a good work in you will carry it on to completion.\u201d \u2014 Philippians 1:6" },
  { message: "Peace isn't the absence of trouble. It's the presence of God in the middle of it.", verse: "\u201cPeace I leave with you; my peace I give you... Do not let your hearts be troubled.\u201d \u2014 John 14:27" },
  { message: "Your weakness is not a disqualification \u2014 it's an invitation for His strength.", verse: "\u201cWhen I am weak, then I am strong.\u201d \u2014 2 Corinthians 12:10" },
  { message: "Grace is not a reward. It is the very ground you stand on.", verse: "\u201cThrough whom we have gained access by faith into this grace in which we now stand.\u201d \u2014 Romans 5:2" },
  { message: "God chose you \u2014 not because you had it together, but because He is love.", verse: "\u201cFor he chose us in him before the creation of the world to be holy and blameless in his sight.\u201d \u2014 Ephesians 1:4" },
  { message: "You are not too far gone. No one is beyond the reach of grace.", verse: "\u201cWhere sin increased, grace increased all the more.\u201d \u2014 Romans 5:20" },
  { message: "Today is a fresh start. Yesterday's failures don't get to follow you here.", verse: "\u201cForget the former things; do not dwell on the past. See, I am doing a new thing!\u201d \u2014 Isaiah 43:18-19" },
  { message: "You were seen before you were formed. You are known and still loved.", verse: "\u201cBefore I formed you in the womb I knew you.\u201d \u2014 Jeremiah 1:5" },
  { message: "Shame says hide. Grace says come closer.", verse: "\u201cThere is now no condemnation for those who are in Christ Jesus.\u201d \u2014 Romans 8:1" },
  { message: "God isn't counting your failures. He's counting on your future.", verse: "\u201cFor I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.\u201d \u2014 Jeremiah 29:11" },
  { message: "You don't have to carry this alone. Grace was made for exactly this moment.", verse: "\u201cCast all your anxiety on him because he cares for you.\u201d \u2014 1 Peter 5:7" },
  { message: "God meets you in the valley \u2014 not just on the mountaintop.", verse: "\u201cEven though I walk through the darkest valley, I will fear no evil, for you are with me.\u201d \u2014 Psalm 23:4" },
  { message: "You are enough. Not because of you \u2014 because of whose you are.", verse: "\u201cI can do all this through him who gives me strength.\u201d \u2014 Philippians 4:13" },
  { message: "Grace doesn't excuse the past. It just refuses to let it define the future.", verse: "\u201cTherefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!\u201d \u2014 2 Corinthians 5:17" },
  { message: "God's patience with you is not running thin. It is running deep.", verse: "\u201cThe Lord is not slow in keeping his promise... Instead he is patient with you.\u201d \u2014 2 Peter 3:9" },
  { message: "Even when you wander, there is always a way home.", verse: "\u201cReturn to me, for I have redeemed you.\u201d \u2014 Isaiah 44:22" },
  { message: "You were never meant to earn your way to God. Grace already built the bridge.", verse: "\u201cFor God so loved the world that he gave his one and only Son.\u201d \u2014 John 3:16" },
  { message: "Breathe. You are held by hands that have never once let go.", verse: "\u201cI give them eternal life, and they shall never perish; no one will snatch them out of my hand.\u201d \u2014 John 10:28" },
  { message: "Today's struggles are not evidence that God has forgotten you.", verse: "\u201cAnd we know that in all things God works for the good of those who love him.\u201d \u2014 Romans 8:28" },
  { message: "You don't have to figure it all out. Just take the next faithful step.", verse: "\u201cYour word is a lamp for my feet, a light on my path.\u201d \u2014 Psalm 119:105" },
  { message: "God's love is not fragile. It does not crack under the weight of your hardest days.", verse: "\u201cThe Lord your God is with you, the Mighty Warrior who saves.\u201d \u2014 Zephaniah 3:17" },
  { message: "You are not in this season by accident. God is up to something.", verse: "\u201cAnd we know that in all things God works for the good of those who love him.\u201d \u2014 Romans 8:28" },
  { message: "Even your smallest prayer reaches the ear of God.", verse: "\u201cThe Lord is near to all who call on him, to all who call on him in truth.\u201d \u2014 Psalm 145:18" },
  { message: "Grace is not a one-time event. It is a daily invitation.", verse: "\u201cLet us then approach God\u2019s throne of grace with confidence.\u201d \u2014 Hebrews 4:16" },
  { message: "You are not defined by what broke you \u2014 you are defined by what rebuilt you.", verse: "\u201cHe heals the brokenhearted and binds up their wounds.\u201d \u2014 Psalm 147:3" },
  { message: "Whatever you're facing today, you are not facing it alone.", verse: "\u201cThe Lord himself goes before you and will be with you.\u201d \u2014 Deuteronomy 31:8" },
  { message: "God's faithfulness is not contingent on yours.", verse: "\u201cIf we are faithless, he remains faithful, for he cannot disown himself.\u201d \u2014 2 Timothy 2:13" },
  { message: "You were made for more than survival. You were made to flourish.", verse: "\u201cI have come that they may have life, and have it to the full.\u201d \u2014 John 10:10" },
  { message: "Your story is not over. The best chapters are still being written.", verse: "\u201cFor I am confident of this, that he who began a good work in you will complete it.\u201d \u2014 Philippians 1:6" },
  { message: "God's mercy is not a last resort. It is a first response.", verse: "\u201cBecause of the Lord\u2019s great love we are not consumed, for his compassions never fail.\u201d \u2014 Lamentations 3:22" },
  { message: "You don't have to perform for God. He loves the real you.", verse: "\u201cThe Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.\u201d \u2014 1 Samuel 16:7" },
  { message: "Doubt and faith can exist in the same heart. God knows. He still shows up.", verse: "\u201cI do believe; help me overcome my unbelief!\u201d \u2014 Mark 9:24" },
  { message: "Your value is not up for debate. God settled it at the cross.", verse: "\u201cFor you know that it was not with perishable things... that you were redeemed.\u201d \u2014 1 Peter 1:18" },
  { message: "You are not a burden. You are a beloved child.", verse: "\u201cHow great is the love the Father has lavished on us, that we should be called children of God!\u201d \u2014 1 John 3:1" },
  { message: "When fear shows up, grace shows up bigger.", verse: "\u201cFor the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\u201d \u2014 2 Timothy 1:7" },
  { message: "Rest is not laziness. It is trust that God holds what you let go.", verse: "\u201cHe grants sleep to those he loves.\u201d \u2014 Psalm 127:2" },
  { message: "The same God who created the universe knows your name.", verse: "\u201cHe who created you, Jacob, he who formed you, Israel: Do not fear, for I have redeemed you; I have summoned you by name; you are mine.\u201d \u2014 Isaiah 43:1" },
  { message: "Nothing you carry today is too heavy for the one who carries you.", verse: "\u201cCast your cares on the Lord and he will sustain you.\u201d \u2014 Psalm 55:22" },
  { message: "God does not love you from a distance. He dwells with you.", verse: "\u201cAnd I will ask the Father, and he will give you another advocate to help you and be with you forever.\u201d \u2014 John 14:16" },
  { message: "Your tears are not wasted. God collects every one.", verse: "\u201cYou keep track of all my sorrows. You have collected all my tears in your bottle.\u201d \u2014 Psalm 56:8" },
  { message: "Today, let grace be louder than guilt.", verse: "\u201cTherefore, there is now no condemnation for those who are in Christ Jesus.\u201d \u2014 Romans 8:1" },
  { message: "You don't have to fix yourself before coming to God. Come broken. He's good at that.", verse: "\u201cA bruised reed he will not break, and a smoldering wick he will not snuff out.\u201d \u2014 Isaiah 42:3" },
  { message: "God's goodness is not seasonal. It is everlasting.", verse: "\u201cGive thanks to the Lord, for he is good; his love endures forever.\u201d \u2014 Psalm 107:1" },
  { message: "Even in waiting, you are not forgotten.", verse: "\u201cBut those who hope in the Lord will renew their strength.\u201d \u2014 Isaiah 40:31" },
  { message: "Grace is not just forgiveness. It is transformation.", verse: "\u201cAnd we all, who with unveiled faces contemplate the Lord\u2019s glory, are being transformed into his image.\u201d \u2014 2 Corinthians 3:18" },
  { message: "You are not fighting for victory. You are fighting from it.", verse: "\u201cBut thanks be to God! He gives us the victory through our Lord Jesus Christ.\u201d \u2014 1 Corinthians 15:57" },
  { message: "God is not in a hurry with you. His timing is not punishment.", verse: "\u201cHe has made everything beautiful in its time.\u201d \u2014 Ecclesiastes 3:11" },
  { message: "You are seen in the darkness. God's eyes never close.", verse: "\u201cHe who watches over you will not slumber.\u201d \u2014 Psalm 121:3" },
  { message: "You don't have to understand the season to trust the one who ordained it.", verse: "\u201cTrust in the Lord with all your heart and lean not on your own understanding.\u201d \u2014 Proverbs 3:5" },
  { message: "Grief is not a sign of weak faith. Even Jesus wept.", verse: "\u201cJesus wept.\u201d \u2014 John 11:35" },
  { message: "You are not an accident. Every detail of you was intentional.", verse: "\u201cFor you created my inmost being; you knit me together in my mother\u2019s womb.\u201d \u2014 Psalm 139:13" },
  { message: "The grace you show yourself today is a reflection of the grace God has shown you.", verse: "\u201cBe kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.\u201d \u2014 Ephesians 4:32" },
  { message: "You are covered. Not by what you've done, but by what He has done.", verse: "\u201cHe himself bore our sins in his body on the cross.\u201d \u2014 1 Peter 2:24" },
  { message: "Every time you rise after falling, grace is at work.", verse: "\u201cFor though the righteous fall seven times, they rise again.\u201d \u2014 Proverbs 24:16" },
  { message: "The enemy cannot have the last word. God always gets the final say.", verse: "\u201cNo weapon forged against you will prevail.\u201d \u2014 Isaiah 54:17" },
  { message: "You are not waiting for God to arrive. He is already here.", verse: "\u201cWhere can I go from your Spirit? Where can I flee from your presence?\u201d \u2014 Psalm 139:7" },
  { message: "What feels like an ending may be the beginning God has been preparing.", verse: "\u201cSee, I am doing a new thing! Now it springs up; do you not perceive it?\u201d \u2014 Isaiah 43:19" },
  { message: "God's love is not diminished by your worst moments.", verse: "\u201cI have loved you with an everlasting love; I have drawn you with unfailing kindness.\u201d \u2014 Jeremiah 31:3" },
  { message: "You were redeemed \u2014 not rented. You fully belong to God.", verse: "\u201cYou are not your own; you were bought at a price.\u201d \u2014 1 Corinthians 6:19-20" },
  { message: "In every storm, there is an anchor that holds.", verse: "\u201cWe have this hope as an anchor for the soul, firm and secure.\u201d \u2014 Hebrews 6:19" },
  { message: "God doesn't just tolerate you \u2014 He delights in you.", verse: "\u201cThe Lord your God is with you... he will take great delight in you... he will rejoice over you with singing.\u201d \u2014 Zephaniah 3:17" },
  { message: "You are not too needy for grace. That's exactly what grace is for.", verse: "\u201cLet us then approach God\u2019s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.\u201d \u2014 Hebrews 4:16" },
  { message: "Grace doesn't minimize your pain. It meets you inside of it.", verse: "\u201cHe was despised and rejected by mankind, a man of suffering, and familiar with pain.\u201d \u2014 Isaiah 53:3" },
  { message: "You are more than your diagnosis, your debt, your past, your fear.", verse: "\u201cI praise you because I am fearfully and wonderfully made.\u201d \u2014 Psalm 139:14" },
  { message: "God doesn't need you to be strong right now. Just willing.", verse: "\u201cMy power is made perfect in weakness.\u201d \u2014 2 Corinthians 12:9" },
  { message: "The grace that saved you is the same grace sustaining you today.", verse: "\u201cHe who began a good work in you will carry it on to completion.\u201d \u2014 Philippians 1:6" },
  { message: "Your prayers are never wasted, even the ones that felt like silence.", verse: "\u201cBefore they call I will answer; while they are still speaking I will hear.\u201d \u2014 Isaiah 65:24" },
  { message: "You are loved in the morning before you've done a single thing.", verse: "\u201cThis is the day the Lord has made; we will rejoice and be glad in it.\u201d \u2014 Psalm 118:24" },
  { message: "God is working in the invisible places of your life right now.", verse: "\u201cNow to him who is able to do immeasurably more than all we ask or imagine.\u201d \u2014 Ephesians 3:20" },
  { message: "You don't have to earn rest. God commands it.", verse: "\u201cHe makes me lie down in green pastures, he leads me beside quiet waters.\u201d \u2014 Psalm 23:2" },
  { message: "Every scar has a story. God sees the courage behind yours.", verse: "\u201cMy grace is sufficient for you.\u201d \u2014 2 Corinthians 12:9" },
  { message: "You are never too late to turn back toward God.", verse: "\u201cReturn to me, and I will return to you.\u201d \u2014 Malachi 3:7" },
  { message: "What you face today, grace faced first.", verse: "\u201cFor we do not have a high priest who is unable to empathize with our weaknesses.\u201d \u2014 Hebrews 4:15" },
  { message: "You matter to the story God is telling in the world.", verse: "\u201cFor we are God\u2019s handiwork, created in Christ Jesus to do good works.\u201d \u2014 Ephesians 2:10" },
  { message: "God's kindness is what leads hearts home \u2014 not fear, not shame.", verse: "\u201cGod\u2019s kindness is intended to lead you to repentance.\u201d \u2014 Romans 2:4" },
  { message: "You are never starting over from zero. You are starting over with everything you've learned.", verse: "\u201cThe Lord makes firm the steps of the one who delights in him.\u201d \u2014 Psalm 37:23" },
  { message: "God's arms are always open. You just have to walk toward them.", verse: "\u201cCome near to God and he will come near to you.\u201d \u2014 James 4:8" },
  { message: "Even the parts of you that feel unlovable are known and loved by God.", verse: "\u201cLord, you have examined me and know all about me.\u201d \u2014 Psalm 139:1" },
  { message: "Today's grace is enough for today. You don't need tomorrow's yet.", verse: "\u201cGive us today our daily bread.\u201d \u2014 Matthew 6:11" },
  { message: "God calls you worthy \u2014 not when you fix yourself, but right now.", verse: "\u201cFor it is God who works in you to will and to act in order to fulfill his good purpose.\u201d \u2014 Philippians 2:13" },
  { message: "You are not a burden to God. You are His joy.", verse: "\u201cFor the Lord takes delight in his people.\u201d \u2014 Psalm 149:4" },
  { message: "The silence you feel is not abandonment. God is still at work.", verse: "\u201cBe still, and know that I am God.\u201d \u2014 Psalm 46:10" },
  { message: "Your identity is not built on your performance. It is anchored in His promise.", verse: "\u201cSo you are no longer a slave, but God\u2019s child.\u201d \u2014 Galatians 4:7" },
  { message: "God is not surprised by anything you're going through today.", verse: "\u201cNothing in all creation is hidden from God\u2019s sight.\u201d \u2014 Hebrews 4:13" },
  { message: "You have permission to hope again. God specializes in resurrection.", verse: "\u201cI am the resurrection and the life.\u201d \u2014 John 11:25" },
  { message: "Grace is the antidote to perfectionism. You are not your track record.", verse: "\u201cHis mercies are new every morning.\u201d \u2014 Lamentations 3:23" },
  { message: "The same power that raised Christ from the dead lives inside of you.", verse: "\u201cAnd if the Spirit of him who raised Jesus from the dead is living in you...\u201d \u2014 Romans 8:11" },
  { message: "You don't have to pretend to be okay for God. He already knows \u2014 and He still loves.", verse: "\u201cFor he knows how we are formed, he remembers that we are dust.\u201d \u2014 Psalm 103:14" },
  { message: "Every act of courage today is an act of faith. God sees it.", verse: "\u201cHave I not commanded you? Be strong and courageous.\u201d \u2014 Joshua 1:9" },
  { message: "Your life is not an accident. It is a purpose in motion.", verse: "\u201cFor we are God\u2019s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.\u201d \u2014 Ephesians 2:10" },
  { message: "When you can't find the words to pray, God reads your heart.", verse: "\u201cThe Spirit himself intercedes for us through wordless groans.\u201d \u2014 Romans 8:26" },
  { message: "Grace is not earned in seasons of strength. It is received in seasons of surrender.", verse: "\u201cHumble yourselves, therefore, under God\u2019s mighty hand, that he may lift you up in due time.\u201d \u2014 1 Peter 5:6" },
  { message: "You are not condemned. You are commissioned.", verse: "\u201cGo and make disciples of all nations.\u201d \u2014 Matthew 28:19" },
  { message: "God doesn't keep score the way the world does. His ledger looks like love.", verse: "\u201cLove keeps no record of wrongs.\u201d \u2014 1 Corinthians 13:5" },
  { message: "Whatever season you are in, God has provision for it.", verse: "\u201cAnd my God will meet all your needs according to the riches of his glory in Christ Jesus.\u201d \u2014 Philippians 4:19" },
  { message: "You are not just surviving. You are becoming.", verse: "\u201cAnd we all... are being transformed into his image with ever-increasing glory.\u201d \u2014 2 Corinthians 3:18" },
  { message: "God's Word is not advice. It is a lifeline. Hold on.", verse: "\u201cFor the word of God is alive and active.\u201d \u2014 Hebrews 4:12" },
  { message: "You are anchored to a love that the storms cannot move.", verse: "\u201cI am convinced that neither death nor life... will be able to separate us from the love of God.\u201d \u2014 Romans 8:38-39" },
  { message: "In every moment of failure, grace is already there waiting.", verse: "\u201cBut where sin increased, grace increased all the more.\u201d \u2014 Romans 5:20" },
  { message: "God's plans for you are not cancelled by your detours.", verse: "\u201cMany are the plans in a person\u2019s heart, but it is the Lord\u2019s purpose that prevails.\u201d \u2014 Proverbs 19:21" },
  { message: "You are held together by a love stronger than anything pulling you apart.", verse: "\u201cHe is before all things, and in him all things hold together.\u201d \u2014 Colossians 1:17" },
  { message: "The grace that covers your past also covers today's mistakes. All of them.", verse: "\u201cAs far as the east is from the west, so far has he removed our transgressions from us.\u201d \u2014 Psalm 103:12" },
  { message: "You don't have to be fearless. You just have to be faithful.", verse: "\u201cDo not be afraid. Stand firm and you will see the deliverance the Lord will bring you today.\u201d \u2014 Exodus 14:13" },
  { message: "God is not a cosmic judge waiting to catch you. He is a Father running to meet you.", verse: "\u201cWhile he was still a long way off, his father saw him and was filled with compassion for him.\u201d \u2014 Luke 15:20" },
  { message: "Every moment you choose love, grace is at work through you.", verse: "\u201cDear friends, let us love one another, for love comes from God.\u201d \u2014 1 John 4:7" },
  { message: "You are not disqualified by your history. You are qualified by His grace.", verse: "\u201cHe has qualified you to share in the inheritance of his holy people in the kingdom of light.\u201d \u2014 Colossians 1:12" },
  { message: "Your deepest longings are known to God \u2014 and He is a God who satisfies.", verse: "\u201cHe satisfies the longing soul, and the hungry soul he fills with good things.\u201d \u2014 Psalm 107:9" },
  { message: "God's mercy meets you at your lowest point and lifts you.", verse: "\u201cHe lifted me out of the slimy pit, out of the mud and mire.\u201d \u2014 Psalm 40:2" },
  { message: "Grace is not a one-time transaction. It is a relationship.", verse: "\u201cRemain in me, as I also remain in you.\u201d \u2014 John 15:4" },
  { message: "The cross was the loudest declaration that you are worth saving.", verse: "\u201cFor God so loved the world that he gave his one and only Son.\u201d \u2014 John 3:16" },
  { message: "You are not defined by the worst thing that ever happened to you.", verse: "\u201cHe restores my soul.\u201d \u2014 Psalm 23:3" },
  { message: "When you feel invisible, remember: you are engraved on the palms of His hands.", verse: "\u201cSee, I have engraved you on the palms of my hands.\u201d \u2014 Isaiah 49:16" },
  { message: "God's timing looks slow from here. But His faithfulness looks perfect from the other side.", verse: "\u201cHe has made everything beautiful in its time.\u201d \u2014 Ecclesiastes 3:11" },
  { message: "Your mess is not the end of your story. It is the middle of your testimony.", verse: "\u201cAnd they overcame him by the blood of the Lamb and by the word of their testimony.\u201d \u2014 Revelation 12:11" },
  { message: "God never said the path would be easy. He said you wouldn't walk it alone.", verse: "\u201cAnd surely I am with you always, to the very end of the age.\u201d \u2014 Matthew 28:20" },
  { message: "Grace is the language God speaks most fluently.", verse: "\u201cThe Word became flesh and made his dwelling among us. We have seen his glory... full of grace and truth.\u201d \u2014 John 1:14" },
  { message: "Every deep breath you take today is a gift from a God who thought of you.", verse: "\u201cThe Spirit of God has made me; the breath of the Almighty gives me life.\u201d \u2014 Job 33:4" },
  { message: "You are not stuck. You are being prepared.", verse: "\u201cAnd the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you.\u201d \u2014 1 Peter 5:10" },
  { message: "God's Word over your life is stronger than any word spoken against you.", verse: "\u201cNo weapon forged against you will prevail, and you will refute every tongue that accuses you.\u201d \u2014 Isaiah 54:17" },
  { message: "You don't have to be extraordinary to be used by God. You just have to be available.", verse: "\u201cFor God chose the foolish things of the world to shame the wise.\u201d \u2014 1 Corinthians 1:27" },
  { message: "You are loved in your confusion, in your chaos, in your questioning.", verse: "\u201cFor I am convinced that neither death nor life... will be able to separate us from the love of God.\u201d \u2014 Romans 8:38-39" },
  { message: "God sees the faithfulness in the small things no one else notices.", verse: "\u201cWell done, good and faithful servant! You have been faithful with a few things.\u201d \u2014 Matthew 25:21" },
  { message: "Grace is bigger than your biggest regret.", verse: "\u201cIf we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.\u201d \u2014 1 John 1:9" },
  { message: "You are not too ordinary for an extraordinary God.", verse: "\u201cBut we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us.\u201d \u2014 2 Corinthians 4:7" },
  { message: "Even your questions are welcomed in the presence of God.", verse: "\u201cCall to me and I will answer you and tell you great and unsearchable things you do not know.\u201d \u2014 Jeremiah 33:3" },
  { message: "God's love doesn't fluctuate with your moods. It is constant.", verse: "\u201cJesus Christ is the same yesterday and today and forever.\u201d \u2014 Hebrews 13:8" },
  { message: "The fight you're in today is already won. You just have to walk it out.", verse: "\u201cThe Lord will fight for you; you need only to be still.\u201d \u2014 Exodus 14:14" },
  { message: "You are a dwelling place for God's Spirit. That is not a small thing.", verse: "\u201cDo you not know that your bodies are temples of the Holy Spirit?\u201d \u2014 1 Corinthians 6:19" },
  { message: "Your worth was established in eternity. It cannot be diminished by a single bad day.", verse: "\u201cBefore I formed you in the womb I knew you, before you were born I set you apart.\u201d \u2014 Jeremiah 1:5" },
  { message: "God is not withholding good from you. He is preparing you for it.", verse: "\u201cNo good thing does he withhold from those whose walk is blameless.\u201d \u2014 Psalm 84:11" },
  { message: "Lean into grace today. Not as an excuse, but as an invitation to become.", verse: "\u201cWork out your salvation with fear and trembling, for it is God who works in you.\u201d \u2014 Philippians 2:12-13" },
  { message: "You are deeply known and deeply loved. Both at the same time.", verse: "\u201cLord, you have examined me and know all about me.\u201d \u2014 Psalm 139:1" },
  { message: "Even if you walked away, grace walked with you \u2014 waiting.", verse: "\u201cReturn to the Lord your God, for he is gracious and compassionate.\u201d \u2014 Joel 2:13" },
  { message: "God's faithfulness in the past is the proof of His faithfulness for today.", verse: "\u201cKnow therefore that the Lord your God is God; he is the faithful God.\u201d \u2014 Deuteronomy 7:9" },
  { message: "You were made for connection \u2014 with God and with others. You are not meant to be alone.", verse: "\u201cIt is not good for the man to be alone.\u201d \u2014 Genesis 2:18" },
  { message: "The light inside you was put there by God. Don't let the world convince you it's gone out.", verse: "\u201cYou are the light of the world.\u201d \u2014 Matthew 5:14" },
  { message: "God is not comparing you to anyone else. He is calling you to be fully you.", verse: "\u201cI praise you because I am fearfully and wonderfully made.\u201d \u2014 Psalm 139:14" },
  { message: "Grace doesn't say your sin doesn't matter. It says it's already been paid for.", verse: "\u201cHe himself bore our sins in his body on the cross.\u201d \u2014 1 Peter 2:24" },
  { message: "Your healing may be slow. That doesn't mean it's not happening.", verse: "\u201cHe heals the brokenhearted and binds up their wounds.\u201d \u2014 Psalm 147:3" },
  { message: "God is not watching you fail. He is coaching you through.", verse: "\u201cThe Lord is my shepherd, I lack nothing.\u201d \u2014 Psalm 23:1" },
  { message: "When everything else shifts, God remains.", verse: "\u201cI the Lord do not change.\u201d \u2014 Malachi 3:6" },
  { message: "You are not just tolerated by God. You are treasured.", verse: "\u201cFor you are a people holy to the Lord your God. The Lord your God has chosen you out of all the peoples.\u201d \u2014 Deuteronomy 7:6" },
  { message: "Let today be the day you stop hiding and start receiving.", verse: "\u201cSeek the Lord while he may be found; call on him while he is near.\u201d \u2014 Isaiah 55:6" },
  { message: "God's voice is kinder than the voice of shame. Learn to tell the difference.", verse: "\u201cMy sheep listen to my voice; I know them, and they follow me.\u201d \u2014 John 10:27" },
  { message: "You are not disqualified by your doubts. Thomas doubted \u2014 and Jesus showed up.", verse: "\u201cStop doubting and believe.\u201d \u2014 John 20:27" },
  { message: "God meets you at the bottom of your resources and says, now watch.", verse: "\u201cWith God all things are possible.\u201d \u2014 Matthew 19:26" },
  { message: "In the gap between who you are and who you want to be, grace lives.", verse: "\u201cFor it is by grace you have been saved, through faith.\u201d \u2014 Ephesians 2:8" },
  { message: "You are not forgotten in the waiting room of unanswered prayer.", verse: "\u201cWait for the Lord; be strong and take heart and wait for the Lord.\u201d \u2014 Psalm 27:14" },
  { message: "God does not grade on a curve. He erases the test and writes 'beloved' in its place.", verse: "\u201cI will forgive their wickedness and will remember their sins no more.\u201d \u2014 Hebrews 8:12" },
  { message: "Even the parts of your story you're ashamed of are being redeemed.", verse: "\u201cAnd we know that in all things God works for the good of those who love him.\u201d \u2014 Romans 8:28" },
  { message: "God's presence is not reserved for your best moments. He is with you in all of them.", verse: "\u201cWhere can I go from your Spirit? Where can I flee from your presence?\u201d \u2014 Psalm 139:7" },
  { message: "You carry the Spirit of God within you. That changes everything.", verse: "\u201cFor the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\u201d \u2014 2 Timothy 1:7" },
  { message: "Your obedience today may be someone else's miracle tomorrow.", verse: "\u201cLet your light shine before others, that they may see your good deeds.\u201d \u2014 Matthew 5:16" },
  { message: "Gratitude is the natural response to grace. Begin there today.", verse: "\u201cGive thanks to the Lord, for he is good; his love endures forever.\u201d \u2014 Psalm 107:1" },
  { message: "God is at work in the seasons of stillness, not just the seasons of movement.", verse: "\u201cBe still, and know that I am God.\u201d \u2014 Psalm 46:10" },
  { message: "You are not alone in the dark. The darkness is not dark to God.", verse: "\u201cEven the darkness will not be dark to you; the night will shine like the day.\u201d \u2014 Psalm 139:12" },
  { message: "Whatever weight you are carrying today \u2014 lay it down. Grace is here.", verse: "\u201cCast all your anxiety on him because he cares for you.\u201d \u2014 1 Peter 5:7" },
  { message: "God sees the big picture. Trust the brushstroke you're in right now.", verse: "\u201cFor my thoughts are not your thoughts, neither are your ways my ways.\u201d \u2014 Isaiah 55:8" },
  { message: "You are a new creation \u2014 not a patched-up version of the old one.", verse: "\u201cTherefore, if anyone is in Christ, the new creation has come.\u201d \u2014 2 Corinthians 5:17" },
  { message: "God's grace is not just for sinners. It sustains the saints, too.", verse: "\u201cAnd God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.\u201d \u2014 2 Corinthians 9:8" },
  { message: "You are held in the hands that shaped the stars. Rest there.", verse: "\u201cThe eternal God is your refuge, and underneath are the everlasting arms.\u201d \u2014 Deuteronomy 33:27" },
  { message: "Grace is not the ceiling of your life. It is the floor.", verse: "\u201cFrom his fullness we have all received, grace upon grace.\u201d \u2014 John 1:16" },
  { message: "The God who holds the universe also holds your name in His heart.", verse: "\u201cI have summoned you by name; you are mine.\u201d \u2014 Isaiah 43:1" },
  { message: "There is no expiration date on God's love for you.", verse: "\u201cI have loved you with an everlasting love.\u201d \u2014 Jeremiah 31:3" },
  { message: "You are not walking toward grace. You are walking within it.", verse: "\u201cIn him we live and move and have our being.\u201d \u2014 Acts 17:28" },
  { message: "God doesn't just forgive \u2014 He forgets. Completely. Permanently.", verse: "\u201cFor I will forgive their wickedness and will remember their sins no more.\u201d \u2014 Hebrews 8:12" },
  { message: "Let the voice of truth be louder than the voice of fear today.", verse: "\u201cFor God has not given us a spirit of fear and timidity, but of power, love, and self-discipline.\u201d \u2014 2 Timothy 1:7" },
  { message: "Grace is the gift you didn't earn and can't lose. Receive it today.", verse: "\u201cFor it is by grace you have been saved, through faith \u2014 and this is not from yourselves, it is the gift of God.\u201d \u2014 Ephesians 2:8" },
  { message: "Your next chapter is not determined by your last one. God writes new beginnings.", verse: "\u201cBehold, I am making all things new.\u201d \u2014 Revelation 21:5" },
  { message: "God's compassion for you is not earned. It is inherited. You are His child.", verse: "\u201cAs a father has compassion on his children, so the Lord has compassion on those who fear him.\u201d \u2014 Psalm 103:13" },
  { message: "You are not wandering in this. God is leading you \u2014 even when the path is unclear.", verse: "\u201cHe guides me along the right paths for his name\u2019s sake.\u201d \u2014 Psalm 23:3" },
  { message: "Your worth isn't measured by productivity. You have value just by existing.", verse: "\u201cFor in him we live and move and have our being.\u201d \u2014 Acts 17:28" },
  { message: "God's grace is not a safety net. It is solid ground.", verse: "\u201cHe set my feet on a rock and gave me a firm place to stand.\u201d \u2014 Psalm 40:2" },
  { message: "Even in the mundane, God is present. Nothing is too small for His attention.", verse: "\u201cAre not two sparrows sold for a penny? Yet not one of them will fall to the ground outside your Father\u2019s care.\u201d \u2014 Matthew 10:29" },
  { message: "You don't have to earn your place at the table. You were invited before you were born.", verse: "\u201cFor he chose us in him before the creation of the world.\u201d \u2014 Ephesians 1:4" },
  { message: "Healing is not always instant. But it is always promised.", verse: "\u201cHe heals the brokenhearted and binds up their wounds.\u201d \u2014 Psalm 147:3" },
  { message: "God's mercies cover yesterday's mistakes and tomorrow's fears.", verse: "\u201cHis compassions never fail. They are new every morning.\u201d \u2014 Lamentations 3:22-23" },
  { message: "You are seen in your exhaustion. God offers rest, not judgment.", verse: "\u201cCome to me, all you who are weary and burdened, and I will give you rest.\u201d \u2014 Matthew 11:28" },
  { message: "The God who parted seas can handle what you're facing today.", verse: "\u201cIs anything too hard for the Lord?\u201d \u2014 Genesis 18:14" },
  { message: "You are a vessel of honor. God's Spirit dwells in you.", verse: "\u201cDo you not know that your bodies are temples of the Holy Spirit, who is in you?\u201d \u2014 1 Corinthians 6:19" },
  { message: "Grace is not just a theological concept. It is a daily experience waiting for you.", verse: "\u201cLet us then approach God\u2019s throne of grace with confidence.\u201d \u2014 Hebrews 4:16" },
  { message: "You don't have to manufacture strength today. God's strength is available to you right now.", verse: "\u201cHe gives strength to the weary and increases the power of the weak.\u201d \u2014 Isaiah 40:29" },
  { message: "Every moment you choose to trust is a victory \u2014 even if it doesn't feel like one.", verse: "\u201cThis is the victory that has overcome the world, even our faith.\u201d \u2014 1 John 5:4" },
  { message: "God's love story with humanity didn't end at the cross. It began there.", verse: "\u201cFor the joy set before him he endured the cross.\u201d \u2014 Hebrews 12:2" },
  { message: "You are not in competition with anyone. Your race is yours alone.", verse: "\u201cLet us run with perseverance the race marked out for us.\u201d \u2014 Hebrews 12:1" },
  { message: "Even your longing for God is a gift. He placed it there.", verse: "\u201cAs the deer pants for streams of water, so my soul pants for you, my God.\u201d \u2014 Psalm 42:1" },
  { message: "You are not running out of chances. God is the God of the second, third, and hundredth chance.", verse: "\u201cReturn to me, for I have redeemed you.\u201d \u2014 Isaiah 44:22" },
  { message: "The grace that found you when you were lost still holds you now.", verse: "\u201cFor the Son of Man came to seek and to save the lost.\u201d \u2014 Luke 19:10" },
  { message: "You don't have to be put together. Authentic beats polished in the kingdom of God.", verse: "\u201cGod opposes the proud but shows favor to the humble.\u201d \u2014 James 4:6" },
  { message: "Your pain is real. And so is God's ability to redeem it.", verse: "\u201cHe comforts us in all our troubles, so that we can comfort those in any trouble.\u201d \u2014 2 Corinthians 1:4" },
  { message: "You are not walking backward when you rest. You are being renewed.", verse: "\u201cEven youths grow tired and weary... but those who hope in the Lord will renew their strength.\u201d \u2014 Isaiah 40:30-31" },
  { message: "God's goodness will follow you all the days of your life. Not just the good ones.", verse: "\u201cSurely your goodness and love will follow me all the days of my life.\u201d \u2014 Psalm 23:6" },
  { message: "You are not a project for God to fix. You are a person He loves to be with.", verse: "\u201cThe Lord your God is with you... he will take great delight in you.\u201d \u2014 Zephaniah 3:17" },
  { message: "Grace whispers: you are forgiven, free, and fully loved. Believe it.", verse: "\u201cIt is for freedom that Christ has set us free.\u201d \u2014 Galatians 5:1" },
  { message: "Your tears water seeds of testimony you can't yet see.", verse: "\u201cThose who sow with tears will reap with songs of joy.\u201d \u2014 Psalm 126:5" },
  { message: "God is not afraid of your anger or your grief. Bring it all.", verse: "\u201cThe Lord is close to the brokenhearted.\u201d \u2014 Psalm 34:18" },
  { message: "You are being shaped, not shamed.", verse: "\u201cYet you, Lord, are our Father. We are the clay, you are the potter.\u201d \u2014 Isaiah 64:8" },
  { message: "Grace turns mourning into dancing. Not right away \u2014 but always, eventually.", verse: "\u201cYou turned my wailing into dancing.\u201d \u2014 Psalm 30:11" },
  { message: "God hears you. Right now, in this moment, He hears every word.", verse: "\u201cI love the Lord, for he heard my voice; he heard my cry for mercy.\u201d \u2014 Psalm 116:1" },
  { message: "You were not designed for condemnation. You were designed for freedom.", verse: "\u201cIt is for freedom that Christ has set us free.\u201d \u2014 Galatians 5:1" },
  { message: "Even your smallest act of faith moves mountains in the unseen.", verse: "\u201cTruly I tell you, if you have faith as small as a mustard seed... Nothing will be impossible for you.\u201d \u2014 Matthew 17:20" },
  { message: "God doesn't love you in theory. He loves you in person, in detail, in full.", verse: "\u201cBut God demonstrates his own love for us in this: While we were still sinners, Christ died for us.\u201d \u2014 Romans 5:8" },
  { message: "You are not an afterthought. You are a masterpiece in progress.", verse: "\u201cFor we are God\u2019s handiwork, created in Christ Jesus to do good works.\u201d \u2014 Ephesians 2:10" },
  { message: "In every moment of uncertainty, God remains certain about you.", verse: "\u201cThe Lord will fulfill his purpose for me; your steadfast love, O Lord, endures forever.\u201d \u2014 Psalm 138:8" },
  { message: "You are not behind. You are exactly where grace has you.", verse: "\u201cHe who began a good work in you will carry it on to completion.\u201d \u2014 Philippians 1:6" },
  { message: "God's mercies don't just cover sin. They cover sorrow, confusion, and weariness too.", verse: "\u201cHe heals the brokenhearted and binds up their wounds.\u201d \u2014 Psalm 147:3" },
  { message: "You were made to be loved, not endured. God loves you \u2014 fully, freely, forever.", verse: "\u201cI have loved you with an everlasting love.\u201d \u2014 Jeremiah 31:3" },
];