export const GRACE_MOMENTS = [
  { message: "God's grace doesn't run out. Not today, not ever.", verse: '"My grace is sufficient for you, for my power is made perfect in weakness." — 2 Corinthians 12:9' },
  { message: "You are loved not because of what you do, but because of who God says you are.", verse: '"See what great love the Father has lavished on us, that we should be called children of God!" — 1 John 3:1' },
  { message: "Your past doesn't define you. God's mercies are new every morning.", verse: '"His compassions never fail. They are new every morning; great is your faithfulness." — Lamentations 3:22-23' },
  { message: "Rest in this: you don't have to earn what has already been freely given.", verse: '"For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God." — Ephesians 2:8' },
  { message: "God is not disappointed in you. He is running toward you.", verse: '"But while he was still a long way off, his father saw him and was filled with compassion for him." — Luke 15:20' },
  { message: "Forgiveness isn't just offered once. It's woven into the nature of God.", verse: '"If we confess our sins, he is faithful and just and will forgive us our sins." — 1 John 1:9' },
  { message: "You are held — even in the moments you feel most alone.", verse: '"For I am the Lord your God who takes hold of your right hand and says, Do not fear; I will help you." — Isaiah 41:13' },
  { message: "Grace says: come as you are. God will handle the rest.", verse: '"Come to me, all you who are weary and burdened, and I will give you rest." — Matthew 11:28' },
  { message: "You don't have to be perfect for God to use you. He specializes in the broken.", verse: '"When I am weak, then I am strong." — 2 Corinthians 12:10' },
  { message: "God's love for you is not based on your performance today.", verse: '"Neither height nor depth... will be able to separate us from the love of God." — Romans 8:39' },
  { message: "When you feel unworthy, remember: grace doesn't wait for worthiness.", verse: '"But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." — Romans 5:8' },
  { message: "You are not your worst day. God sees the full story — and He's not done writing it.", verse: '"Being confident of this, that he who began a good work in you will carry it on to completion." — Philippians 1:6' },
  { message: "Peace isn't the absence of trouble. It's the presence of God in the middle of it.", verse: '"Peace I leave with you; my peace I give you... Do not let your hearts be troubled." — John 14:27' },
  { message: "Your weakness is not a disqualification — it's an invitation for His strength.", verse: '"When I am weak, then I am strong." — 2 Corinthians 12:10' },
  { message: "Grace is not a reward. It is the very ground you stand on.", verse: '"Through whom we have gained access by faith into this grace in which we now stand." — Romans 5:2' },
  { message: "God chose you — not because you had it together, but because He is love.", verse: '"For he chose us in him before the creation of the world to be holy and blameless in his sight." — Ephesians 1:4' },
  { message: "You are not too far gone. No one is beyond the reach of grace.", verse: '"Where sin increased, grace increased all the more." — Romans 5:20' },
  { message: "Today is a fresh start. Yesterday's failures don't get to follow you here.", verse: '"Forget the former things; do not dwell on the past. See, I am doing a new thing!" — Isaiah 43:18-19' },
  { message: "You were seen before you were formed. You are known and still loved.", verse: '"Before I formed you in the womb I knew you." — Jeremiah 1:5' },
  { message: "Shame says hide. Grace says come closer.", verse: '"There is now no condemnation for those who are in Christ Jesus." — Romans 8:1' },
  { message: "God isn't counting your failures. He's counting on your future.", verse: '"For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you." — Jeremiah 29:11' },
  { message: "You don't have to carry this alone. Grace was made for exactly this moment.", verse: '"Cast all your anxiety on him because he cares for you." — 1 Peter 5:7' },
  { message: "God meets you in the valley — not just on the mountaintop.", verse: '"Even though I walk through the darkest valley, I will fear no evil, for you are with me." — Psalm 23:4' },
  { message: "You are enough. Not because of you — because of whose you are.", verse: '"I can do all this through him who gives me strength." — Philippians 4:13' },
  { message: "Grace doesn't excuse the past. It just refuses to let it define the future.", verse: '"Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!" — 2 Corinthians 5:17' },
  { message: "God's patience with you is not running thin. It is running deep.", verse: '"The Lord is not slow in keeping his promise... Instead he is patient with you." — 2 Peter 3:9' },
  { message: "Even when you wander, there is always a way home.", verse: '"Return to me, for I have redeemed you." — Isaiah 44:22' },
  { message: "You were never meant to earn your way to God. Grace already built the bridge.", verse: '"For God so loved the world that he gave his one and only Son." — John 3:16' },
  { message: "Breathe. You are held by hands that have never once let go.", verse: '"I give them eternal life, and they shall never perish; no one will snatch them out of my hand." — John 10:28' },
  { message: "Today's struggles are not evidence that God has forgotten you.", verse: '"And we know that in all things God works for the good of those who love him." — Romans 8:28' },
  { message: "You don't have to figure it all out. Just take the next faithful step.", verse: '"Your word is a lamp for my feet, a light on my path." — Psalm 119:105' },
  { message: "God's love is not fragile. It does not crack under the weight of your hardest days.", verse: '"The Lord your God is with you, the Mighty Warrior who saves." — Zephaniah 3:17' },
  { message: "You are not in this season by accident. God is up to something.", verse: '"And we know that in all things God works for the good of those who love him." — Romans 8:28' },
  { message: "Even your smallest prayer reaches the ear of God.", verse: '"The Lord is near to all who call on him, to all who call on him in truth." — Psalm 145:18' },
  { message: "Grace is not a one-time event. It is a daily invitation.", verse: '"Let us then approach God\u2019s throne of grace with confidence." — Hebrews 4:16' },
  { message: "You are not defined by what broke you — you are defined by what rebuilt you.", verse: '"He heals the brokenhearted and binds up their wounds." — Psalm 147:3' },
  { message: "Whatever you're facing today, you are not facing it alone.", verse: '"The Lord himself goes before you and will be with you." — Deuteronomy 31:8' },
  { message: "God's faithfulness is not contingent on yours.", verse: '"If we are faithless, he remains faithful, for he cannot disown himself." — 2 Timothy 2:13' },
  { message: "You were made for more than survival. You were made to flourish.", verse: '"I have come that they may have life, and have it to the full." — John 10:10' },
  { message: "Your story is not over. The best chapters are still being written.", verse: '"For I am confident of this, that he who began a good work in you will complete it." — Philippians 1:6' },
  { message: "God's mercy is not a last resort. It is a first response.", verse: '"Because of the Lord's great love we are not consumed, for his compassions never fail." — Lamentations 3:22' },
  { message: "You don't have to perform for God. He loves the real you.", verse: '"The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart." — 1 Samuel 16:7' },
  { message: "Doubt and faith can exist in the same heart. God knows. He still shows up.", verse: '"I do believe; help me overcome my unbelief!" — Mark 9:24' },
  { message: "Your value is not up for debate. God settled it at the cross.", verse: '"For you know that it was not with perishable things... that you were redeemed." — 1 Peter 1:18' },
  { message: "You are not a burden. You are a beloved child.", verse: '"How great is the love the Father has lavished on us, that we should be called children of God!" — 1 John 3:1' },
  { message: "When fear shows up, grace shows up bigger.", verse: '"For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline." — 2 Timothy 1:7' },
  { message: "Rest is not laziness. It is trust that God holds what you let go.", verse: '"He grants sleep to those he loves." — Psalm 127:2' },
  { message: "The same God who created the universe knows your name.", verse: '"He who created you, Jacob, he who formed you, Israel: Do not fear, for I have redeemed you; I have summoned you by name; you are mine." — Isaiah 43:1' },
  { message: "Nothing you carry today is too heavy for the one who carries you.", verse: '"Cast your cares on the Lord and he will sustain you." — Psalm 55:22' },
  { message: "God does not love you from a distance. He dwells with you.", verse: '"And I will ask the Father, and he will give you another advocate to help you and be with you forever." — John 14:16' },
  { message: "Your tears are not wasted. God collects every one.", verse: '"You keep track of all my sorrows. You have collected all my tears in your bottle." — Psalm 56:8' },
  { message: "Today, let grace be louder than guilt.", verse: '"Therefore, there is now no condemnation for those who are in Christ Jesus." — Romans 8:1' },
  { message: "You don't have to fix yourself before coming to God. Come broken. He's good at that.", verse: '"A bruised reed he will not break, and a smoldering wick he will not snuff out." — Isaiah 42:3' },
  { message: "God's goodness is not seasonal. It is everlasting.", verse: '"Give thanks to the Lord, for he is good; his love endures forever." — Psalm 107:1' },
  { message: "Even in waiting, you are not forgotten.", verse: '"But those who hope in the Lord will renew their strength." — Isaiah 40:31' },
  { message: "Grace is not just forgiveness. It is transformation.", verse: '"And we all, who with unveiled faces contemplate the Lord's glory, are being transformed into his image." — 2 Corinthians 3:18' },
  { message: "You are not fighting for victory. You are fighting from it.", verse: '"But thanks be to God! He gives us the victory through our Lord Jesus Christ." — 1 Corinthians 15:57' },
  { message: "God is not in a hurry with you. His timing is not punishment.", verse: '"He has made everything beautiful in its time." — Ecclesiastes 3:11' },
  { message: "You are seen in the darkness. God's eyes never close.", verse: '"He who watches over you will not slumber." — Psalm 121:3' },
  { message: "You don't have to understand the season to trust the one who ordained it.", verse: '"Trust in the Lord with all your heart and lean not on your own understanding." — Proverbs 3:5' },
  { message: "Grief is not a sign of weak faith. Even Jesus wept.", verse: '"Jesus wept." — John 11:35' },
  { message: "You are not an accident. Every detail of you was intentional.", verse: '"For you created my inmost being; you knit me together in my mother's womb." — Psalm 139:13' },
  { message: "The grace you show yourself today is a reflection of the grace God has shown you.", verse: '"Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you." — Ephesians 4:32' },
  { message: "You are covered. Not by what you've done, but by what He has done.", verse: '"He himself bore our sins in his body on the cross." — 1 Peter 2:24' },
  { message: "Every time you rise after falling, grace is at work.", verse: '"For though the righteous fall seven times, they rise again." — Proverbs 24:16' },
  { message: "The enemy cannot have the last word. God always gets the final say.", verse: '"No weapon forged against you will prevail." — Isaiah 54:17' },
  { message: "You are not waiting for God to arrive. He is already here.", verse: '"Where can I go from your Spirit? Where can I flee from your presence?" — Psalm 139:7' },
  { message: "What feels like an ending may be the beginning God has been preparing.", verse: '"See, I am doing a new thing! Now it springs up; do you not perceive it?" — Isaiah 43:19' },
  { message: "God's love is not diminished by your worst moments.", verse: '"I have loved you with an everlasting love; I have drawn you with unfailing kindness." — Jeremiah 31:3' },
  { message: "You were redeemed — not rented. You fully belong to God.", verse: '"You are not your own; you were bought at a price." — 1 Corinthians 6:19-20' },
  { message: "In every storm, there is an anchor that holds.", verse: '"We have this hope as an anchor for the soul, firm and secure." — Hebrews 6:19' },
  { message: "God doesn't just tolerate you — He delights in you.", verse: '"The Lord your God is with you... he will take great delight in you... he will rejoice over you with singing." — Zephaniah 3:17' },
  { message: "You are not too needy for grace. That's exactly what grace is for.", verse: '"Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need." — Hebrews 4:16' },
  { message: "Grace doesn't minimize your pain. It meets you inside of it.", verse: '"He was despised and rejected by mankind, a man of suffering, and familiar with pain." — Isaiah 53:3' },
  { message: "You are more than your diagnosis, your debt, your past, your fear.", verse: '"I praise you because I am fearfully and wonderfully made." — Psalm 139:14' },
  { message: "God doesn't need you to be strong right now. Just willing.", verse: '"My power is made perfect in weakness." — 2 Corinthians 12:9' },
  { message: "The grace that saved you is the same grace sustaining you today.", verse: '"He who began a good work in you will carry it on to completion." — Philippians 1:6' },
  { message: "Your prayers are never wasted, even the ones that felt like silence.", verse: '"Before they call I will answer; while they are still speaking I will hear." — Isaiah 65:24' },
  { message: "You are loved in the morning before you've done a single thing.", verse: '"This is the day the Lord has made; we will rejoice and be glad in it." — Psalm 118:24' },
  { message: "God is working in the invisible places of your life right now.", verse: '"Now to him who is able to do immeasurably more than all we ask or imagine." — Ephesians 3:20' },
  { message: "You don't have to earn rest. God commands it.", verse: '"He makes me lie down in green pastures, he leads me beside quiet waters." — Psalm 23:2' },
  { message: "Every scar has a story. God sees the courage behind yours.", verse: '"My grace is sufficient for you." — 2 Corinthians 12:9' },
  { message: "You are never too late to turn back toward God.", verse: '"Return to me, and I will return to you." — Malachi 3:7' },
  { message: "What you face today, grace faced first.", verse: '"For we do not have a high priest who is unable to empathize with our weaknesses." — Hebrews 4:15' },
  { message: "You matter to the story God is telling in the world.", verse: '"For we are God's handiwork, created in Christ Jesus to do good works." — Ephesians 2:10' },
  { message: "God's kindness is what leads hearts home — not fear, not shame.", verse: '"God's kindness is intended to lead you to repentance." — Romans 2:4' },
  { message: "You are never starting over from zero. You are starting over with everything you've learned.", verse: '"The Lord makes firm the steps of the one who delights in him." — Psalm 37:23' },
  { message: "God's arms are always open. You just have to walk toward them.", verse: '"Come near to God and he will come near to you." — James 4:8' },
  { message: "Even the parts of you that feel unlovable are known and loved by God.", verse: '"Lord, you have examined me and know all about me." — Psalm 139:1' },
  { message: "Today's grace is enough for today. You don't need tomorrow's yet.", verse: '"Give us today our daily bread." — Matthew 6:11' },
  { message: "God calls you worthy — not when you fix yourself, but right now.", verse: '"For it is God who works in you to will and to act in order to fulfill his good purpose." — Philippians 2:13' },
  { message: "You are not a burden to God. You are His joy.", verse: '"For the Lord takes delight in his people." — Psalm 149:4' },
  { message: "The silence you feel is not abandonment. God is still at work.", verse: '"Be still, and know that I am God." — Psalm 46:10' },
  { message: "Your identity is not built on your performance. It is anchored in His promise.", verse: '"So you are no longer a slave, but God's child." — Galatians 4:7' },
  { message: "God is not surprised by anything you're going through today.", verse: '"Nothing in all creation is hidden from God's sight." — Hebrews 4:13' },
  { message: "You have permission to hope again. God specializes in resurrection.", verse: '"I am the resurrection and the life." — John 11:25' },
  { message: "Grace is the antidote to perfectionism. You are not your track record.", verse: '"His mercies are new every morning." — Lamentations 3:23' },
  { message: "The same power that raised Christ from the dead lives inside of you.", verse: '"And if the Spirit of him who raised Jesus from the dead is living in you..." — Romans 8:11' },
  { message: "You don't have to pretend to be okay for God. He already knows — and He still loves.", verse: '"For he knows how we are formed, he remembers that we are dust." — Psalm 103:14' },
  { message: "Every act of courage today is an act of faith. God sees it.", verse: '"Have I not commanded you? Be strong and courageous." — Joshua 1:9' },
  { message: "Your life is not an accident. It is a purpose in motion.", verse: '"For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do." — Ephesians 2:10' },
  { message: "When you can't find the words to pray, God reads your heart.", verse: '"The Spirit himself intercedes for us through wordless groans." — Romans 8:26' },
  { message: "Grace is not earned in seasons of strength. It is received in seasons of surrender.", verse: '"Humble yourselves, therefore, under God's mighty hand, that he may lift you up in due time." — 1 Peter 5:6' },
  { message: "You are not condemned. You are commissioned.", verse: '"Go and make disciples of all nations." — Matthew 28:19' },
  { message: "God doesn't keep score the way the world does. His ledger looks like love.", verse: '"Love keeps no record of wrongs." — 1 Corinthians 13:5' },
  { message: "Whatever season you are in, God has provision for it.", verse: '"And my God will meet all your needs according to the riches of his glory in Christ Jesus." — Philippians 4:19' },
  { message: "You are not just surviving. You are becoming.", verse: '"And we all... are being transformed into his image with ever-increasing glory." — 2 Corinthians 3:18' },
  { message: "God's Word is not advice. It is a lifeline. Hold on.", verse: '"For the word of God is alive and active." — Hebrews 4:12' },
  { message: "You are anchored to a love that the storms cannot move.", verse: '"I am convinced that neither death nor life... will be able to separate us from the love of God." — Romans 8:38-39' },
  { message: "In every moment of failure, grace is already there waiting.", verse: '"But where sin increased, grace increased all the more." — Romans 5:20' },
  { message: "God's plans for you are not cancelled by your detours.", verse: '"Many are the plans in a person's heart, but it is the Lord's purpose that prevails." — Proverbs 19:21' },
  { message: "You are held together by a love stronger than anything pulling you apart.", verse: '"He is before all things, and in him all things hold together." — Colossians 1:17' },
  { message: "The grace that covers your past also covers today's mistakes. All of them.", verse: '"As far as the east is from the west, so far has he removed our transgressions from us." — Psalm 103:12' },
  { message: "You don't have to be fearless. You just have to be faithful.", verse: '"Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today." — Exodus 14:13' },
  { message: "God is not a cosmic judge waiting to catch you. He is a Father running to meet you.", verse: '"While he was still a long way off, his father saw him and was filled with compassion for him." — Luke 15:20' },
  { message: "Every moment you choose love, grace is at work through you.", verse: '"Dear friends, let us love one another, for love comes from God." — 1 John 4:7' },
  { message: "You are not disqualified by your history. You are qualified by His grace.", verse: '"He has qualified you to share in the inheritance of his holy people in the kingdom of light." — Colossians 1:12' },
  { message: "Your deepest longings are known to God — and He is a God who satisfies.", verse: '"He satisfies the longing soul, and the hungry soul he fills with good things." — Psalm 107:9' },
  { message: "God's mercy meets you at your lowest point and lifts you.", verse: '"He lifted me out of the slimy pit, out of the mud and mire." — Psalm 40:2' },
  { message: "Grace is not a one-time transaction. It is a relationship.", verse: '"Remain in me, as I also remain in you." — John 15:4' },
  { message: "The cross was the loudest declaration that you are worth saving.", verse: '"For God so loved the world that he gave his one and only Son." — John 3:16' },
  { message: "You are not defined by the worst thing that ever happened to you.", verse: '"He restores my soul." — Psalm 23:3' },
  { message: "When you feel invisible, remember: you are engraved on the palms of His hands.", verse: '"See, I have engraved you on the palms of my hands." — Isaiah 49:16' },
  { message: "God's timing looks slow from here. But His faithfulness looks perfect from the other side.", verse: '"He has made everything beautiful in its time." — Ecclesiastes 3:11' },
  { message: "Your mess is not the end of your story. It is the middle of your testimony.", verse: '"And they overcame him by the blood of the Lamb and by the word of their testimony." — Revelation 12:11' },
  { message: "God never said the path would be easy. He said you wouldn't walk it alone.", verse: '"And surely I am with you always, to the very end of the age." — Matthew 28:20' },
  { message: "Grace is the language God speaks most fluently.", verse: '"The Word became flesh and made his dwelling among us. We have seen his glory... full of grace and truth." — John 1:14' },
  { message: "Every deep breath you take today is a gift from a God who thought of you.", verse: '"The Spirit of God has made me; the breath of the Almighty gives me life." — Job 33:4' },
  { message: "You are not stuck. You are being prepared.", verse: '"And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you." — 1 Peter 5:10' },
  { message: "God's Word over your life is stronger than any word spoken against you.", verse: '"No weapon forged against you will prevail, and you will refute every tongue that accuses you." — Isaiah 54:17' },
  { message: "You don't have to be extraordinary to be used by God. You just have to be available.", verse: '"For God chose the foolish things of the world to shame the wise." — 1 Corinthians 1:27' },
  { message: "You are loved in your confusion, in your chaos, in your questioning.", verse: '"For I am convinced that neither death nor life... will be able to separate us from the love of God." — Romans 8:38-39' },
  { message: "God sees the faithfulness in the small things no one else notices.", verse: '"Well done, good and faithful servant! You have been faithful with a few things." — Matthew 25:21' },
  { message: "Grace is bigger than your biggest regret.", verse: '"If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness." — 1 John 1:9' },
  { message: "You are not too ordinary for an extraordinary God.", verse: '"But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us." — 2 Corinthians 4:7' },
  { message: "Even your questions are welcomed in the presence of God.", verse: '"Call to me and I will answer you and tell you great and unsearchable things you do not know." — Jeremiah 33:3' },
  { message: "God's love doesn't fluctuate with your moods. It is constant.", verse: '"Jesus Christ is the same yesterday and today and forever." — Hebrews 13:8' },
  { message: "The fight you're in today is already won. You just have to walk it out.", verse: '"The Lord will fight for you; you need only to be still." — Exodus 14:14' },
  { message: "You are a dwelling place for God's Spirit. That is not a small thing.", verse: '"Do you not know that your bodies are temples of the Holy Spirit?" — 1 Corinthians 6:19' },
  { message: "Your worth was established in eternity. It cannot be diminished by a single bad day.", verse: '"Before I formed you in the womb I knew you, before you were born I set you apart." — Jeremiah 1:5' },
  { message: "God is not withholding good from you. He is preparing you for it.", verse: '"No good thing does he withhold from those whose walk is blameless." — Psalm 84:11' },
  { message: "Lean into grace today. Not as an excuse, but as an invitation to become.", verse: '"Work out your salvation with fear and trembling, for it is God who works in you." — Philippians 2:12-13' },
  { message: "You are deeply known and deeply loved. Both at the same time.", verse: '"Lord, you have examined me and know all about me." — Psalm 139:1' },
  { message: "Even if you walked away, grace walked with you — waiting.", verse: '"Return to the Lord your God, for he is gracious and compassionate." — Joel 2:13' },
  { message: "God's faithfulness in the past is the proof of His faithfulness for today.", verse: '"Know therefore that the Lord your God is God; he is the faithful God." — Deuteronomy 7:9' },
  { message: "You were made for connection — with God and with others. You are not meant to be alone.", verse: '"It is not good for the man to be alone." — Genesis 2:18' },
  { message: "The light inside you was put there by God. Don't let the world convince you it's gone out.", verse: '"You are the light of the world." — Matthew 5:14' },
  { message: "God is not comparing you to anyone else. He is calling you to be fully you.", verse: '"I praise you because I am fearfully and wonderfully made." — Psalm 139:14' },
  { message: "Grace doesn't say your sin doesn't matter. It says it's already been paid for.", verse: '"He himself bore our sins in his body on the cross." — 1 Peter 2:24' },
  { message: "Your healing may be slow. That doesn't mean it's not happening.", verse: '"He heals the brokenhearted and binds up their wounds." — Psalm 147:3' },
  { message: "God is not watching you fail. He is coaching you through.", verse: '"The Lord is my shepherd, I lack nothing." — Psalm 23:1' },
  { message: "When everything else shifts, God remains.", verse: '"I the Lord do not change." — Malachi 3:6' },
  { message: "You are not just tolerated by God. You are treasured.", verse: '"For you are a people holy to the Lord your God. The Lord your God has chosen you out of all the peoples." — Deuteronomy 7:6' },
  { message: "Let today be the day you stop hiding and start receiving.", verse: '"Seek the Lord while he may be found; call on him while he is near." — Isaiah 55:6' },
  { message: "God's voice is kinder than the voice of shame. Learn to tell the difference.", verse: '"My sheep listen to my voice; I know them, and they follow me." — John 10:27' },
  { message: "You are not disqualified by your doubts. Thomas doubted — and Jesus showed up.", verse: '"Stop doubting and believe." — John 20:27' },
  { message: "God meets you at the bottom of your resources and says, now watch.", verse: '"With God all things are possible." — Matthew 19:26' },
  { message: "In the gap between who you are and who you want to be, grace lives.", verse: '"For it is by grace you have been saved, through faith." — Ephesians 2:8' },
  { message: "You are not forgotten in the waiting room of unanswered prayer.", verse: '"Wait for the Lord; be strong and take heart and wait for the Lord." — Psalm 27:14' },
  { message: "God does not grade on a curve. He erases the test and writes 'beloved' in its place.", verse: '"I will forgive their wickedness and will remember their sins no more." — Hebrews 8:12' },
  { message: "Even the parts of your story you're ashamed of are being redeemed.", verse: '"And we know that in all things God works for the good of those who love him." — Romans 8:28' },
  { message: "God's presence is not reserved for your best moments. He is with you in all of them.", verse: '"Where can I go from your Spirit? Where can I flee from your presence?" — Psalm 139:7' },
  { message: "You carry the Spirit of God within you. That changes everything.", verse: '"For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline." — 2 Timothy 1:7' },
  { message: "Your obedience today may be someone else's miracle tomorrow.", verse: '"Let your light shine before others, that they may see your good deeds." — Matthew 5:16' },
  { message: "Gratitude is the natural response to grace. Begin there today.", verse: '"Give thanks to the Lord, for he is good; his love endures forever." — Psalm 107:1' },
  { message: "God is at work in the seasons of stillness, not just the seasons of movement.", verse: '"Be still, and know that I am God." — Psalm 46:10' },
  { message: "You are not alone in the dark. The darkness is not dark to God.", verse: '"Even the darkness will not be dark to you; the night will shine like the day." — Psalm 139:12' },
  { message: "Whatever weight you are carrying today — lay it down. Grace is here.", verse: '"Cast all your anxiety on him because he cares for you." — 1 Peter 5:7' },
  { message: "God sees the big picture. Trust the brushstroke you're in right now.", verse: '"For my thoughts are not your thoughts, neither are your ways my ways." — Isaiah 55:8' },
  { message: "You are a new creation — not a patched-up version of the old one.", verse: '"Therefore, if anyone is in Christ, the new creation has come." — 2 Corinthians 5:17' },
  { message: "God's grace is not just for sinners. It sustains the saints, too.", verse: '"And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work." — 2 Corinthians 9:8' },
  { message: "You are held in the hands that shaped the stars. Rest there.", verse: '"The eternal God is your refuge, and underneath are the everlasting arms." — Deuteronomy 33:27' },
  { message: "Grace is not the ceiling of your life. It is the floor.", verse: '"From his fullness we have all received, grace upon grace." — John 1:16' },
  { message: "The God who holds the universe also holds your name in His heart.", verse: '"I have summoned you by name; you are mine." — Isaiah 43:1' },
  { message: "There is no expiration date on God's love for you.", verse: '"I have loved you with an everlasting love." — Jeremiah 31:3' },
  { message: "You are not walking toward grace. You are walking within it.", verse: '"In him we live and move and have our being." — Acts 17:28' },
  { message: "God doesn't just forgive — He forgets. Completely. Permanently.", verse: '"For I will forgive their wickedness and will remember their sins no more." — Hebrews 8:12' },
  { message: "Let the voice of truth be louder than the voice of fear today.", verse: '"For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline." — 2 Timothy 1:7' },
  { message: "Grace is the gift you didn't earn and can't lose. Receive it today.", verse: '"For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God." — Ephesians 2:8' },
  { message: "Your next chapter is not determined by your last one. God writes new beginnings.", verse: '"Behold, I am making all things new." — Revelation 21:5' },
  { message: "God's compassion for you is not earned. It is inherited. You are His child.", verse: '"As a father has compassion on his children, so the Lord has compassion on those who fear him." — Psalm 103:13' },
  { message: "You are not wandering in this. God is leading you — even when the path is unclear.", verse: '"He guides me along the right paths for his name's sake." — Psalm 23:3' },
  { message: "Your worth isn't measured by productivity. You have value just by existing.", verse: '"For in him we live and move and have our being." — Acts 17:28' },
  { message: "God's grace is not a safety net. It is solid ground.", verse: '"He set my feet on a rock and gave me a firm place to stand." — Psalm 40:2' },
  { message: "Even in the mundane, God is present. Nothing is too small for His attention.", verse: '"Are not two sparrows sold for a penny? Yet not one of them will fall to the ground outside your Father's care." — Matthew 10:29' },
  { message: "You don't have to earn your place at the table. You were invited before you were born.", verse: '"For he chose us in him before the creation of the world." — Ephesians 1:4' },
  { message: "Healing is not always instant. But it is always promised.", verse: '"He heals the brokenhearted and binds up their wounds." — Psalm 147:3' },
  { message: "God's mercies cover yesterday's mistakes and tomorrow's fears.", verse: '"His compassions never fail. They are new every morning." — Lamentations 3:22-23' },
  { message: "You are seen in your exhaustion. God offers rest, not judgment.", verse: '"Come to me, all you who are weary and burdened, and I will give you rest." — Matthew 11:28' },
  { message: "The God who parted seas can handle what you're facing today.", verse: '"Is anything too hard for the Lord?" — Genesis 18:14' },
  { message: "You are a vessel of honor. God's Spirit dwells in you.", verse: '"Do you not know that your bodies are temples of the Holy Spirit, who is in you?" — 1 Corinthians 6:19' },
  { message: "Grace is not just a theological concept. It is a daily experience waiting for you.", verse: '"Let us then approach God\u2019s throne of grace with confidence." — Hebrews 4:16' },
  { message: "You don't have to manufacture strength today. God's strength is available to you right now.", verse: '"He gives strength to the weary and increases the power of the weak." — Isaiah 40:29' },
  { message: "Every moment you choose to trust is a victory — even if it doesn't feel like one.", verse: '"This is the victory that has overcome the world, even our faith." — 1 John 5:4' },
  { message: "God's love story with humanity didn't end at the cross. It began there.", verse: '"For the joy set before him he endured the cross." — Hebrews 12:2' },
  { message: "You are not in competition with anyone. Your race is yours alone.", verse: '"Let us run with perseverance the race marked out for us." — Hebrews 12:1' },
  { message: "Even your longing for God is a gift. He placed it there.", verse: '"As the deer pants for streams of water, so my soul pants for you, my God." — Psalm 42:1' },
  { message: "You are not running out of chances. God is the God of the second, third, and hundredth chance.", verse: '"Return to me, for I have redeemed you." — Isaiah 44:22' },
  { message: "The grace that found you when you were lost still holds you now.", verse: '"For the Son of Man came to seek and to save the lost." — Luke 19:10' },
  { message: "You don't have to be put together. Authentic beats polished in the kingdom of God.", verse: '"God opposes the proud but shows favor to the humble." — James 4:6' },
  { message: "Your pain is real. And so is God's ability to redeem it.", verse: '"He comforts us in all our troubles, so that we can comfort those in any trouble." — 2 Corinthians 1:4' },
  { message: "You are not walking backward when you rest. You are being renewed.", verse: '"Even youths grow tired and weary... but those who hope in the Lord will renew their strength." — Isaiah 40:30-31' },
  { message: "God's goodness will follow you all the days of your life. Not just the good ones.", verse: '"Surely your goodness and love will follow me all the days of my life." — Psalm 23:6' },
  { message: "You are not a project for God to fix. You are a person He loves to be with.", verse: '"The Lord your God is with you... he will take great delight in you." — Zephaniah 3:17' },
  { message: "Grace whispers: you are forgiven, free, and fully loved. Believe it.", verse: '"It is for freedom that Christ has set us free." — Galatians 5:1' },
  { message: "Your tears water seeds of testimony you can't yet see.", verse: '"Those who sow with tears will reap with songs of joy." — Psalm 126:5' },
  { message: "God is not afraid of your anger or your grief. Bring it all.", verse: '"The Lord is close to the brokenhearted." — Psalm 34:18' },
  { message: "You are being shaped, not shamed.", verse: '"Yet you, Lord, are our Father. We are the clay, you are the potter." — Isaiah 64:8' },
  { message: "Grace turns mourning into dancing. Not right away — but always, eventually.", verse: '"You turned my wailing into dancing." — Psalm 30:11' },
  { message: "God hears you. Right now, in this moment, He hears every word.", verse: '"I love the Lord, for he heard my voice; he heard my cry for mercy." — Psalm 116:1' },
  { message: "You were not designed for condemnation. You were designed for freedom.", verse: '"It is for freedom that Christ has set us free." — Galatians 5:1' },
  { message: "Even your smallest act of faith moves mountains in the unseen.", verse: '"Truly I tell you, if you have faith as small as a mustard seed... Nothing will be impossible for you." — Matthew 17:20' },
  { message: "God doesn't love you in theory. He loves you in person, in detail, in full.", verse: '"But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." — Romans 5:8' },
  { message: "You are not an afterthought. You are a masterpiece in progress.", verse: '"For we are God's handiwork, created in Christ Jesus to do good works." — Ephesians 2:10' },
  { message: "In every moment of uncertainty, God remains certain about you.", verse: '"The Lord will fulfill his purpose for me; your steadfast love, O Lord, endures forever." — Psalm 138:8' },
  { message: "You are not behind. You are exactly where grace has you.", verse: '"He who began a good work in you will carry it on to completion." — Philippians 1:6' },
  { message: "God's mercies don't just cover sin. They cover sorrow, confusion, and weariness too.", verse: '"He heals the brokenhearted and binds up their wounds." — Psalm 147:3' },
  { message: "You were made to be loved, not endured. God loves you — fully, freely, forever.", verse: '"I have loved you with an everlasting love." — Jeremiah 31:3' },
];