export const BREAKTHROUGH_LEADERS_PLAN = {
  id: 'breakthrough-leaders',
  title: 'Breakthrough Leaders',
  subtitle: '8 Weeks to Transformational Leadership',
  description: 'Develop leadership that creates lasting transformation in yourself and others.',
  weeks: 8,
  comingSoon: true,
  days_total: 56,
  difficulty: 'Intermediate',
  gradient: 'from-[#FF6348] to-[#FFD700]',
  accent: '#FFD700',
  cover_emoji: '👑',
  tags: ['Leadership', 'Growth', 'Impact'],
  category: 'personal',
  week_themes: [],
  days: Array.from({ length: 56 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Breakthrough Leadership',
    bible: { book: 'Timothy', chapter: 2, verse_range: '2', key_verse: 'Faithful leaders develop others' },
    workout: { premade_id: 'strength-circuit', motivational_tip: 'Lead by example', coach_note: 'Strong leaders inspire' },
    nutrition: { focus: 'Vitality', meal_theme: 'Leadership', plan: 'Fuel your leadership', tip: 'Sustain your energy', recipe_search: 'power meals' },
    journal: { prompt: 'What kind of leader are you becoming?', entry_type: 'general' },
    affirmation: 'I am a breakthrough leader',
    personal_growth_page: 'Community',
    personal_growth_label: 'Leadership',
  })),
};