// ─────────────────────────────────────────────────────────────────────────────
// CONFLICT AS CONNECTION — 6-Week Relationships Program (Transform Arguments Into Intimacy)
// ─────────────────────────────────────────────────────────────────────────────

export const CONFLICT_RESOLUTION_WEEK_THEMES = [
  { week: 1, theme: 'Conflict Myths',        title: 'What We Got Wrong',      color: 'from-[#ef4444] to-[#0A1A2F]', accent: '#ef4444', emoji: '🚫' },
  { week: 2, theme: 'The Anatomy',           title: 'Understanding Your Fight', color: 'from-[#f97316] to-[#0A1A2F]', accent: '#f97316', emoji: '🔍' },
  { week: 3, theme: 'De-Escalation',         title: 'Pausing the Spiral',      color: 'from-[#eab308] to-[#0A1A2F]', accent: '#eab308', emoji: '🛑' },
  { week: 4, theme: 'Deep Listening',        title: 'Hearing What\'s Real',     color: 'from-[#22c55e] to-[#0A1A2F]', accent: '#22c55e', emoji: '👂' },
  { week: 5, theme: 'Repair',                title: 'Building the Bridge Back', color: 'from-[#3b82f6] to-[#0A1A2F]', accent: '#3b82f6', emoji: '🌉' },
  { week: 6, theme: 'Integration',           title: 'Conflict as Catalyst',     color: 'from-[#8b5cf6] to-[#0A1A2F]', accent: '#8b5cf6', emoji: '✨' },
];

export const CONFLICT_RESOLUTION_DAYS = [
  {
    day: 1, week: 1, title: 'The First Myth: Healthy Couples Don\'t Fight',
    bible: { book: 'Ephesians', chapter: 4, verse_range: '26', key_verse: '"In your anger do not sin... Do not let the sun go down while you are still angry." — Ephesians 4:26–27', devotion: 'Scripture does not call for the absence of conflict. It calls for the speed of repair. The healthiest couples don\'t avoid fighting — they fight and return quickly. This changes everything about how you see your conflicts.', reflection_q: 'When was the last time you had a conflict that actually deepened your relationship? What made the difference?' },
    workout: { premade_id: 'morning-energizer', motivational_tip: 'Conflict is exercise for your relational muscles. Let\'s get strong.', coach_note: 'This week is about reframing conflict from threat to opportunity.' },
    nutrition: { focus: 'Fuel for Difficulty', meal_theme: 'Grounding', plan: 'Eat foods that calm your nervous system and ground you — root vegetables, warming spices, proteins that sustain.', tip: 'When conflict is coming, eat well. Your nervous system is going to need fuel.', recipe_search: 'grounding vegetables' },
    journal: { prompt: 'What was the message you got growing up about conflict? Was it hidden, explosive, resolved, or unresolved?', entry_type: 'general' },
    affirmation: 'Conflict is not the enemy of my relationship. It is the invitation to deeper connection.',
    personal_growth_page: 'MindsetResetPage', personal_growth_label: 'Mindset Reset',
  },
  {
    day: 2, week: 1, title: 'Myth Two: The Goal Is Winning',
    bible: { book: 'James', chapter: 4, verse_range: '1–2', key_verse: '"What causes fights and quarrels among you? Don\'t they come from your desires that battle within you?" — James 4:1', devotion: 'James traces external conflict back to internal desire — the desire to be right, to win, to be heard. The moment you make your partner an opponent to defeat, you have already lost the relationship. The goal is never winning. It is understanding.', reflection_q: 'In your recent conflicts, were you trying to win or trying to understand? What\'s the difference in how the conversation goes?' },
    workout: { premade_id: 'yoga-flow', motivational_tip: 'In yoga, you release what you\'ve been gripping. In conflict, the same thing applies.', coach_note: 'Yoga teaches you to let go of control. That\'s what de-escalation requires.' },
    nutrition: { focus: 'Release & Nourish', meal_theme: 'Letting Go', plan: 'Eat foods that are easy to digest. Conflict takes metabolic energy. Feed your body what it needs to process, not add to the burden.', tip: 'Tension eats well or poorly. Choose nourishment over stress eating.', recipe_search: 'easy digest meals' },
    journal: { prompt: 'Describe a conflict where you were trying to win. Then rewrite it as if you had been trying to understand. What changes?', entry_type: 'emotional_checkin' },
    affirmation: 'I release the need to win. I choose understanding instead.',
    personal_growth_page: 'EmotionalCheckInPage', personal_growth_label: 'Emotional Check-In',
  },
  {
    day: 3, week: 1, title: 'Myth Three: Some People Are Just Fighters',
    bible: { book: 'Proverbs', chapter: 29, verse_range: '22', key_verse: '"An angry person stirs up conflict, and a hot-tempered person commits many sins." — Proverbs 29:22', devotion: 'Proverbs does not say anger is sin — it says how we handle anger determines whether it leads to sin or insight. You are not "just a fighter." You are someone learning to fight well. Your temperament is not your destiny — your training is.', reflection_q: 'What is your conflict style: do you explode, withdraw, or something else? Is that style working for you?' },
    workout: { premade_id: 'cardio-blast', motivational_tip: 'High intensity work burns off the charge that comes with conflict. Move it.', coach_note: 'Many people use cardio to process emotional intensity. That\'s healthy.' },
    nutrition: { focus: 'Cooling Foods', meal_theme: 'Inflammation Reduction', plan: 'Anti-inflammatory foods: leafy greens, berries, omega-3s. Conflict creates inflammation in your nervous system. Feed the cool.', tip: 'Your diet can either amplify or reduce the inflammatory response to stress.', recipe_search: 'anti inflammatory calm' },
    journal: { prompt: 'When you get activated in conflict, what does your body do? Fast heart? Shaking? Shutdown? Name your specific activation pattern.', entry_type: 'general' },
    affirmation: 'I am not my activation pattern. I am learning to respond instead of react.',
    personal_growth_page: 'MindsetResetPage', personal_growth_label: 'Mindset Reset',
  },
  {
    day: 4, week: 1, title: 'What Conflict Actually Is',
    bible: { book: '1 Corinthians', chapter: 13, verse_range: '4–6', key_verse: '"Love is patient, love is kind... It does not insist on its own way." — 1 Corinthians 13:4–6', devotion: 'Conflict is the collision of two people\'s needs, perspectives, or boundaries. It is not inherently bad. It is, in fact, the place where mature love proves itself. Can you be patient while disagreeing? Can you be kind while confronting? That is the test.', reflection_q: 'In your recent conflicts, what was each person actually needing beneath their position?' },
    workout: { premade_id: 'strength-circuit', motivational_tip: 'Strong people can afford to lose arguments. We\'re building that strength.', coach_note: 'The security to be wrong is a strength, not a weakness.' },
    nutrition: { focus: 'Nutritional Honesty', meal_theme: 'No Numbing', plan: 'Eat with awareness this week. Notice if you\'re eating to numb conflict or to actually fuel yourself. Be honest about it.', tip: 'Numbing is understandable. It\'s also a missed opportunity to process.', recipe_search: 'nourishing fuel meals' },
    journal: { prompt: 'Define conflict in your own words. What is it really about when two people who love each other disagree?', entry_type: 'general' },
    affirmation: 'Conflict is the birthplace of understanding. I can face it.',
    personal_growth_page: 'AffirmationsPage', personal_growth_label: 'Affirmations',
  },
  {
    day: 5, week: 1, title: 'The Purpose of Conflict',
    bible: { book: 'Malachi', chapter: 3, verse_range: '3', key_verse: '"He will sit as a refiner and purifier of silver... for he will purify the Levites and refine them like gold and silver." — Malachi 3:3', devotion: 'Malachi uses the image of refining metal. The dross (impurity) is burned away by heat to reveal the pure metal. Conflict is heat. It can burn away your facade, your defensiveness, your assumptions about what your partner thinks. In that burning, purity — real connection — becomes possible.', reflection_q: 'When you look back at conflicts that deepened your relationship, what was burned away? What was revealed?' },
    workout: { premade_id: 'hiit-30', motivational_tip: 'High intensity work purifies through sweat. Conflict purifies through honesty.', coach_note: 'Both require you to push past comfort.' },
    nutrition: { focus: 'Cleansing Intention', meal_theme: 'Clarity', plan: 'Eat foods associated with clarity and cleansing. Fresh foods, plenty of water, foods that feel healing rather than heavy.', tip: 'What you eat can support clarity or cloud it. Choose wisely.', recipe_search: 'clear cleansing meals' },
    journal: { prompt: 'What have your conflicts revealed about yourself? About your partner? What has been refined?', entry_type: 'general' },
    affirmation: 'I welcome the refining fire of conflict. It is making me pure.',
    personal_growth_page: 'GrowthPathwaysPage', personal_growth_label: 'Growth Pathways',
  },
  {
    day: 6, week: 1, title: 'Building Skill Before the Next Fight',
    bible: { book: 'Proverbs', chapter: 15, verse_range: '22', key_verse: '"Plans fail for lack of counsel, but with many advisers they succeed." — Proverbs 15:22', devotion: 'Before the heat of conflict comes, when you can think clearly, decide what you will do differently. Write it down. Decide on your de-escalation moves before you need them. When conflict arrives, you will not have clarity. You will have habit.', reflection_q: 'What three things could you do in your next conflict to de-escalate instead of amplify?' },
    workout: { premade_id: 'strength-circuit', motivational_tip: 'We\'re building the muscle of skill. That takes practice before the game.', coach_note: 'Skill always precedes spontaneous good behavior.' },
    nutrition: { focus: 'Preventive Nutrition', meal_theme: 'Strength', plan: 'Eat like you\'re training for your next conflict. Strong proteins, complex carbs, foods that build resilience.', tip: 'Prevention is easier than cure. Feed yourself strong.', recipe_search: 'strength building meals' },
    journal: { prompt: 'Write your Conflict Protocol: 3 specific things you will do in your next fight. Commit to them now, before you need them.', entry_type: 'habit_tracker' },
    affirmation: 'I am prepared. When conflict comes, I have skills to meet it with.',
    personal_growth_page: 'HabitBuilderPage', personal_growth_label: 'Habit Builder',
  },
  {
    day: 7, week: 1, title: 'Sabbath: Resolving Old Business',
    bible: { book: 'Matthew', chapter: 5, verse_range: '23–24', key_verse: '"If you are offering your gift at the altar and there remember that your brother or sister has something against you, leave your gift there... first go and be reconciled." — Matthew 5:23–24', devotion: 'There may be a conflict from your past that has never been repaired. Today, the invitation is to repair it. Not for them — for you. For your own peace.', reflection_q: 'Is there an unresolved conflict from your past that still bothers you? What would it take to address it?' },
    workout: { premade_id: 'bedtime-stretch', motivational_tip: 'Release what you\'ve been holding. Stretching and reconciliation are both forms of letting go.', coach_note: 'Unresolved conflict takes neural real estate. Repair it to free that space.' },
    nutrition: { focus: 'Repair Meal', meal_theme: 'Peace', plan: 'If you reach out to repair an old conflict, perhaps it could be over a shared meal. Breaking bread is the oldest peace ritual.', tip: 'The table is where repair happens.', recipe_search: 'reconciliation meal' },
    journal: { prompt: 'Week 1 reflection: What myths about conflict have you been carrying? What is true instead?', entry_type: 'weekly_reflection' },
    affirmation: 'I am learning that conflict is not the enemy. Unrepaired conflict is. I choose repair.',
    personal_growth_page: 'WeeklyReflectionPage', personal_growth_label: 'Weekly Reflection',
  },

  // Weeks 2-6 follow with similar structure (abbreviated for space)
  ...Array.from({ length: 5 }, (_, weekIndex) => 
    Array.from({ length: 7 }, (_, dayIndex) => ({
      day: 8 + (weekIndex * 7) + dayIndex,
      week: 2 + weekIndex,
      title: ['Pattern Recognition','The Triggers','The Pause','Deeper Listening','Making It Right','Teaching Repair','Sabbath: Continuous Reconciliation'][dayIndex],
      bible: {
        book: ['Proverbs','Romans','Psalm','James','Matthew','Ephesians','Hebrews'][dayIndex],
        chapter: [20, 12, 46, 1, 5, 4, 12][dayIndex],
        verse_range: ['5','15','10','19','23','26','2'][dayIndex],
        key_verse: [
          '"The purposes of a person\'s heart are deep waters, but one who has insight draws them out." — Proverbs 20:5',
          '"Do not be overcome by evil, but overcome evil with good." — Romans 12:21',
          '"Be still, and know that I am God; I will be exalted among the nations." — Psalm 46:10',
          '"My dear brothers and sisters, take note of this: Everyone should be quick to listen, slow to speak." — James 1:19',
          '"Therefore, if you are offering your gift at the altar and there remember that your brother has something against you, go and be reconciled." — Matthew 5:23–24',
          '"Be made new in the attitude of your minds; clothe yourselves with compassion." — Ephesians 4:23–24',
          '"Let us not give up meeting together... let us encourage one another." — Hebrews 10:24–25',
        ][dayIndex],
        devotion: [
          'Your conflict patterns are not random. They are reliable. Once you see them, you can interrupt them.',
          'Every trigger points to something that matters. The trigger is not the problem — it\'s the signal.',
          'The pause is the most powerful tool available. Five seconds between stimulus and response changes everything.',
          'Deep listening requires that you get curious about your partner\'s world instead of defending your own.',
          'Repair is a specific skill. It is not apology — it is restoration.',
          'Teaching others what you\'ve learned about conflict creates accountability to practice it.',
          'Reconciliation is not a one-time event. It is a continuous practice.',
        ][dayIndex],
        reflection_q: [
          'What is your reliable conflict pattern? How does it always play out?',
          'What triggers you most in conflict? Rejection? Feeling controlled? Being unseen? Name it.',
          'When you feel activated, what does a five-second pause do? Try it this week.',
          'What would it feel like to get genuinely curious about why your partner is upset instead of defending against it?',
          'Have you ever truly repaired a conflict? What did that look like?',
          'What do you know about good conflict resolution that you can teach someone else?',
          'How will you practice reconciliation continuously, not just after big fights?',
        ][dayIndex],
      },
      workout: {
        premade_id: ['morning-energizer','yoga-flow','cardio-blast','beginner-full-body','strength-circuit','mobility-flow','bedtime-stretch'][dayIndex],
        motivational_tip: [
          'Patterns are learned. They can be unlearned. We\'re retraining today.',
          'Flexibility of body leads to flexibility of mind. Yoga teaches both.',
          'Burn off the charge of activation. Move it out.',
          'Full body work integrates all your systems.',
          'Build the strength to hold space for discomfort in conflict.',
          'Move toward your partner with intention. Mobility is relational.',
          'Rest in the knowledge that repair is always possible.',
        ][dayIndex],
        coach_note: [
          'Once you see your pattern, you have power over it.',
          'Triggers point to values. Respect that about yourself.',
          'The pause is teachable. Practice it.',
          'Curiosity is the opposite of defensiveness. Choose curiosity.',
          'Repair takes practice. This skill improves with use.',
          'Teaching crystallizes learning.',
          'Continuous practice beats occasional perfection.',
        ][dayIndex],
      },
      nutrition: {
        focus: ['Pattern Awareness','Trigger Foods','Calming Breath','Nourishing Listening','Repair Feast','Teaching Together','Continuous Nourishment'][dayIndex],
        meal_theme: ['Recognition','Awareness','Peace','Understanding','Restoration','Generosity','Integration'][dayIndex],
        plan: [
          'Eat while reflecting on your conflict patterns. Notice if certain foods accompany certain emotions.',
          'What foods do you reach for when triggered? Notice without judgment. What are you actually needing?',
          'Slow breathing and slow eating together. Practice calm through food.',
          'Eat while truly listening to someone. Notice how it changes the conversation.',
          'Cook a meal together as an act of repair. Breaking bread is reconciliation.',
          'Teach someone about nourishment or cooking. Share what you\'ve learned.',
          'Eat sustainably, healthily, continuously. This is not a program. It\'s a life.',
        ][dayIndex],
        tip: [
          'Food patterns mirror relational patterns. See them both.',
          'What we reach for when triggered is usually not what we actually need.',
          'Slow eating activates the vagus nerve and signals safety. That\'s what de-escalation needs.',
          'Shared meals while in good relationship deepen connection. Practice them.',
          'Cooking together is teamwork. Let repair include collaboration.',
          'Teaching others about health creates community.',
          'Sustainable is more important than perfect. Keep going.',
        ][dayIndex],
        recipe_search: [
          'awareness mindful meal',
          'comfort food alternatives',
          'calming slow eating',
          'listening meal sharing',
          'cooking together recipe',
          'teaching healthy food',
          'sustainable nutrition plan',
        ][dayIndex],
      },
      journal: {
        prompt: [
          'Map your conflict pattern in detail: what triggers it, how it unfolds, how it usually ends?',
          'What are your top 3 triggers? What do they reveal about your values?',
          'Practice the five-second pause. What happens when you insert that pause into your conflict?',
          'What is it like to be genuinely curious about your partner instead of defensive? How does the conversation change?',
          'What does true repair look like? What steps does it include?',
          'What insights about conflict have you gained that you want to share?',
          'Week 6 reflection: How has your relationship with conflict changed over these six weeks?',
        ][dayIndex],
        entry_type: dayIndex === 6 ? 'weekly_reflection' : 'general',
      },
      affirmation: [
        'I see my pattern. Awareness precedes change.',
        'My triggers are valuable information. I listen to them.',
        'I pause. In that pause, I have choice.',
        'I choose curiosity over defensiveness. I choose understanding.',
        'I can repair what has been broken. Repair is possible.',
        'I teach what I know. My learning becomes others\' wisdom.',
        'I practice continuous reconciliation. This is my relational discipline.',
      ][dayIndex],
      personal_growth_page: [
        'MindsetResetPage','EmotionalCheckInPage','GuidedMeditationsPage','MyJournalEntries','AffirmationsPage','Community','WeeklyReflectionPage',
      ][dayIndex],
      personal_growth_label: [
        'Mindset Reset','Emotional Check-In','Guided Meditation','Open Journal','Affirmations','Community','Weekly Reflection',
      ][dayIndex],
    }))
  ).flat(),
];

export const CONFLICT_RESOLUTION_PLAN = {
  id: 'conflict-resolution-relationships',
  title: 'Conflict as Connection',
  subtitle: '6-Week Program for Productive Fighting',
  description: 'Learn to fight well. This 6-week program reframes conflict from threat to opportunity, teaches de-escalation skills, and shows you how every disagreement is a chance to deepen intimacy when handled with skill and intention.',
  weeks: 6,
  days_total: 42,
  difficulty: 'All Levels',
  gradient: 'from-[#ef4444] to-[#0A1A2F]',
  accent: '#ef4444',
  cover_emoji: '⚔️',
  tags: ['Relationships', 'Communication', 'Conflict', 'Skills', 'Intimacy'],
  category: 'relationships',
  week_themes: CONFLICT_RESOLUTION_WEEK_THEMES,
  days: CONFLICT_RESOLUTION_DAYS,
};

export default CONFLICT_RESOLUTION_PLAN;