// ─────────────────────────────────────────────────────────────────────────────
// FREEDOM & RECOVERY — 4-Week Coaching Plan
// "Breaking Chains: A Faith-Based Journey to Freedom from Addiction"
// ─────────────────────────────────────────────────────────────────────────────

export const FREEDOM_RECOVERY_PLAN = {
  id: 'freedom-recovery',
  title: 'Freedom & Recovery',
  subtitle: '4 Weeks to Break the Chains of Addiction',
  description: 'A 28-day faith-based journey toward freedom from alcohol, drugs, and substance dependency. This plan is NOT a substitute for professional treatment — it is a spiritual companion for your recovery. Rooted in Scripture, honest reflection, physical movement, and daily surrender, this plan walks with you through honesty, identity, new habits, and community.',
  weeks: 4,
  days_total: 28,
  difficulty: 'All Levels',
  gradient: 'from-[#7C3AED] to-[#A78BFA]',
  accent: '#7C3AED',
  emoji: '⛓️‍💥',
  category: 'spiritual',
  coach: 'Hannah',
  tags: ['addiction', 'recovery', 'freedom', 'sobriety', 'healing', 'chains', 'surrender'],
  disclaimer: 'IMPORTANT: This coaching plan is for spiritual encouragement and personal growth only. It is NOT a substitute for professional addiction treatment, medical detox, clinical counseling, or medication-assisted treatment. Alcohol and drug withdrawal can be medically dangerous — always consult a physician before stopping any substance. If you are in crisis, call SAMHSA at 1-800-662-4357 or 988 Suicide & Crisis Lifeline.',
  crisis_resources: [
    { name: 'SAMHSA National Helpline', number: '1-800-662-4357', note: 'Free, confidential, 24/7, 365 days a year' },
    { name: '988 Suicide & Crisis Lifeline', number: '988', note: 'Call or text 24/7' },
    { name: 'Crisis Text Line', number: 'Text HOME to 741741', note: '24/7 crisis support' },
  ],
  week_themes: [
    { week: 1, theme: 'Honesty',    title: 'Breaking the Silence',          color: 'from-[#7C3AED] to-[#A78BFA]', accent: '#7C3AED', emoji: '🪞' },
    { week: 2, theme: 'Identity',   title: 'You Are Not Your Addiction',     color: 'from-[#0A1A2F] to-[#38BDF8]', accent: '#38BDF8', emoji: '👑' },
    { week: 3, theme: 'Rebuilding', title: 'New Patterns, New Life',         color: 'from-[#065F46] to-[#10B981]', accent: '#10B981', emoji: '🌱' },
    { week: 4, theme: 'Community',  title: 'You Were Never Meant to Walk Alone', color: 'from-[#0A1A2F] to-[#c9a227]', accent: '#c9a227', emoji: '🤝' },
  ],
  days: [
    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 1 — HONESTY: "Breaking the Silence"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 1, week: 1,
      title: 'The First Step Is the Hardest',
      bible: { book: 'James', chapter: 5, verse_range: '16',
        key_verse: '"Therefore, confess your sins to one another, and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective." — James 5:16 (WEB)',
        devotion: 'Recovery starts with one terrifying word: honesty. Not partial honesty — the kind where you admit you "maybe drink a little too much." Full honesty. The kind that says, "I have lost control and I need help." James does not say confession heals because it feels good. It heals because it breaks the power of secrecy. Addiction thrives in darkness. Every chain of bondage has a lock — and that lock is the secret you are keeping. Today, you do not have to fix everything. You just have to stop pretending nothing is wrong.',
        reflection_q: 'What have you been hiding from yourself, from God, or from someone who loves you? What would happen if you spoke it out loud today?',
      },
      journal: { prompt: 'Write the truth you have been afraid to say. Not for anyone else — for you. What substance has power over you? How long has this been going on? What has it cost you? Be as honest as you can bear to be.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'morning-energizer', motivational_tip: 'Recovery begins with small acts of self-care. Moving your body is one of the first ways to tell your brain: I am choosing a different path today.', coach_note: 'Gentle is the goal. Showing up matters more than intensity.' },
      nutrition: { focus: 'Hydration', meal_theme: 'Flush and restore', plan: 'Drink at least 8 glasses of water today. Substance use depletes your body of water, electrolytes, and nutrients. Rehydration is the simplest first step of physical recovery.', tip: 'Add lemon and a pinch of salt to your water for better absorption.', recipe_search: 'hydrating recovery foods' },
      affirmation: 'I am done pretending. Today I choose honesty, and honesty is the beginning of freedom.',
    },
    {
      day: 2, week: 1,
      title: 'God Already Knows',
      bible: { book: 'Psalms', chapter: 139, verse_range: '1–4',
        key_verse: '"You, Yahweh, have searched me, and you know me. You know my sitting down and my rising up. You understand my thoughts from afar." — Psalm 139:1–2 (WEB)',
        devotion: 'Here is the most liberating truth for anyone in addiction: God already knows. He knows how many times you have used. He knows about the hidden bottles, the secret purchases, the lies you told to cover it up. He knows the shame you carry. And He is not repulsed by you. He is not surprised. He is not waiting for you to clean up before He shows up. He has been searching for you this entire time — not to punish you, but to rescue you.',
        reflection_q: 'How does it feel to know that God already knows everything and still pursues you? Does that bring relief or fear?',
      },
      journal: { prompt: 'Write a letter to God as if He already knows everything (because He does). Tell Him what you have been carrying. You do not have to explain or justify. Just tell Him.', entry_type: 'spiritual' },
      workout: { premade_id: 'yoga-flow', motivational_tip: 'Yoga teaches you to sit with discomfort without running from it. That is the recovery skill of the century.', coach_note: 'Slow, intentional movement. Breathe through the discomfort.' },
      nutrition: { focus: 'B-Vitamins', meal_theme: 'Nervous system repair', plan: 'Alcohol and many drugs severely deplete B vitamins, which are critical for your nervous system. Eat eggs, leafy greens, whole grains, and legumes today.', tip: 'Consider a B-complex supplement — ask your doctor first.', recipe_search: 'B vitamin rich meal recovery' },
      affirmation: 'God already knows my story, and He still calls me His own. I do not have to hide anymore.',
    },
    {
      day: 3, week: 1,
      title: 'The Cost of Hiding',
      bible: { book: 'Proverbs', chapter: 28, verse_range: '13',
        key_verse: '"He who conceals his sins doesn\'t prosper, but whoever confesses and renounces them finds mercy." — Proverbs 28:13 (WEB)',
        devotion: 'Addiction is expensive — but not just financially. It costs you relationships. It costs you health. It costs you years. And the hiding costs even more than the substance itself. The energy it takes to maintain a double life — to perform normalcy while drowning — is exhausting. But the Proverb promises something specific: mercy comes to those who confess AND renounce. Confession without action is just venting. Action without confession is just willpower. Recovery requires both.',
        reflection_q: 'What has this addiction cost you that money cannot buy back? Relationships? Trust? Years? Health? Name it specifically.',
      },
      journal: { prompt: 'Make a cost inventory. List everything this addiction has taken from you: relationships, money, health, opportunities, self-respect, time with your children, trust from people who love you. Be specific. This is not to punish yourself — it is to see clearly.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'beginner-full-body', motivational_tip: 'Rebuilding physical strength is a metaphor for what you are doing spiritually. One rep at a time.', coach_note: 'Full body engagement. You are reclaiming your body.' },
      nutrition: { focus: 'Protein and stabilization', meal_theme: 'Blood sugar balance', plan: 'Cravings are often linked to unstable blood sugar. Eat regular meals with protein, healthy fats, and complex carbs. No skipping meals — your body needs consistency right now.', tip: 'Eat something with protein within 1 hour of waking.', recipe_search: 'blood sugar stabilizing meals' },
      affirmation: 'I choose to count the cost honestly — not to condemn myself, but to fuel my commitment to freedom.',
    },
    {
      day: 4, week: 1,
      title: 'Powerlessness Is Not Weakness',
      bible: { book: '2 Corinthians', chapter: 12, verse_range: '9–10',
        key_verse: '"My grace is sufficient for you, for my power is made perfect in weakness." — 2 Corinthians 12:9 (WEB)',
        devotion: 'Every recovery framework begins with the same admission: I am powerless over this substance. For the self-reliant, this feels like defeat. But Paul teaches us something counterintuitive — when you finally admit you cannot do this alone, you create space for a power far greater than willpower. God\'s strength does not supplement your strength. It replaces it. The moment you stop trying to manage your addiction through sheer effort, and instead surrender it to God, everything changes.',
        reflection_q: 'Where have you been relying on willpower instead of God\'s power? What would true surrender look like for you today?',
      },
      journal: { prompt: 'Write this sentence and then continue: "I am powerless over _____, and I need God\'s help because..." Let yourself write freely.', entry_type: 'spiritual' },
      workout: { premade_id: 'morning-energizer', motivational_tip: 'Physical movement releases endorphins — your body\'s natural feel-good chemicals. This is healthy chemistry replacing harmful chemistry.', coach_note: 'Your body is learning that it can feel good without substances.' },
      nutrition: { focus: 'Omega-3 fatty acids', meal_theme: 'Brain repair', plan: 'Substance use damages brain tissue and neurotransmitter systems. Omega-3s (salmon, walnuts, flaxseed, sardines) support brain healing and mood stabilization.', tip: 'Aim for fatty fish 2-3 times this week.', recipe_search: 'omega 3 brain health meal' },
      affirmation: 'My weakness is not my shame — it is the doorway through which God\'s power enters. I surrender today.',
    },
    {
      day: 5, week: 1,
      title: 'The Trigger Map',
      bible: { book: '1 Corinthians', chapter: 10, verse_range: '13',
        key_verse: '"No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape." — 1 Corinthians 10:13 (WEB)',
        devotion: 'Every relapse has a history. It did not start with the drink or the drug — it started with a trigger: stress, loneliness, celebration, boredom, a specific person, a specific place, a specific time of day. God promises a way of escape with every temptation — but you have to know where the temptation enters before you can find the exit. Today you are building your trigger map.',
        reflection_q: 'What are your top 3 triggers? Can you identify the emotional state, the environment, and the time of day when cravings are strongest?',
      },
      journal: { prompt: 'Create your personal trigger map. For each trigger, write: (1) What is the trigger? (2) What emotion am I feeling when it hits? (3) What is my current response? (4) What could be a new response? Be as detailed as possible — this is your escape plan.', entry_type: 'general' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'Strength training teaches you that discomfort is temporary and growth comes on the other side of it. Same with cravings.', coach_note: 'Channel the energy. Use the workout as a physical outlet for emotional pressure.' },
      nutrition: { focus: 'Gut health', meal_theme: 'Microbiome repair', plan: 'Substance use destroys gut bacteria, which directly affects mood and cravings. Eat fermented foods (yogurt, kimchi, sauerkraut) and fiber-rich vegetables today.', tip: 'A healthy gut produces 90% of your body\'s serotonin. Feed it well.', recipe_search: 'gut health probiotic meal' },
      affirmation: 'I know my triggers, and I am building my escape routes. God is faithful — He will make a way.',
    },
    {
      day: 6, week: 1,
      title: 'Grieving What Addiction Took',
      bible: { book: 'Psalms', chapter: 34, verse_range: '18',
        key_verse: '"Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit." — Psalm 34:18 (WEB)',
        devotion: 'Recovery is not just about stopping a behavior. It is about grieving what was lost while you were in bondage. The years. The relationships. The person you might have become. You need to mourn these losses — not to stay stuck in sadness, but to honor the weight of what happened and make space for what God will rebuild. He is near to the brokenhearted. Not near to the put-together. Near to the broken.',
        reflection_q: 'What do you need to grieve? What loss from your addiction have you never allowed yourself to fully feel?',
      },
      journal: { prompt: 'Write a grief letter. It can be to yourself, to someone you hurt, to the years you lost, or to the person you wish you had been. Let yourself feel this. Then write one sentence about what you believe God can still build from here.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'yoga-flow', motivational_tip: 'Grief lives in the body. Gentle movement and deep breathing help release stored emotion.', coach_note: 'This is an emotional day. Be gentle with yourself.' },
      nutrition: { focus: 'Magnesium', meal_theme: 'Calming and restorative', plan: 'Magnesium calms the nervous system and supports sleep — both critical in early recovery. Eat dark leafy greens, dark chocolate, pumpkin seeds, and bananas.', tip: 'Epsom salt bath tonight — magnesium absorbs through the skin.', recipe_search: 'magnesium rich calming meal' },
      affirmation: 'I give myself permission to grieve. God is close to me in my brokenness, and He will not waste my pain.',
    },
    {
      day: 7, week: 1,
      title: 'Sabbath Rest in Recovery',
      bible: { book: 'Matthew', chapter: 11, verse_range: '28–30',
        key_verse: '"Come to me, all you who labor and are heavily burdened, and I will give you rest." — Matthew 11:28 (WEB)',
        devotion: 'The first week of honesty is exhausting. You have looked at things you have been avoiding for months or years. You have named costs, identified triggers, grieved losses, and admitted powerlessness. Today, you rest. Not because the work is done, but because rest is part of the work. Jesus does not say "come to me when you are fixed." He says come as you are — tired, burdened, heavy — and He will give you rest.',
        reflection_q: 'What does rest look like for you that does NOT involve the substance you are recovering from? Can you find rest in God today?',
      },
      journal: { prompt: 'Reflect on Week 1. What was the hardest truth you confronted? What surprised you? What do you feel right now — physically, emotionally, spiritually? Write it all.', entry_type: 'weekly_reflection' },
      workout: { premade_id: 'desk-stretch', motivational_tip: 'Rest is not quitting. It is recovering. Your body and spirit need this.', coach_note: 'Gentle stretching only. This is your Sabbath.' },
      nutrition: { focus: 'Comfort without substances', meal_theme: 'Soul food done healthy', plan: 'Make a warm, comforting meal today that feels like home — but without alcohol or any trigger foods. Soup, roasted chicken, fresh bread. Feed your soul through your stomach.', tip: 'Cooking can be meditative. Be present in the process.', recipe_search: 'healthy comfort food soul meal' },
      affirmation: 'I come to Jesus tired and heavy, and He gives me rest. Week 1 is complete. I am still standing.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 2 — IDENTITY: "You Are Not Your Addiction"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 8, week: 2,
      title: 'You Are a New Creation',
      bible: { book: '2 Corinthians', chapter: 5, verse_range: '17',
        key_verse: '"Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new." — 2 Corinthians 5:17 (WEB)',
        devotion: 'Addiction rewrites your identity. It teaches you to say "I am an addict" as if that is your permanent name. But God says something different. He says you are a new creation. The old has passed away. You are not defined by what you consumed — you are defined by who created you and who redeemed you. Today begins the work of separating your identity from your addiction.',
        reflection_q: 'When you think about yourself, what label comes first — "addict," "failure," "broken"? What if God\'s label for you is "new creation"?',
      },
      journal: { prompt: 'Write two lists. List 1: "My addiction says I am..." (write every lie it tells you). List 2: "God says I am..." (use Scripture to answer every lie). Keep this page. Read it when the lies get loud.', entry_type: 'spiritual' },
      workout: { premade_id: 'hiit-30', motivational_tip: 'High intensity training proves to your brain that you are capable of hard things. Every completed set is evidence that you are more than your addiction.', coach_note: 'Push today. Prove to yourself what you are capable of.' },
      nutrition: { focus: 'Amino acids', meal_theme: 'Neurotransmitter rebuilding', plan: 'Your brain\'s reward system was hijacked by substances. Help rebuild it with amino acid-rich foods: turkey, eggs, nuts, seeds, and legumes. These are the building blocks of dopamine and serotonin — your natural feel-good chemicals.', tip: 'L-tyrosine (found in chicken, fish, and almonds) supports dopamine production naturally.', recipe_search: 'amino acid rich brain food meal' },
      affirmation: 'I am not my addiction. I am a new creation in Christ. The old has passed away — everything is becoming new.',
    },
    {
      day: 9, week: 2,
      title: 'Dead to Sin, Alive to God',
      bible: { book: 'Romans', chapter: 6, verse_range: '6–7',
        key_verse: '"Knowing this, that our old man was crucified with him, that the body of sin might be done away with, so that we would no longer be in bondage to sin. For he who has died has been freed from sin." — Romans 6:6–7 (WEB)',
        devotion: 'Paul uses the language of death and freedom. Your old self — the one who was enslaved — was crucified with Christ. That means the person who needed the substance to cope, to celebrate, to escape, to function — that person died. You are a resurrected version. You do not have to obey the old master anymore. The chains are broken. The cell door is open. You can walk out.',
        reflection_q: 'What part of your "old self" are you still carrying? What would it mean to truly let that version of you die?',
      },
      journal: { prompt: 'Write a eulogy for your addicted self. Not with cruelty — with compassion. Acknowledge what that person was going through, why they turned to substances, and then formally say goodbye. "You were trying to survive. But I am choosing to live."', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'Building physical strength is a tangible symbol of the inner transformation happening in you right now.', coach_note: 'Progressive overload — a little more than last time. Growth is the goal.' },
      nutrition: { focus: 'Liver support', meal_theme: 'Detox and repair', plan: 'Your liver has been working overtime. Support it with cruciferous vegetables (broccoli, cauliflower, Brussels sprouts), beets, garlic, and turmeric. These foods naturally support your body\'s detoxification pathways.', tip: 'A glass of warm water with turmeric and lemon first thing in the morning.', recipe_search: 'liver support detox meal healthy' },
      affirmation: 'My old self was crucified with Christ. I have been freed from sin\'s bondage. I am alive, and I am free.',
    },
    {
      day: 10, week: 2,
      title: 'The Armor of God Against Cravings',
      bible: { book: 'Ephesians', chapter: 6, verse_range: '10–13',
        key_verse: '"Put on the whole armor of God, that you may be able to stand against the wiles of the devil." — Ephesians 6:11 (WEB)',
        devotion: 'Cravings are not just biological — they are spiritual. The enemy knows your weak points and will exploit them. Paul\'s response is not "try harder" — it is "put on armor." The belt of truth (you are not lying to yourself anymore). The breastplate of righteousness (your identity is secured in Christ, not in your behavior). The shield of faith (trust God when the craving screams). The sword of the Spirit (speak Scripture out loud when the pressure builds).',
        reflection_q: 'Which piece of spiritual armor do you need most right now? Where do you feel most vulnerable?',
      },
      journal: { prompt: 'Write out your personalized "Armor Plan" — for each piece of armor, write how you will use it when cravings come. Example: "Belt of truth: I will call my accountability partner instead of hiding." Make it practical and specific.', entry_type: 'general' },
      workout: { premade_id: 'morning-energizer', motivational_tip: 'Morning workouts create a natural high that reduces the intensity of cravings throughout the day.', coach_note: 'Start the day strong. Set the tone before the world sets it for you.' },
      nutrition: { focus: 'Complex carbohydrates', meal_theme: 'Steady energy, no crashes', plan: 'Blood sugar crashes trigger cravings hard. Eat slow-burning carbs: sweet potatoes, oats, brown rice, quinoa. These keep your energy stable and your cravings quieter.', tip: 'Pair carbs with protein and fat for even slower digestion.', recipe_search: 'slow burning complex carb meal' },
      affirmation: 'I put on the full armor of God today. I am not defenseless against cravings — I am equipped for battle.',
    },
    {
      day: 11, week: 2,
      title: 'Shame Cannot Live Here',
      bible: { book: 'Romans', chapter: 8, verse_range: '1',
        key_verse: '"There is therefore now no condemnation to those who are in Christ Jesus." — Romans 8:1 (WEB)',
        devotion: 'Shame is addiction\'s best friend. It says "you failed again, so why bother trying?" Shame keeps you drinking, using, hiding, isolating. But Paul declares something absolute: NO condemnation. Not "less condemnation." Not "condemnation after three strikes." None. Zero. This is not permission to keep using — it is freedom from the lie that says your failures define your future.',
        reflection_q: 'What is the most shameful thing your addiction has caused you to do? Can you bring it into the light of Romans 8:1?',
      },
      journal: { prompt: 'Write down the shame you carry — the thing you have never told anyone. Then write Romans 8:1 underneath it. Then write: "This does not define me. This does not disqualify me. I am not condemned." Say it out loud.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'hiit-30', motivational_tip: 'Shame says you do not deserve to feel strong. Prove it wrong today.', coach_note: 'Channel the emotion. Every rep is a declaration that shame does not own you.' },
      nutrition: { focus: 'Vitamin D and sunlight', meal_theme: 'Mood support', plan: 'Depression and shame are worsened by Vitamin D deficiency — common in people who have been isolating. Get 15 minutes of sunlight today. Eat Vitamin D-rich foods: fatty fish, egg yolks, fortified foods.', tip: 'Walk outside in the morning sun. Double benefit: exercise + Vitamin D.', recipe_search: 'vitamin D mood boost meal' },
      affirmation: 'There is no condemnation for me. Shame has lost its power. I am free to grow, to heal, and to become.',
    },
    {
      day: 12, week: 2,
      title: 'Replacing the Counterfeit',
      bible: { book: 'John', chapter: 10, verse_range: '10',
        key_verse: '"The thief only comes to steal, kill, and destroy. I came that they may have life, and may have it abundantly." — John 10:10 (WEB)',
        devotion: 'Addiction is a counterfeit. It promises peace but delivers anxiety. It promises connection but delivers isolation. It promises relief but delivers deeper pain. Jesus offers the real thing — abundant life. Not easy life, not pain-free life, but life with meaning, purpose, presence, and hope. Today, identify what your addiction was counterfeiting, and begin reaching for the real thing.',
        reflection_q: 'What was your substance pretending to give you? Peace? Confidence? Escape? Connection? What is the real version of that, and how can you pursue it?',
      },
      journal: { prompt: 'Create two columns. Column A: "What the substance promised me." Column B: "What actually delivers that (the real version)." For each counterfeit promise, find the authentic source.', entry_type: 'general' },
      workout: { premade_id: 'beginner-full-body', motivational_tip: 'Exercise delivers real endorphins — not borrowed ones. This is the authentic version of feeling good.', coach_note: 'Focus on how you FEEL after the workout. Memorize that feeling.' },
      nutrition: { focus: 'Whole foods over processed', meal_theme: 'Real nourishment', plan: 'Your body was fed counterfeit fuel. Today, eat only whole, unprocessed foods. Real food from the earth. Nothing from a box, bag, or drive-through. This is a recalibration day.', tip: 'If your great-grandmother would not recognize it as food, skip it today.', recipe_search: 'whole foods clean eating simple meal' },
      affirmation: 'The counterfeit has been exposed. I am reaching for the real thing — abundant life through Christ.',
    },
    {
      day: 13, week: 2,
      title: 'Freedom Is Not Just Sobriety',
      bible: { book: 'Galatians', chapter: 5, verse_range: '1',
        key_verse: '"Stand firm therefore in the liberty by which Christ has made us free, and don\'t be entangled again with a yoke of bondage." — Galatians 5:1 (WEB)',
        devotion: 'Sobriety is the floor — not the ceiling. God did not free you from alcohol or drugs just so you could white-knuckle your way through every day for the rest of your life. He freed you FOR something — for purpose, for joy, for service, for love, for the abundant life He promised. True freedom is not just the absence of the substance. It is the presence of a new life that is so full you do not need the old one anymore.',
        reflection_q: 'What does freedom look like for you beyond just "not using"? What life are you being freed FOR?',
      },
      journal: { prompt: 'Write a vision for your free life. Not just sober — FREE. What does your morning look like? Your relationships? Your health? Your faith? Your career? Your joy? Write it in present tense as if it is already true.', entry_type: 'general' },
      workout: { premade_id: 'yoga-flow', motivational_tip: 'Flexibility in the body creates flexibility in the mind. Recovery requires both.', coach_note: 'Open the body. Release the tension of a hard week of identity work.' },
      nutrition: { focus: 'Anti-inflammatory eating', meal_theme: 'Reducing internal inflammation', plan: 'Chronic substance use creates systemic inflammation. Fight it with anti-inflammatory foods: berries, fatty fish, olive oil, turmeric, leafy greens, nuts. Reduce sugar, refined carbs, and seed oils.', tip: 'Inflammation drives both physical pain and mental fog. Reducing it will help you think more clearly.', recipe_search: 'anti-inflammatory healing meal' },
      affirmation: 'I am not just sober — I am FREE. Christ set me free for a life of purpose, joy, and abundance.',
    },
    {
      day: 14, week: 2,
      title: 'Halfway Through — The Mirror',
      bible: { book: 'Philippians', chapter: 3, verse_range: '13–14',
        key_verse: '"But one thing I do: forgetting the things which are behind, and stretching forward to the things which are before, I press on toward the goal for the prize of the high calling of God in Christ Jesus." — Philippians 3:13–14 (WEB)',
        devotion: 'Two weeks. You are halfway through this plan. You have been more honest than you have been in years. You have confronted shame, grieved losses, identified triggers, and begun rebuilding your identity. Paul says the posture of the free person is forward-leaning — forgetting what is behind and pressing toward what is ahead. You cannot change the past. But the next 14 days are yours.',
        reflection_q: 'What is different about you today compared to Day 1? What are you most proud of? What still scares you about the road ahead?',
      },
      journal: { prompt: 'Write a midpoint letter to yourself. Acknowledge how far you have come. Name what has changed. Then write what you are committing to for the next two weeks. Sign it.', entry_type: 'weekly_reflection' },
      workout: { premade_id: 'desk-stretch', motivational_tip: 'Halfway. Rest. Reflect. Recover. Then come back stronger for Week 3.', coach_note: 'Active recovery. Gentle stretching. Celebrate the milestone.' },
      nutrition: { focus: 'Midpoint nutrition check', meal_theme: 'Sustaining the changes', plan: 'Review your eating over the last 2 weeks. Are you eating regularly? Are you hydrated? Are you fueling recovery or just getting by? Adjust your plan for the next two weeks based on what you have learned about your body.', tip: 'Consistency beats perfection. If you ate well 80% of the time, you are winning.', recipe_search: 'balanced healthy recovery meal' },
      affirmation: 'I am halfway through and I am not the same person who started. I press on toward the goal of freedom.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 3 — REBUILDING: "New Patterns, New Life"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 15, week: 3,
      title: 'The Power of Routine',
      bible: { book: 'Daniel', chapter: 6, verse_range: '10',
        key_verse: '"When Daniel knew that the writing was signed, he went into his house... and he kneeled on his knees three times a day, and prayed, and gave thanks before his God, as he did before." — Daniel 6:10 (WEB)',
        devotion: 'Daniel was told his routine of prayer would get him thrown to the lions. He kept doing it anyway. When everything around him was threatening his life, he fell back on his habits. That is the power of routine — it holds you when willpower fails. Recovery requires building a new daily structure that replaces the hours, rituals, and patterns that used to revolve around the substance.',
        reflection_q: 'What does your ideal recovery day look like from waking to sleeping? What routines are you building that will hold you when willpower runs out?',
      },
      journal: { prompt: 'Design your ideal daily routine for recovery. Hour by hour if possible. Include: morning prayer/meditation, meals, movement, work, connection with others, evening wind-down. Write it as a plan you can follow starting tomorrow.', entry_type: 'general' },
      workout: { premade_id: 'morning-energizer', motivational_tip: 'The same time, the same workout, the same discipline — every day. Routine is your armor.', coach_note: 'Consistency is your new superpower. Show up at the same time every day.' },
      nutrition: { focus: 'Meal timing', meal_theme: 'Structure and consistency', plan: 'Eat at the same times every day this week. Breakfast within 1 hour of waking, lunch midday, dinner early evening. Consistent meal timing stabilizes blood sugar and reduces cravings.', tip: 'Set alarms for meals if you need to. Treat eating like medicine — non-negotiable.', recipe_search: 'structured meal plan routine' },
      affirmation: 'I am building a daily structure that holds me. My routine is my armor, and consistency is my weapon.',
    },
    {
      day: 16, week: 3,
      title: 'New People, New Places, New Things',
      bible: { book: 'Proverbs', chapter: 13, verse_range: '20',
        key_verse: '"One who walks with wise men grows wise, but a companion of fools suffers harm." — Proverbs 13:20 (WEB)',
        devotion: 'Recovery often requires changing your environment. The friends who use, the bars you frequented, the routines that revolved around substances — these are not neutral. They are gravitational fields pulling you back. This is not judgment on those people — it is protection for you. You need to be ruthlessly honest about which environments support your recovery and which sabotage it.',
        reflection_q: 'Who in your life supports your recovery? Who makes it harder? What environments are you willing to leave behind to stay free?',
      },
      journal: { prompt: 'Make three lists: (1) People who support my recovery (2) People/places/situations I need to avoid (3) New people/places/activities I want to build into my life. Be honest, even if it is painful.', entry_type: 'general' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'The gym is one of the best "new places" in recovery. Surround yourself with people pursuing health.', coach_note: 'Consider finding a workout partner. Accountability in fitness translates to accountability in recovery.' },
      nutrition: { focus: 'Social eating', meal_theme: 'Recovery-friendly social meals', plan: 'Practice eating a meal with someone who supports your recovery. Social meals without substances can feel unfamiliar at first. Practice it. Order sparkling water with lime. It gets easier.', tip: 'Have a non-alcoholic drink in your hand at social events — it reduces questions and pressure.', recipe_search: 'dinner party non alcoholic celebration' },
      affirmation: 'I am building a new environment that supports my freedom. I choose wise companions who help me grow.',
    },
    {
      day: 17, week: 3,
      title: 'What to Do When Cravings Hit',
      bible: { book: 'Psalms', chapter: 46, verse_range: '1–3',
        key_verse: '"God is our refuge and strength, a very present help in trouble." — Psalm 46:1 (WEB)',
        devotion: 'Cravings will come. This is not failure — it is normal. The question is not whether you will be tempted, but what you will do in the first 90 seconds. Research shows most cravings pass within 15-20 minutes if you do not act on them. You need a plan for those minutes. God is a very present help — not a distant one. He is available in the exact moment of temptation.',
        reflection_q: 'What is your 90-second craving response plan? What will you do in the first moments when the urge hits?',
      },
      journal: { prompt: 'Write your HALT+B craving response card: When I am Hungry — I will eat. When I am Angry — I will pray/call someone. When I am Lonely — I will reach out. When I am Tired — I will rest. When I am Bored — I will move my body. Keep this on your phone.', entry_type: 'general' },
      workout: { premade_id: 'hiit-30', motivational_tip: 'When a craving hits, do 20 burpees. By the time you finish, the craving has lost its grip. Movement breaks the cycle.', coach_note: 'High intensity is a craving-breaker. Remember this workout when temptation comes.' },
      nutrition: { focus: 'Craving substitutes', meal_theme: 'Healthy alternatives', plan: 'Sweet cravings? Try frozen grapes, dates, or dark chocolate. Want something to sip? Kombucha, herbal tea, or sparkling water with fruit. The oral fixation is real — give your mouth something healthy to do.', tip: 'Keep recovery snacks pre-made and accessible so you are never scrambling in a craving moment.', recipe_search: 'healthy craving substitute snacks' },
      affirmation: 'Cravings are temporary. God is permanent. I have a plan, and I will use it.',
    },
    {
      day: 18, week: 3,
      title: 'Making Amends',
      bible: { book: 'Matthew', chapter: 5, verse_range: '23–24',
        key_verse: '"If therefore you are offering your gift at the altar, and there remember that your brother has anything against you, leave your gift there before the altar, and go your way. First be reconciled to your brother, and then come and offer your gift." — Matthew 5:23–24 (WEB)',
        devotion: 'Addiction leaves wreckage in other people\'s lives. You cannot heal fully while carrying the weight of unaddressed harm. Making amends is not about groveling or self-flagellation — it is about taking responsibility, asking for forgiveness, and doing what you can to repair what was broken. Some relationships may not be repairable. That is okay. Your job is to offer the amend; the outcome is not in your control.',
        reflection_q: 'Who have you harmed through your addiction? Who deserves an honest conversation and an apology? Are you ready to begin that process?',
      },
      journal: { prompt: 'Write a list of people your addiction has affected. For each person, write: (1) What happened (2) How it affected them (3) What you would say if you could. You do not have to send these yet — just write them.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'yoga-flow', motivational_tip: 'Letting go of guilt in the body through gentle movement mirrors the emotional release of making amends.', coach_note: 'Emotional day. Move gently. Breathe deeply.' },
      nutrition: { focus: 'Self-care meal', meal_theme: 'Nourishing yourself is not selfish', plan: 'Making amends is heavy work. Feed yourself well today. Cook something that requires care and attention — the act of nourishing yourself is part of the healing.', tip: 'You cannot pour from an empty cup. Eating well is not selfish — it is necessary.', recipe_search: 'self care nourishing comfort meal' },
      affirmation: 'I take responsibility for the harm I caused. I offer amends with humility and leave the outcome to God.',
    },
    {
      day: 19, week: 3,
      title: 'Learning to Feel Again',
      bible: { book: 'Ecclesiastes', chapter: 3, verse_range: '1, 4',
        key_verse: '"For everything there is a season, and a time for every purpose under heaven... a time to weep, and a time to laugh; a time to mourn, and a time to dance." — Ecclesiastes 3:1, 4 (WEB)',
        devotion: 'Substances numb emotions. That was the point. But in recovery, feelings come flooding back — and they are LOUD. Joy feels overwhelming. Sadness feels crushing. Anger feels volcanic. This is normal. Your emotional nervous system is recalibrating after being suppressed. The goal is not to numb the feelings again — it is to learn to sit with them, name them, and let them pass through you without destroying you.',
        reflection_q: 'What emotions are you feeling most intensely right now? Are you tempted to numb them? What would it look like to feel them fully and let them pass?',
      },
      journal: { prompt: 'Set a timer for 5 minutes. Write whatever emotions come. Do not edit, do not censor. Just stream of consciousness. Then read it back. Name each emotion you see. This is emotional literacy — a recovery superpower.', entry_type: 'emotional_checkin' },
      workout: { premade_id: 'beginner-full-body', motivational_tip: 'Physical movement is one of the healthiest ways to process intense emotions. Sweat is emotional release.', coach_note: 'If emotions come up during the workout, let them. Keep moving. They will pass.' },
      nutrition: { focus: 'Tryptophan for mood', meal_theme: 'Mood stabilization', plan: 'Tryptophan converts to serotonin in the brain. Eat turkey, chicken, eggs, cheese, nuts, and seeds. These naturally support emotional regulation.', tip: 'Pair tryptophan foods with complex carbs for better absorption.', recipe_search: 'tryptophan mood stabilizing meal' },
      affirmation: 'I am learning to feel again without running. Every emotion is temporary, and I am strong enough to sit with it.',
    },
    {
      day: 20, week: 3,
      title: 'Relapse Is Not the End',
      bible: { book: 'Proverbs', chapter: 24, verse_range: '16',
        key_verse: '"For a righteous man falls seven times, and rises up again." — Proverbs 24:16 (WEB)',
        devotion: 'This is the most important truth in recovery: relapse does not erase your progress. It is a setback, not a reset. The righteous person is not defined by never falling — they are defined by getting back up. If you have relapsed during this plan, or if you relapse in the future, this verse is your lifeline. Get up. Call someone. Be honest. Return to Day 1 of your routine. Do not let shame convince you that one slip means the war is lost.',
        reflection_q: 'If relapse happens, what will your "get back up" plan look like? Who will you call? What will you do within the first hour?',
      },
      journal: { prompt: 'Write your relapse response plan. (1) Who I will call within 10 minutes. (2) Where I will go (a safe environment). (3) What I will say ("I slipped, and I need support"). (4) What I will do the next morning (return to my routine). Keep this plan accessible.', entry_type: 'general' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'Falling in the gym is part of training. Falling in recovery is part of the process. Get back under the bar.', coach_note: 'The goal is resilience, not perfection.' },
      nutrition: { focus: 'Consistent eating through setbacks', meal_theme: 'Do not abandon self-care', plan: 'When setbacks happen, self-care is the first thing to go — people stop eating, stop sleeping, stop exercising. The most important thing you can do after a setback is eat your next meal. Self-care is not earned through good behavior.', tip: 'Have easy, pre-prepared meals available so that when hard days come, feeding yourself does not require willpower.', recipe_search: 'easy meal prep recovery simple' },
      affirmation: 'If I fall, I will rise again. Relapse is not my identity — resilience is. I get back up.',
    },
    {
      day: 21, week: 3,
      title: 'Week 3 Rest and Reflection',
      bible: { book: 'Isaiah', chapter: 43, verse_range: '18–19',
        key_verse: '"Don\'t remember the former things, and don\'t consider the things of old. Behold, I will do a new thing. It springs out now. Don\'t you know it?" — Isaiah 43:18–19 (WEB)',
        devotion: 'God is doing something new in you. Can you feel it springing up? Three weeks ago, you started this journey with honesty. Two weeks ago, you began rebuilding your identity. This week, you have been laying down new patterns — new routines, new relationships, new coping strategies. God says do not fixate on the old. Look at what is emerging. It is new. It is real. And it is just getting started.',
        reflection_q: 'What "new thing" do you see God doing in your life right now? What has surprised you most about Week 3?',
      },
      journal: { prompt: 'Reflect on Week 3. What new pattern are you most proud of? What was the hardest craving moment and how did you handle it? What still needs work? Write honestly.', entry_type: 'weekly_reflection' },
      workout: { premade_id: 'desk-stretch', motivational_tip: 'Gentle rest. You have earned it. Three weeks of building is serious work.', coach_note: 'Recovery day. Light stretching. Deep breathing.' },
      nutrition: { focus: 'Celebration meal', meal_theme: 'Joy without substances', plan: 'Celebrate three weeks of recovery with a special meal. Cook something elaborate, order something you love, or share a meal with someone who has supported you. Celebrate WITHOUT the substance. Train your brain that joy exists without it.', tip: 'Celebration is a critical recovery skill. Learning to mark milestones without substances rewires your reward system.', recipe_search: 'celebration meal no alcohol special dinner' },
      affirmation: 'God is doing a new thing in me. I can see it springing up. Three weeks in — I am not going back.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 4 — COMMUNITY: "You Were Never Meant to Walk Alone"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 22, week: 4,
      title: 'You Need People',
      bible: { book: 'Ecclesiastes', chapter: 4, verse_range: '9–10',
        key_verse: '"Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn\'t have another to lift him up." — Ecclesiastes 4:9–10 (WEB)',
        devotion: 'Isolation is addiction\'s operating system. It tells you that no one understands, no one cares, and you are better off handling this alone. That is a lie. Recovery happens in community — not in isolation. You need people who will celebrate your wins, catch you when you fall, and tell you the truth when you are drifting. Today, reach out to someone.',
        reflection_q: 'Who are your "two or three" — the people you would trust with your recovery? If you do not have them yet, where will you find them?',
      },
      journal: { prompt: 'List the people in your recovery circle: (1) Someone who has walked through addiction themselves (2) Someone who loves you unconditionally (3) A professional (counselor, pastor, sponsor). If any of these seats are empty, write a plan to fill them this week.', entry_type: 'general' },
      workout: { premade_id: 'morning-energizer', motivational_tip: 'Consider inviting someone to work out with you today. Shared struggle builds shared strength.', coach_note: 'Connection is the opposite of addiction. Reach out today.' },
      nutrition: { focus: 'Shared meal', meal_theme: 'Breaking bread together', plan: 'Eat a meal with someone from your recovery circle today. The table is one of God\'s primary places of healing — from the Last Supper to the first-century church. Food shared in love is medicine.', tip: 'If you cannot meet in person, eat on a video call. Presence matters.', recipe_search: 'meal to share with friend community' },
      affirmation: 'I was not made to walk this road alone. I am reaching out, connecting, and letting people in.',
    },
    {
      day: 23, week: 4,
      title: 'Accountability Without Shame',
      bible: { book: 'Galatians', chapter: 6, verse_range: '1–2',
        key_verse: '"Brothers, even if a man is caught in some fault, you who are spiritual must restore such a one in a spirit of gentleness, looking to yourself so that you also aren\'t tempted. Bear one another\'s burdens, and so fulfill the law of Christ." — Galatians 6:1–2 (WEB)',
        devotion: 'Accountability is not surveillance. It is not someone checking up on you with suspicion. True accountability is someone walking beside you with gentleness — bearing your burden because they know they have their own. Find people who will ask you hard questions with kind eyes. People who will not shame you when you struggle, but who will also not let you lie to yourself.',
        reflection_q: 'Do you have someone you check in with regularly about your recovery? If not, who could you ask? What would you want them to ask you?',
      },
      journal: { prompt: 'Write 5 questions you want an accountability partner to ask you weekly. Examples: "Have you been honest this week?" "When was your strongest craving and what did you do?" "Are you sleeping, eating, and praying?" "Is there anything you are hiding?" "How can I support you?"', entry_type: 'general' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'A spotter in the gym does not lift the weight for you. They just make sure you do not get crushed. That is accountability.', coach_note: 'Progress requires both effort and support. Neither alone is enough.' },
      nutrition: { focus: 'Routine meal prep', meal_theme: 'Preparing ahead', plan: 'Meal prep for the rest of the week. Having food prepared removes one more decision from your day — and in recovery, decision fatigue is a real threat. Cook in bulk: proteins, grains, and vegetables you can combine easily.', tip: 'Sunday meal prep is one of the highest-ROI recovery habits you can build.', recipe_search: 'meal prep recovery week plan' },
      affirmation: 'I invite accountability into my life — not as punishment, but as protection and love.',
    },
    {
      day: 24, week: 4,
      title: 'Forgiving Yourself',
      bible: { book: '1 John', chapter: 1, verse_range: '9',
        key_verse: '"If we confess our sins, he is faithful and righteous to forgive us our sins, and to cleanse us from all unrighteousness." — 1 John 1:9 (WEB)',
        devotion: 'You may have accepted that God forgives you. But have you forgiven yourself? Many people in recovery carry a debt they refuse to cancel — the debt against themselves. "I should have known better." "I wasted so many years." "I hurt my family." These are true statements. But if God — who is perfectly just — has forgiven you, who are you to override His judgment? Self-forgiveness is not excusing what happened. It is accepting the pardon that has already been given.',
        reflection_q: 'What have you not forgiven yourself for? What would it take to accept God\'s forgiveness as final?',
      },
      journal: { prompt: 'Write a forgiveness letter to yourself. Address the version of you who was in addiction. Acknowledge what happened with honesty. Then write: "I forgive you. You did not know what you know now. And from this point forward, we walk in freedom."', entry_type: 'spiritual' },
      workout: { premade_id: 'yoga-flow', motivational_tip: 'Release. Let go. Soften. Forgiveness is a physical act as much as a spiritual one.', coach_note: 'Breathe into every stretch. Release what you have been holding.' },
      nutrition: { focus: 'Gentle nutrition', meal_theme: 'Be kind to your body', plan: 'Today is about self-compassion in the kitchen. Cook something nourishing and eat it slowly, without guilt. Your body carried you through addiction and it is still here, still fighting. Feed it with gratitude.', tip: 'No calorie counting today. Just eat well, eat enough, and say thank you to the body that survived.', recipe_search: 'gentle nourishing self compassion meal' },
      affirmation: 'If God has forgiven me, I can forgive myself. I release the debt. I accept the pardon. I walk free.',
    },
    {
      day: 25, week: 4,
      title: 'Your Story Can Save Someone',
      bible: { book: 'Revelation', chapter: 12, verse_range: '11',
        key_verse: '"They overcame him because of the Lamb\'s blood, and because of the word of their testimony." — Revelation 12:11 (WEB)',
        devotion: 'Your story of addiction and recovery is not your shame — it is your weapon. Revelation says the saints overcome the enemy by the blood of the Lamb AND by the word of their testimony. Your testimony is not complete until you share it. Somewhere right now, someone is in the exact place you were on Day 1 of this plan. They need to hear that freedom is possible. Your pain has prepared you to be their proof.',
        reflection_q: 'Are you ready to share your story? Not with everyone — but with one person who needs to hear it?',
      },
      journal: { prompt: 'Write your testimony in 3 paragraphs: (1) Where you were (2) What God did (3) Where you are now. Keep it honest. Keep it real. You may never share it, or you may share it with one person, or you may share it with a thousand. Write it either way.', entry_type: 'spiritual' },
      workout: { premade_id: 'hiit-30', motivational_tip: 'Your strength is evidence of your transformation. Let it speak.', coach_note: 'Strong workout for a strong day. Finish well.' },
      nutrition: { focus: 'Fueling purpose', meal_theme: 'Eating for mission', plan: 'You are not just surviving anymore — you are being prepared for a mission. Eat like someone who has somewhere to go and something to do. High-quality protein, vegetables, whole grains, healthy fats. This is mission fuel.', tip: 'Purpose changes how you eat. When you are living FOR something, you stop putting garbage IN your body.', recipe_search: 'high performance purpose driven meal' },
      affirmation: 'My story is my testimony. My pain is my weapon. Someone needs to hear that freedom is real.',
    },
    {
      day: 26, week: 4,
      title: 'Building a Life You Do Not Want to Escape',
      bible: { book: 'Jeremiah', chapter: 29, verse_range: '11',
        key_verse: '"For I know the thoughts that I think toward you,\" says Yahweh, \"thoughts of peace, and not of evil, to give you hope and a future." — Jeremiah 29:11 (WEB)',
        devotion: 'The ultimate recovery goal is not sobriety. It is building a life so meaningful, so connected, so purpose-driven that you no longer need an escape hatch. You used substances to escape pain, boredom, loneliness, or emptiness. The answer is not just removing the escape — it is filling the emptiness with something real. God has plans for you. Not plans to survive — plans to thrive.',
        reflection_q: 'What kind of life would be so fulfilling that you would never want to escape it? What is one step you can take today toward building that life?',
      },
      journal: { prompt: 'Design your life 1 year from now. Be specific: Where are you living? Who is in your life? What is your daily routine? What are you doing for work? For service? For joy? Write it in vivid detail.', entry_type: 'general' },
      workout: { premade_id: 'strength-circuit', motivational_tip: 'Build the strongest version of yourself — not to run from something, but to run TOWARD something.', coach_note: 'Train with intention. Every rep is building the future you.' },
      nutrition: { focus: 'Sustainable eating patterns', meal_theme: 'Long-term wellness', plan: 'Recovery eating is not a diet — it is a lifestyle. Build an eating pattern you can sustain for years: regular meals, whole foods, plenty of water, treats in moderation, and zero guilt. This is the long game.', tip: 'The best nutrition plan is the one you can follow for the rest of your life.', recipe_search: 'sustainable healthy lifestyle meal' },
      affirmation: 'I am building a life I do not want to escape. God\'s plans for me are good, and I am stepping into them.',
    },
    {
      day: 27, week: 4,
      title: 'Gratitude as a Weapon',
      bible: { book: '1 Thessalonians', chapter: 5, verse_range: '16–18',
        key_verse: '"Rejoice always. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you." — 1 Thessalonians 5:16–18 (WEB)',
        devotion: 'Gratitude is not just a nice feeling — it is a neurological weapon against addiction. Research shows that gratitude activates the same brain regions that substances hijack — the reward center. When you practice gratitude daily, you are literally retraining your brain to find reward in real life instead of in a bottle or a pill. This is not positive thinking. This is neuroscience meeting Scripture.',
        reflection_q: 'What are you genuinely grateful for in your recovery? Name 10 things — from the tiny (clean sheets) to the massive (you are alive).',
      },
      journal: { prompt: 'Write 10 things you are grateful for today. Then write 10 things you are grateful for BECAUSE of your recovery. Then write 10 things you are grateful for that you almost lost. Read this list out loud.', entry_type: 'gratitude' },
      workout: { premade_id: 'beginner-full-body', motivational_tip: 'Your body works. Your lungs breathe. Your heart beats. Gratitude starts in the body.', coach_note: 'Move with gratitude today. Every rep is a thank-you to the body that survived.' },
      nutrition: { focus: 'Mindful eating', meal_theme: 'Eating with gratitude', plan: 'Eat one meal today without your phone, without TV, without distraction. Just you and the food. Taste it. Smell it. Feel the texture. Say thank you for it. This is mindful eating, and it rewires your relationship with pleasure.', tip: 'Mindful eating reduces binge eating, emotional eating, and craving intensity.', recipe_search: 'mindful eating simple beautiful meal' },
      affirmation: 'Gratitude rewires my brain. I choose thankfulness today as an act of worship and a weapon against addiction.',
    },
    {
      day: 28, week: 4,
      title: 'The Chains Are Broken — Walk Free',
      bible: { book: 'John', chapter: 8, verse_range: '36',
        key_verse: '"If therefore the Son makes you free, you will be free indeed." — John 8:36 (WEB)',
        devotion: 'Twenty-eight days. You made it. You were honest when it hurt. You rebuilt your identity when shame tried to name you. You created new patterns when old ones pulled at you. You reached out when isolation called. And today, Jesus speaks over you the same words He spoke 2,000 years ago: "You are free indeed." Not free-ish. Not mostly free. Not free until the next craving. FREE INDEED. The chains are broken. The cell door is open. And the road ahead is wide, bright, and full of purpose. This is not the end of your recovery — it is the foundation. Keep going. Keep showing up. Keep surrendering. And when the hard days come — and they will — remember: you have already proven that freedom is possible.',
        reflection_q: 'What does "free indeed" mean to you today? How has your understanding of freedom changed since Day 1?',
      },
      journal: { prompt: 'Write a letter to the person you were on Day 1. Tell them what you have learned. Tell them what has changed. Tell them what is ahead. Then write a commitment: "From this day forward, I choose..." and finish the sentence with whatever is on your heart.', entry_type: 'weekly_reflection' },
      workout: { premade_id: 'hiit-30', motivational_tip: 'End this plan strong. Leave everything on the floor. You are not the same person who started.', coach_note: 'Final workout of the plan. Give it everything you have. You have earned this.' },
      nutrition: { focus: 'Celebration feast', meal_theme: 'Freedom feast', plan: 'Cook a beautiful meal tonight. Invite someone who supported your recovery. Light candles. Set the table. This is your freedom feast — a meal that celebrates 28 days of courage, honesty, and transformation. No substances required.', tip: 'Mark this day. Create a new tradition. Every 28 days, have your freedom feast and celebrate how far you have come.', recipe_search: 'celebration feast recovery milestone dinner' },
      affirmation: 'If the Son sets me free, I am free INDEED. The chains are broken. I am walking into a new life.',
    },
  ],
};
