// ─────────────────────────────────────────────────────────────────────────────
// GRACE & RESTORATION — 4-Week Coaching Plan
// "Walking in Freedom: A Journey Through Grace, Forgiveness & New Identity"
// ─────────────────────────────────────────────────────────────────────────────

export const GRACE_RESTORATION_PLAN = {
  id: 'grace-restoration',
  title: 'Grace & Restoration',
  subtitle: '4 Weeks to Freedom Through Forgiveness',
  description: 'A 28-day journey through the heart of the Gospel — grace, forgiveness, identity, and freedom. Break free from shame, learn to forgive yourself and others, and step into who God says you are. Guided by Scripture, prayer, and daily reflection.',
  weeks: 4,
  days_total: 28,
  difficulty: 'All Levels',
  gradient: 'from-[#c9a227] to-[#FAD98D]',
  accent: '#c9a227',
  emoji: '🕊️',
  category: 'spiritual',
  coach: 'Gideon',
  tags: ['grace', 'forgiveness', 'identity', 'freedom', 'restoration'],
  week_themes: [
    { week: 1, theme: 'Grace',        title: 'Receiving What You Cannot Earn', color: 'from-[#c9a227] to-[#FAD98D]', accent: '#c9a227', emoji: '🕊️' },
    { week: 2, theme: 'Forgiveness',   title: 'Releasing What Holds You Back',  color: 'from-[#0A1A2F] to-[#AFC7E3]', accent: '#AFC7E3', emoji: '🤍' },
    { week: 3, theme: 'Identity',      title: 'Becoming Who God Says You Are',  color: 'from-[#3C4E53] to-[#FD9C2D]', accent: '#FD9C2D', emoji: '👑' },
    { week: 4, theme: 'Freedom',       title: 'Living Unchained',              color: 'from-[#0A1A2F] to-[#c9a227]', accent: '#c9a227', emoji: '✨' },
  ],
  days: [
    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 1 — GRACE: "Receiving What You Cannot Earn"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 1, week: 1,
      title: 'The Gift You Cannot Earn',
      bible: { book: 'Ephesians', chapter: 2, verse_range: '8–9',
        key_verse: '"For by grace you have been saved through faith, and that not of yourselves; it is the gift of God." — Ephesians 2:8',
        devotion: 'Grace is not a reward for good behavior. It is the unearned, undeserved, unstoppable love of God poured out on people who could never earn it. Today we begin not by trying harder, but by receiving what has already been given. You don\'t have to clean yourself up before coming to God. He meets you exactly where you are.',
        reflection_q: 'In what area of your life have you been trying to earn God\'s love instead of simply receiving it?',
      },
      journal: { prompt: 'Write about a time you felt unworthy of love or grace. Now write what God says about you in Ephesians 2:10 — "created in Christ Jesus to do good works." How do these two truths sit together?', entry_type: 'spiritual' },
      affirmation: 'I am saved by grace, not by my performance. God\'s love for me is not something I earn — it is something I receive.',
    },
    {
      day: 2, week: 1,
      title: 'Sufficient Grace',
      bible: { book: '2 Corinthians', chapter: 12, verse_range: '9–10',
        key_verse: '"My grace is sufficient for you, for my power is made perfect in weakness." — 2 Corinthians 12:9',
        devotion: 'Paul asked God three times to remove his thorn. God said no — but He said something better: My grace is enough. Your weakness is not disqualifying. It is the very place where God\'s power shows up most clearly. Stop hiding your struggles. They are the canvas on which grace paints its masterpiece.',
        reflection_q: 'What weakness or struggle have you been hiding from God or others? What would it look like to let grace meet you there?',
      },
      journal: { prompt: 'Name one area where you feel weak or insufficient. Now write a prayer inviting God\'s strength into that exact place.', entry_type: 'spiritual' },
      affirmation: 'My weakness is not my shame — it is where God\'s power is perfected. His grace is sufficient for me today.',
    },
    {
      day: 3, week: 1,
      title: 'New Every Morning',
      bible: { book: 'Lamentations', chapter: 3, verse_range: '22–26',
        key_verse: '"Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning." — Lamentations 3:22-23',
        devotion: 'Jeremiah wrote these words from the ruins of Jerusalem — not from a mountaintop experience. Grace is not just for good days. It is designed for the wreckage, the aftermath, the morning after you failed again. Every sunrise is God saying: "I\'m not done with you. Let\'s start again."',
        reflection_q: 'What do you need to leave behind from yesterday? What would it look like to truly start fresh this morning?',
      },
      journal: { prompt: 'Write a letter to yourself from God\'s perspective. What would He say about yesterday\'s failures? What would He say about today\'s possibilities?', entry_type: 'spiritual' },
      affirmation: 'Yesterday is gone. God\'s mercies are new this morning. I am not defined by my worst day.',
    },
    {
      day: 4, week: 1,
      title: 'Grace in the Mess',
      bible: { book: 'Romans', chapter: 5, verse_range: '6–8',
        key_verse: '"But God commends his own love toward us, in that while we were yet sinners, Christ died for us." — Romans 5:8',
        devotion: 'God didn\'t wait for you to get it together. He loved you at your worst. Not after you cleaned up, not after you proved yourself — while you were still in the mess. This is what makes grace radical. It doesn\'t require improvement as a prerequisite. It offers love as the starting point.',
        reflection_q: 'Do you believe God loves you right now — not a future, improved version of you, but the you sitting here today?',
      },
      journal: { prompt: 'What conditions have you placed on receiving God\'s love? "I\'ll feel worthy when..." Finish that sentence, then cross it out and write: "I am worthy now because Christ says so."', entry_type: 'spiritual' },
      affirmation: 'God loved me at my worst. I don\'t have to earn what has already been freely given.',
    },
    {
      day: 5, week: 1,
      title: 'The Prodigal\'s Welcome',
      bible: { book: 'Luke', chapter: 15, verse_range: '20–24',
        key_verse: '"But while he was still far off, his father saw him and was moved with compassion, and ran and fell on his neck and kissed him." — Luke 15:20',
        devotion: 'The father didn\'t wait at the door with arms crossed. He ran. He didn\'t ask for an explanation. He threw a party. This is how God responds when you come home — not with a lecture, but with a celebration. No matter how far you\'ve wandered, the Father is already running toward you.',
        reflection_q: 'Where have you wandered from God? Can you picture Him running toward you right now — not angry, but overjoyed?',
      },
      journal: { prompt: 'Write your own "coming home" prayer. Tell God where you\'ve been and what you want to come back to.', entry_type: 'prayer' },
      affirmation: 'No matter how far I\'ve wandered, the Father runs toward me with open arms. I am always welcome home.',
    },
    {
      day: 6, week: 1,
      title: 'Grace Over Performance',
      bible: { book: 'Galatians', chapter: 3, verse_range: '2–5',
        key_verse: '"Did you receive the Spirit by the works of the law, or by believing what you heard?" — Galatians 3:2',
        devotion: 'Paul is almost frustrated here. He\'s saying: "You started this journey by faith — why are you now trying to finish it by effort?" Performance Christianity is exhausting. It turns God into a taskmaster and faith into a checklist. Grace says: you were saved by faith, you are sustained by faith, and you will finish by faith.',
        reflection_q: 'Where in your faith walk has effort replaced trust? What would it look like to rest in grace instead of striving?',
      },
      journal: { prompt: 'List three ways you\'ve been "performing" for God. Now write beside each one how grace reframes it.', entry_type: 'spiritual' },
      affirmation: 'I don\'t perform for God\'s approval. I rest in His acceptance and respond with grateful obedience.',
    },
    {
      day: 7, week: 1,
      title: 'Sabbath of Grace',
      bible: { book: 'Hebrews', chapter: 4, verse_range: '9–11',
        key_verse: '"There remains, then, a Sabbath-rest for the people of God." — Hebrews 4:9',
        devotion: 'Rest is not laziness — it is faith. It says: God, I trust that You are working even when I am not. Today is your day to stop striving, stop performing, stop earning. Simply be held. Let this first week of grace settle into your bones.',
        reflection_q: 'What would true spiritual rest look like for you today? Not escape, but genuine trust-filled rest?',
      },
      journal: { prompt: 'Reflect on this first week. Where did grace surprise you? Where did it challenge you? What is God stirring in your heart?', entry_type: 'weekly_reflection' },
      affirmation: 'I rest in God\'s finished work. I am held, loved, and secure — not because of what I do, but because of what He has done.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 2 — FORGIVENESS: "Releasing What Holds You Back"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 8, week: 2,
      title: 'The Weight of Unforgiveness',
      bible: { book: 'Matthew', chapter: 18, verse_range: '21–35',
        key_verse: '"Then the master called the servant in. \'You wicked servant,\' he said, \'I canceled all that debt of yours because you begged me to. Shouldn\'t you have had mercy?\'" — Matthew 18:32-33',
        devotion: 'Unforgiveness is like drinking poison and expecting the other person to get sick. Jesus tells this parable because He knows that holding onto bitterness doesn\'t punish the person who hurt you — it imprisons you. The servant was forgiven an impossible debt and then choked someone over pocket change. We do this too.',
        reflection_q: 'Is there someone you\'ve been withholding forgiveness from? What would it cost you to release them — and what is it costing you not to?',
      },
      journal: { prompt: 'Write the name of someone you need to forgive. You don\'t have to send this to them. Just name the hurt, name the anger, and then write: "I choose to release you, because God released me."', entry_type: 'spiritual' },
      affirmation: 'I release those who have hurt me — not because they deserve it, but because I deserve freedom.',
    },
    {
      day: 9, week: 2,
      title: 'Forgiving Yourself',
      bible: { book: 'Romans', chapter: 8, verse_range: '1–4',
        key_verse: '"Therefore, there is now no condemnation for those who are in Christ Jesus." — Romans 8:1',
        devotion: 'Sometimes the person hardest to forgive is the one in the mirror. You replay the mistake. You punish yourself with guilt. But hear this: if God Himself says there is NO condemnation, who are you to overrule Him? Self-forgiveness isn\'t arrogance — refusing it is. You are saying your judgment matters more than God\'s.',
        reflection_q: 'What past mistake are you still punishing yourself for? What would it mean to accept God\'s verdict of "not condemned"?',
      },
      journal: { prompt: 'Write a letter of forgiveness to yourself. Name what you did, acknowledge the pain, and then extend the same grace God extends to you.', entry_type: 'spiritual' },
      affirmation: 'There is no condemnation for me in Christ. I forgive myself because God already has.',
    },
    {
      day: 10, week: 2,
      title: 'Seventy Times Seven',
      bible: { book: 'Matthew', chapter: 18, verse_range: '21–22',
        key_verse: '"Jesus answered, \'I tell you, not seven times, but seventy-seven times.\'" — Matthew 18:22',
        devotion: 'Peter thought he was being generous — seven times! But Jesus blew past every limit. Forgiveness isn\'t a transaction with a cap. It\'s a lifestyle. It doesn\'t mean what they did was okay. It means you refuse to let it define your future.',
        reflection_q: 'Is there a hurt you thought you forgave but keeps resurfacing? What would repeated forgiveness look like in practice?',
      },
      journal: { prompt: 'Forgiveness is often a process, not a one-time event. Write about a wound that keeps resurfacing and what it would look like to forgive it again today.', entry_type: 'spiritual' },
      affirmation: 'Forgiveness is not a single act — it is a daily choice. And every day, I choose freedom.',
    },
    {
      day: 11, week: 2,
      title: 'Forgiveness as Strength',
      bible: { book: 'Ephesians', chapter: 4, verse_range: '31–32',
        key_verse: '"Be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you." — Ephesians 4:32',
        devotion: 'Forgiveness is not weakness. It is the most powerful act a human being can perform. It takes more strength to release than to hold on. Bitterness is easy — it runs on autopilot. Forgiveness requires intentional, Christ-like courage.',
        reflection_q: 'Have you ever confused forgiveness with weakness? How does seeing it as strength change your perspective?',
      },
      journal: { prompt: 'Write about the strongest act of forgiveness you\'ve ever witnessed or experienced. What made it powerful?', entry_type: 'general' },
      affirmation: 'Forgiveness is not weakness — it is the highest form of strength. I am strong enough to let go.',
    },
    {
      day: 12, week: 2, title: 'Breaking the Chain',
      bible: { book: 'Colossians', chapter: 3, verse_range: '12–14',
        key_verse: '"Bearing with one another, and forgiving each other, if any man has a complaint against any; even as Christ forgave you, so you also do." — Colossians 3:13',
        devotion: 'Hurt people hurt people. But forgiven people can break the chain. When you choose forgiveness, you\'re not just healing yourself — you\'re stopping generational pain, relational cycles, and inherited bitterness from passing to the next person.',
        reflection_q: 'Is there a cycle of hurt in your family or relationships that you have the power to break through forgiveness?',
      },
      journal: { prompt: 'Identify one relational pattern rooted in unforgiveness. Write out what it would look like broken — and what freedom would replace it.', entry_type: 'spiritual' },
      affirmation: 'I break the chain of hurt. Forgiveness flows through me and stops the cycle here.',
    },
    {
      day: 13, week: 2, title: 'Forgiven and Free',
      bible: { book: 'Psalm', chapter: 103, verse_range: '10–12',
        key_verse: '"As far as the east is from the west, so far has he removed our transgressions from us." — Psalm 103:12',
        devotion: 'East and west never meet. That\'s how far God has thrown your sin. He doesn\'t keep a record. He doesn\'t bring it up in arguments. He doesn\'t use it against you. If the Creator of the universe can release it, maybe you can too.',
        reflection_q: 'Are you holding onto something God has already released? What would it feel like to truly let it go?',
      },
      journal: { prompt: 'Write down something you\'ve been holding against yourself. Then physically cross it out and write Psalm 103:12 over it.', entry_type: 'spiritual' },
      affirmation: 'My sins have been removed as far as the east is from the west. I am forgiven and I am free.',
    },
    {
      day: 14, week: 2, title: 'The Freedom of Letting Go',
      bible: { book: 'Isaiah', chapter: 43, verse_range: '18–19',
        key_verse: '"Don\'t remember the former things, and don\'t consider the things of old. Behold, I will do a new thing." — Isaiah 43:18-19',
        devotion: 'God is in the business of new things. But you can\'t grab hold of the new if your hands are full of the old. This week asked you to release — people who hurt you, guilt you carried, chains that bound you. As you enter the weekend, open your hands. Let go. Something new is coming.',
        reflection_q: 'What "former thing" is God asking you to stop dwelling on so He can do a new thing in your life?',
      },
      journal: { prompt: 'Reflect on Week 2. What did you release? What still needs releasing? Write a prayer of surrender for the things you\'re not ready to let go of yet.', entry_type: 'weekly_reflection' },
      affirmation: 'I release the past. My hands are open. God is doing a new thing, and I am ready to receive it.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 3 — IDENTITY: "Becoming Who God Says You Are"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 15, week: 3, title: 'Chosen Before Time',
      bible: { book: 'Ephesians', chapter: 1, verse_range: '3–6',
        key_verse: '"He chose us in him before the foundation of the world, that we should be holy and without defect before him in love." — Ephesians 1:4',
        devotion: 'Before the universe had a single star, God chose you. Not as an afterthought. Not as a backup plan. You were handpicked, set apart, and called blameless — not because of anything you\'ve done, but because of His love.',
        reflection_q: 'How does knowing you were chosen before creation change the way you see yourself today?',
      },
      journal: { prompt: 'Write "I am chosen" at the top of the page. Then list five ways your life would be different if you truly believed it every single day.', entry_type: 'spiritual' },
      affirmation: 'I was chosen before the foundation of the world. I am not an accident — I am a deliberate act of God\'s love.',
    },
    {
      day: 16, week: 3, title: 'A New Creation',
      bible: { book: '2 Corinthians', chapter: 5, verse_range: '17',
        key_verse: '"Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new." — 2 Corinthians 5:17',
        devotion: 'You are not an improved version of the old you. You are a new creation. The old — the shame, the labels, the failures — has gone. Not hidden, not suppressed. Gone. The new is here. Live from your new identity, not your old one.',
        reflection_q: 'What "old label" do you still wear that God has already replaced? What is the new name He has given you?',
      },
      journal: { prompt: 'List three labels you\'ve carried from your past. Beside each one, write the truth God speaks over you instead.', entry_type: 'spiritual' },
      affirmation: 'The old has gone. I am a new creation in Christ. My past does not define my future.',
    },
    {
      day: 17, week: 3, title: 'God\'s Masterpiece',
      bible: { book: 'Ephesians', chapter: 2, verse_range: '10',
        key_verse: '"For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them." — Ephesians 2:10',
        devotion: 'The Greek word for "handiwork" is poiema — where we get the word "poem." You are God\'s poem. His art. His creative expression to the world. You are not a rough draft. You are a finished masterpiece with a purpose prepared before you were born.',
        reflection_q: 'If you truly saw yourself as God\'s masterpiece, what would you stop tolerating in your life? What would you start pursuing?',
      },
      journal: { prompt: 'God has prepared good works for you in advance. What do you sense He is preparing you for right now?', entry_type: 'spiritual' },
      affirmation: 'I am God\'s masterpiece — His poem written to the world. I have a purpose that was prepared before I was born.',
    },
    {
      day: 18, week: 3, title: 'Beloved Child',
      bible: { book: '1 John', chapter: 3, verse_range: '1',
        key_verse: '"See how great a love the Father has given to us, that we should be called children of God! And that is what we are!" — 1 John 3:1',
        devotion: 'John can barely contain himself. "See what great love!" He\'s overwhelmed. You are not just tolerated by God — you are loved with a lavishing, extravagant, over-the-top love. You are His child. Not a servant. Not an employee. A son or daughter. That changes everything.',
        reflection_q: 'Do you relate to God more as a child relates to a loving parent, or as an employee relates to a boss? What needs to shift?',
      },
      journal: { prompt: 'Write about what it means to you personally to be called a child of God. How does this identity shape your decisions?', entry_type: 'spiritual' },
      affirmation: 'I am a beloved child of God. I am not tolerated — I am lavished with love.',
    },
    {
      day: 19, week: 3, title: 'Seated in Authority',
      bible: { book: 'Ephesians', chapter: 2, verse_range: '6–7',
        key_verse: '"And God raised us up with Christ and seated us with him in the heavenly realms." — Ephesians 2:6',
        devotion: 'You are not crawling toward God hoping He\'ll notice you. You are already seated with Christ in heavenly places. This is your position — not something you\'re working toward. You operate from victory, not toward it.',
        reflection_q: 'How would your daily life change if you truly believed you are already seated in a place of spiritual authority?',
      },
      journal: { prompt: 'Write about one situation where you\'ve been living "beneath" your identity in Christ. How does Ephesians 2:6 reframe it?', entry_type: 'spiritual' },
      affirmation: 'I am seated with Christ in heavenly places. I operate from victory, not toward it.',
    },
    {
      day: 20, week: 3, title: 'Named and Known',
      bible: { book: 'Isaiah', chapter: 43, verse_range: '1',
        key_verse: '"I have called you by your name. You are mine." — Isaiah 43:1',
        devotion: 'God doesn\'t call you by your mistakes. He calls you by name. He knows you — your fears, your dreams, your 3am thoughts. And He says: You are mine. Not "you could be mine if you try harder." You ARE mine. Right now. As you are.',
        reflection_q: 'What name has the world given you that God wants to replace? What does He call you instead?',
      },
      journal: { prompt: 'God says "You are mine." Write a response to Him. What does it mean to belong completely to someone who loves you completely?', entry_type: 'prayer' },
      affirmation: 'God knows my name. I belong to Him. I am not lost — I am claimed, called, and known.',
    },
    {
      day: 21, week: 3, title: 'Living from Identity',
      bible: { book: 'Colossians', chapter: 3, verse_range: '1–4',
        key_verse: '"Set your minds on things above, where Christ is, seated at the right hand of God." — Colossians 3:1',
        devotion: 'This week you\'ve discovered who you are — chosen, new, a masterpiece, beloved, seated in authority, known by name. Now the question is: will you live from this identity or fall back into the old one? Setting your mind on things above isn\'t escapism. It\'s choosing to see reality as God sees it.',
        reflection_q: 'Which identity truth from this week was the hardest to believe? Which one do you most need to carry into next week?',
      },
      journal: { prompt: 'Reflect on Week 3. Write your "Identity Statement" — a paragraph declaring who you are in Christ, in your own words.', entry_type: 'weekly_reflection' },
      affirmation: 'I know who I am. I am chosen, forgiven, beloved, and free. I live from this identity every single day.',
    },

    // ═══════════════════════════════════════════════════════════════════════
    // WEEK 4 — FREEDOM: "Living Unchained"
    // ═══════════════════════════════════════════════════════════════════════
    {
      day: 22, week: 4, title: 'Free Indeed',
      bible: { book: 'John', chapter: 8, verse_range: '36',
        key_verse: '"If therefore the Son makes you free, you will be free indeed." — John 8:36',
        devotion: 'Not partially free. Not free with conditions. Free indeed — completely, fully, unshakably free. The chains of shame, guilt, fear, and performance have been broken. But sometimes we stand in the open cell door and refuse to walk out. Today, walk out.',
        reflection_q: 'What open door of freedom are you standing in front of but afraid to walk through?',
      },
      journal: { prompt: 'Finish this sentence twenty different ways: "Because of Christ, I am free from..." Let it flow without editing.', entry_type: 'spiritual' },
      affirmation: 'I am free indeed. Not partially, not conditionally — completely free through Christ.',
    },
    {
      day: 23, week: 4, title: 'Freedom from Shame',
      bible: { book: 'Romans', chapter: 10, verse_range: '11',
        key_verse: '"Everyone who believes in him will not be disappointed." — Romans 10:11',
        devotion: 'Shame says: "You ARE the mistake." Guilt says: "You MADE a mistake." Grace says: "The mistake is covered, and you are loved." Shame is the enemy\'s favorite weapon because it attacks identity. But God has declared you will never be put to shame. Believe it.',
        reflection_q: 'Where has shame been speaking louder than grace in your life? What truth needs to replace it?',
      },
      journal: { prompt: 'Write about one area where shame has been running the show. Then write God\'s response to that shame using Romans 10:11.', entry_type: 'spiritual' },
      affirmation: 'I will never be put to shame. Shame has no authority over my identity in Christ.',
    },
    {
      day: 24, week: 4, title: 'Freedom from Fear',
      bible: { book: '2 Timothy', chapter: 1, verse_range: '7',
        key_verse: '"For God didn\'t give us a spirit of fear, but of power, love, and self-control." — 2 Timothy 1:7',
        devotion: 'Fear is not from God. Read that again. The spirit of timidity, of shrinking back, of playing small — that is not the Spirit you were given. You were given power, love, and a sound mind. Fear may knock on your door, but you don\'t have to invite it in.',
        reflection_q: 'What fear has been holding you back from stepping into what God has called you to? What would courage look like today?',
      },
      journal: { prompt: 'Name your three biggest fears. Beside each one, write what God\'s Spirit gives you instead (power, love, self-discipline).', entry_type: 'spiritual' },
      affirmation: 'God has not given me a spirit of fear. I have power, love, and a sound mind. I move forward in courage.',
    },
    {
      day: 25, week: 4, title: 'Freedom to Fail',
      bible: { book: 'Proverbs', chapter: 24, verse_range: '16',
        key_verse: '"For a righteous man falls seven times, and rises up again." — Proverbs 24:16',
        devotion: 'Freedom in Christ includes the freedom to fail. Not permission to sin, but permission to be human. You will stumble. You will have bad days. And every single time, grace catches you and says: "Get up. We\'re not done." The righteous are not defined by their falls. They are defined by their rising.',
        reflection_q: 'How would your approach to growth change if you gave yourself permission to fail and get back up without self-condemnation?',
      },
      journal: { prompt: 'Write about a recent failure. Now rewrite the story from grace\'s perspective — not minimizing what happened, but showing how God redeems it.', entry_type: 'spiritual' },
      affirmation: 'I have freedom to fail and freedom to rise. My falls do not define me — my rising does.',
    },
    {
      day: 26, week: 4, title: 'Living Generously',
      bible: { book: 'Matthew', chapter: 10, verse_range: '8',
        key_verse: '"Freely you received; freely give." — Matthew 10:8',
        devotion: 'Grace was never meant to stop with you. You received it freely — now pour it out freely. Forgive lavishly. Love extravagantly. Give grace to the people who haven\'t earned it, just like it was given to you. This is how the Kingdom spreads — one act of undeserved love at a time.',
        reflection_q: 'Who in your life needs to receive the grace that God has given you? How can you extend it to them today?',
      },
      journal: { prompt: 'Plan one concrete act of grace you will extend this week — forgiving someone, encouraging someone, or serving someone who doesn\'t expect it.', entry_type: 'general' },
      affirmation: 'I have freely received grace, and I freely give it. I am a channel of God\'s love to the world around me.',
    },
    {
      day: 27, week: 4, title: 'Walking in the Light',
      bible: { book: '1 John', chapter: 1, verse_range: '7–9',
        key_verse: '"If we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus purifies us from all sin." — 1 John 1:7',
        devotion: 'Walking in the light doesn\'t mean being perfect. It means being honest. It means no more hiding, no more pretending, no more performing. When you walk in the light — with God and with others — something beautiful happens: real fellowship, real connection, real freedom.',
        reflection_q: 'What are you keeping in the dark that needs to be brought into the light? What would honest community look like for you?',
      },
      journal: { prompt: 'Write about one thing you\'ve been hiding — from God, from yourself, or from others. Then write what it would look like to bring it into the light.', entry_type: 'spiritual' },
      affirmation: 'I walk in the light. I have nothing to hide because I have nothing to prove. I am free to be honest and fully known.',
    },
    {
      day: 28, week: 4, title: 'Sent in Grace',
      bible: { book: '2 Corinthians', chapter: 5, verse_range: '18–20',
        key_verse: '"We are therefore Christ\'s ambassadors, as though God were making his appeal through us." — 2 Corinthians 5:20',
        devotion: 'You began this journey receiving grace. You end it being sent in grace. You are now an ambassador — someone who represents the King in foreign territory. Every interaction is an opportunity to show the world what grace looks like. You\'ve been restored. Now go restore others. This is your calling. This is your purpose. This is your freedom.',
        reflection_q: 'How has this 28-day journey changed the way you see yourself, God, and others? What will you carry forward?',
      },
      journal: { prompt: 'Write your final reflection. What has God done in you over these 4 weeks? What are you taking with you? What are you leaving behind? How will you live differently from this point forward?', entry_type: 'weekly_reflection' },
      affirmation: 'I am an ambassador of grace. I have been restored, and now I carry restoration wherever I go. I am free. I am loved. I am sent.',
    },
  ],
};
