export const GROWTH_SPRINT_PLAN = {
  id: 'growth-sprint',
  title: 'Growth Sprint',
  subtitle: '6 Weeks to Rapid Transformation',
  description: 'Fast-track your personal development in 6 intensive weeks.',
  weeks: 6,
  comingSoon: true,
  days_total: 42,
  difficulty: 'Intermediate',
  gradient: 'from-[#FF9FF3] to-[#54A0FF]',
  accent: '#54A0FF',
  cover_emoji: '🚀',
  tags: ['Personal', 'Growth', 'Development'],
  category: 'personal',
  week_themes: [],
  days: Array.from({ length: 42 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Accelerating Your Growth',
    bible: { book: 'Proverbs', chapter: 9, verse_range: '9', key_verse: 'Growth comes through wisdom' },
    workout: { premade_id: 'hiit-30', motivational_tip: 'Push yourself', coach_note: 'Growth happens at the edge' },
    nutrition: { focus: 'Energy', meal_theme: 'Performance', plan: 'Fuel growth', tip: 'Eat strategically', recipe_search: 'power meals' },
    journal: { prompt: 'How are you growing?', entry_type: 'general' },
    affirmation: 'I am growing and transforming',
    personal_growth_page: 'GrowthPathwaysPage',
    personal_growth_label: 'Growth',
  })),
};