export const MIND_RENEWAL_PLAN = {
  id: 'mind-renewal',
  title: 'Mind Renewal',
  subtitle: '8 Weeks to Mental Clarity',
  description: 'Renew your mind and transform your thinking patterns.',
  weeks: 8,
  days_total: 56,
  difficulty: 'All Levels',
  gradient: 'from-[#00D2D3] to-[#54A0FF]',
  accent: '#00D2D3',
  cover_emoji: '🧠',
  tags: ['Mindset', 'Mental Health', 'Clarity'],
  category: 'personal',
  week_themes: [],
  days: Array.from({ length: 56 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Renewing Your Mind',
    bible: { book: 'Philippians', chapter: 4, verse_range: '8', key_verse: 'Whatever is true, think on these things' },
    workout: { premade_id: 'meditation-flow', motivational_tip: 'Clear your mind', coach_note: 'Movement brings clarity' },
    nutrition: { focus: 'Brain Health', meal_theme: 'Clarity', plan: 'Feed your mind', tip: 'Omega-3s for clarity', recipe_search: 'brain foods' },
    journal: { prompt: 'What thoughts are you renewing?', entry_type: 'mindset_reset' },
    affirmation: 'My mind is renewed and clear',
    personal_growth_page: 'MindsetResetPage',
    personal_growth_label: 'Mindset',
  })),
};