export const NOURISH_THRIVE_PLAN = {
  id: 'nourish-thrive',
  title: 'Nourish & Thrive',
  subtitle: '8 Weeks to Nutritional Mastery',
  description: 'Master nutrition and transform your relationship with food.',
  weeks: 8,
  days_total: 56,
  difficulty: 'All Levels',
  gradient: 'from-[#6BCB77] to-[#FFD93D]',
  accent: '#6BCB77',
  cover_emoji: '🥗',
  tags: ['Nutrition', 'Wellness', 'Food'],
  category: 'nutrition',
  week_themes: [],
  days: Array.from({ length: 56 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Nourishing Your Body',
    bible: { book: 'Proverbs', chapter: 27, verse_range: '12', key_verse: 'The wise eat to live' },
    workout: { premade_id: 'yoga-flow', motivational_tip: 'Nourish yourself', coach_note: 'Food is medicine' },
    nutrition: { focus: 'Balance', meal_theme: 'Wellness', plan: 'Eat mindfully', tip: 'Listen to your body', recipe_search: 'healthy recipes' },
    journal: { prompt: 'What does nourishment mean to you?', entry_type: 'general' },
    affirmation: 'I nourish my body with intention',
    personal_growth_page: 'Nutrition',
    personal_growth_label: 'Nutrition',
  })),
};