export const POWER_PURPOSE_PLAN = {
  id: 'power-purpose',
  title: 'Power & Purpose',
  subtitle: '6 Weeks to Athletic Excellence',
  description: 'Build strength, speed, and purpose through intentional training.',
  weeks: 6,
  comingSoon: true,
  days_total: 42,
  difficulty: 'Intermediate',
  gradient: 'from-[#FF6B6B] to-[#FFD93D]',
  accent: '#FFD93D',
  cover_emoji: '💪',
  tags: ['Fitness', 'Strength', 'Performance'],
  category: 'fitness',
  week_themes: [],
  days: Array.from({ length: 42 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Building Strength',
    bible: { book: 'Psalm', chapter: 27, verse_range: '1', key_verse: 'The Lord is my strength' },
    workout: { premade_id: 'strength-circuit', motivational_tip: 'You are stronger than you know', coach_note: 'Focus on consistency' },
    nutrition: { focus: 'Protein', meal_theme: 'Power', plan: 'Eat for strength', tip: 'Fuel your body well', recipe_search: 'protein meals' },
    journal: { prompt: 'How are you building strength?', entry_type: 'general' },
    affirmation: 'I am strong and purposeful',
    personal_growth_page: 'HabitBuilderPage',
    personal_growth_label: 'Habit Builder',
  })),
};