export const SACRED_KITCHEN_PLAN = {
  id: 'sacred-kitchen',
  title: 'Sacred Kitchen',
  subtitle: '6 Weeks to Conscious Cooking',
  description: 'Transform cooking into a spiritual practice and healing art.',
  weeks: 6,
  comingSoon: true,
  days_total: 42,
  difficulty: 'All Levels',
  gradient: 'from-[#FFB347] to-[#6BCB77]',
  accent: '#FFB347',
  cover_emoji: '🍳',
  tags: ['Nutrition', 'Cooking', 'Wellness'],
  category: 'nutrition',
  week_themes: [],
  days: Array.from({ length: 42 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Sacred Cooking',
    bible: { book: '1 Corinthians', chapter: 10, verse_range: '31', key_verse: 'Do it all for God' },
    workout: { premade_id: 'morning-energizer', motivational_tip: 'Cook with love', coach_note: 'Cooking is wellness' },
    nutrition: { focus: 'Intention', meal_theme: 'Sacred', plan: 'Cook mindfully', tip: 'Love in every meal', recipe_search: 'mindful recipes' },
    journal: { prompt: 'What makes cooking sacred?', entry_type: 'general' },
    affirmation: 'My cooking is a gift of love',
    personal_growth_page: 'DiscoverRecipes',
    personal_growth_label: 'Recipes',
  })),
};