export const SOUL_DEEP_PLAN = {
  id: 'soul-deep',
  title: 'Soul Deep',
  subtitle: '8 Weeks of Spiritual Transformation',
  description: 'Go deep in spiritual growth and inner transformation.',
  weeks: 8,
  days_total: 56,
  difficulty: 'All Levels',
  gradient: 'from-[#4D96FF] to-[#A29BFE]',
  accent: '#A29BFE',
  cover_emoji: '✝️',
  tags: ['Spiritual', 'Prayer', 'Growth'],
  category: 'spiritual',
  week_themes: [],
  days: Array.from({ length: 56 }, (_, i) => ({
    day: i + 1,
    week: Math.floor(i / 7) + 1,
    title: 'Deepening Your Spiritual Life',
    bible: { book: 'Psalm', chapter: 42, verse_range: '1', key_verse: 'As the deer pants for water' },
    workout: { premade_id: 'power-yoga', motivational_tip: 'Seek God deeply', coach_note: 'Spirit guides the body' },
    nutrition: { focus: 'Clarity', meal_theme: 'Spirit', plan: 'Eat for clarity', tip: 'Fuel your soul', recipe_search: 'simple meals' },
    journal: { prompt: 'What is your spiritual journey?', entry_type: 'scripture_reflection' },
    affirmation: 'My soul is seeking God',
    personal_growth_page: 'GuidedMeditationsPage',
    personal_growth_label: 'Meditation',
  })),
};