export const CHALLENGE_SEED_KEY = 'group_challenges_seeded_v1';

const today = new Date();
const fmt = (d) => d.toISOString().split('T')[0];
const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate() + n); return x; };

export const SEED_CHALLENGES = [
  {
    title: '21-Day Prayer Streak',
    description: 'Commit to 5 minutes of intentional prayer every day for 21 days. Build the habit that changes everything else.',
    challenge_type: 'prayer',
    type: 'prayer',
    duration_days: 21,
    goal_value: 5,
    goal_unit: 'minutes',
    emoji: '🙏',
    gradient: 'from-violet-600 to-purple-400',
    is_active: true,
    status: 'active',
    participant_count: 34,
    reward_points: 210,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 21)),
    chatbot_facilitator: 'Gideon',
    daily_prompts: [
      { day: 1, prompt: "Start simple. Tell God one thing you're grateful for and one thing you need help with today." },
      { day: 2, prompt: "Pray for someone in your group by name. Ask God to bless them specifically." },
      { day: 3, prompt: "Sit in silence for 2 minutes before you pray. Let yourself arrive." },
      { day: 7, prompt: "You made it a week. Thank God for your consistency and ask Him to deepen this habit." },
      { day: 14, prompt: "Halfway there. Reflect on how your prayer life has shifted over the last two weeks." },
      { day: 21, prompt: "Final day. Write a prayer of thanksgiving for who you are becoming through this discipline." },
    ],
  },
  {
    title: '30-Day Gratitude Journal',
    description: 'Write 3 things you are genuinely thankful for every day. Science and Scripture both agree — this practice rewires your heart.',
    challenge_type: 'reading',
    type: 'reading',
    duration_days: 30,
    goal_value: 3,
    goal_unit: 'entries',
    emoji: '📝',
    gradient: 'from-amber-500 to-yellow-300',
    is_active: true,
    status: 'active',
    participant_count: 57,
    reward_points: 300,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 30)),
    chatbot_facilitator: 'Hannah',
    daily_prompts: [
      { day: 1, prompt: "Write 3 specific things you're grateful for today — be concrete, not generic." },
      { day: 5, prompt: "What's something hard that happened recently that you can find even one thing to be grateful for within it?" },
      { day: 10, prompt: "Write about a person in your life you're grateful for. What specifically have they given you?" },
      { day: 20, prompt: "Notice something small today — a moment, a sensation, a conversation — and write about why it matters." },
      { day: 30, prompt: "Final entry: What has shifted in you over 30 days of gratitude? Write freely." },
    ],
  },
  {
    title: 'Bible in 90 Days',
    description: 'Read through the entire Bible together in 90 days. ~12 pages a day. We track together, discuss weekly, and finish what we start.',
    challenge_type: 'reading',
    type: 'reading',
    duration_days: 90,
    goal_value: 12,
    goal_unit: 'pages',
    emoji: '📖',
    gradient: 'from-[#c9a227] to-[#FAD98D]',
    is_active: true,
    status: 'active',
    participant_count: 22,
    reward_points: 900,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 90)),
    chatbot_facilitator: 'Gideon',
    daily_prompts: [
      { day: 1, prompt: "Genesis 1-16 today. What struck you most about the creation account?" },
      { day: 7, prompt: "One week in. What's been the most surprising thing you've read so far?" },
      { day: 30, prompt: "You're in the Psalms. Pick one verse that hit you today and write it out." },
      { day: 60, prompt: "Now in the New Testament. How does the Old Testament feel different now that you've read it?" },
      { day: 90, prompt: "You finished the Bible. Write one thing that will stay with you forever." },
    ],
  },
  {
    title: '7-Day Digital Detox',
    description: 'Cut social media to 15 minutes or less per day for one week. Use the reclaimed time for prayer, reading, or real connection.',
    challenge_type: 'meditation',
    type: 'meditation',
    duration_days: 7,
    goal_value: 15,
    goal_unit: 'minutes max',
    emoji: '📵',
    gradient: 'from-slate-700 to-slate-500',
    is_active: true,
    status: 'active',
    participant_count: 41,
    reward_points: 70,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 7)),
    chatbot_facilitator: 'Hannah',
    daily_prompts: [
      { day: 1, prompt: "Delete the apps from your home screen today (you can re-download later). How did it feel?" },
      { day: 3, prompt: "What have you done with the time you've reclaimed? What surprised you?" },
      { day: 7, prompt: "The week is done. What do you want to carry forward? What do you want to leave behind?" },
    ],
  },
  {
    title: '14-Day Morning Devotional',
    description: 'Start every morning with 10 minutes of Scripture and reflection before touching your phone. Two weeks of intentional mornings.',
    challenge_type: 'prayer',
    type: 'prayer',
    duration_days: 14,
    goal_value: 10,
    goal_unit: 'minutes',
    emoji: '🌅',
    gradient: 'from-orange-500 to-amber-300',
    is_active: true,
    status: 'active',
    participant_count: 29,
    reward_points: 140,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 14)),
    chatbot_facilitator: 'Gideon',
    daily_prompts: [
      { day: 1, prompt: "Set your alarm 15 minutes earlier. Read Psalm 5:3. What does it mean to bring your requests before God in the morning?" },
      { day: 7, prompt: "One week in. Is this getting easier or harder? What does that tell you?" },
      { day: 14, prompt: "Last morning. How has starting your day differently changed the rest of your day?" },
    ],
  },
  {
    title: '30-Day Fitness Commitment',
    description: 'Move your body intentionally every single day for 30 days. Even 20 minutes counts. This is about building the discipline, not perfection.',
    challenge_type: 'workouts',
    type: 'workouts',
    duration_days: 30,
    goal_value: 20,
    goal_unit: 'minutes',
    emoji: '💪',
    gradient: 'from-[#0A1A2F] to-[#3C4E53]',
    is_active: true,
    status: 'active',
    participant_count: 63,
    reward_points: 300,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 30)),
    chatbot_facilitator: 'CoachDavid',
    daily_prompts: [
      { day: 1, prompt: "Today is about showing up, not performance. What does your body need right now?" },
      { day: 10, prompt: "Ten days in. What has been your biggest obstacle? How have you overcome it?" },
      { day: 20, prompt: "You're two-thirds of the way there. How do you feel compared to day 1?" },
      { day: 30, prompt: "You did it. What does this 30 days prove to you about yourself?" },
    ],
  },
  {
    title: '21-Day Acts of Service',
    description: 'One intentional act of kindness or service each day for 21 days. Log what you did. Be specific. Watch your heart change.',
    challenge_type: 'custom',
    type: 'custom',
    duration_days: 21,
    goal_value: 1,
    goal_unit: 'act per day',
    emoji: '🤝',
    gradient: 'from-emerald-600 to-green-400',
    is_active: true,
    status: 'active',
    participant_count: 18,
    reward_points: 210,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 21)),
    chatbot_facilitator: 'Hannah',
    daily_prompts: [
      { day: 1, prompt: "Start close. Do something kind for someone you live with or see every day." },
      { day: 7, prompt: "Serve a stranger today. Someone you'll never see again." },
      { day: 14, prompt: "Serve someone who can't repay you. How does that feel different?" },
      { day: 21, prompt: "Final day. Which act of service surprised you the most — in terms of what it did for you?" },
    ],
  },
  {
    title: '10-Day Clean Eating Reset',
    description: 'Ten days of whole foods, no processed sugar, and intentional hydration. Treating your body as the temple it is.',
    challenge_type: 'water_intake',
    type: 'water_intake',
    duration_days: 10,
    goal_value: 8,
    goal_unit: 'glasses',
    emoji: '🥗',
    gradient: 'from-lime-600 to-green-300',
    is_active: true,
    status: 'active',
    participant_count: 45,
    reward_points: 100,
    start_date: fmt(today),
    end_date: fmt(addDays(today, 10)),
    chatbot_facilitator: 'ChefDaniel',
    daily_prompts: [
      { day: 1, prompt: "Clear your pantry of the biggest offenders. What's hardest for you to give up?" },
      { day: 5, prompt: "Halfway point. How is your energy, sleep, or mood different?" },
      { day: 10, prompt: "Ten days done. What did you learn about your relationship with food?" },
    ],
  },
];
