// Seed data for health-condition recipes.
// Each recipe has health_conditions: string[] for filtering.

export const HEALTH_CONDITIONS = [
  {
    id: 'diabetes',
    label: 'Diabetes',
    emoji: '🩸',
    color: 'bg-[#AFC7E3]/20 text-[#3C4E53]',
    description: 'Low glycemic index, complex carbs, balanced macros',
  },
  {
    id: 'hypertension',
    label: 'High Blood Pressure',
    emoji: '❤️',
    color: 'bg-red-50 text-red-700',
    description: 'Low sodium, rich in potassium and magnesium',
  },
  {
    id: 'heart_health',
    label: 'Heart Health',
    emoji: '🫀',
    color: 'bg-pink-50 text-pink-700',
    description: 'Omega-3s, low saturated fat, high fiber',
  },
  {
    id: 'anti_inflammatory',
    label: 'Anti-Inflammatory',
    emoji: '🌿',
    color: 'bg-[#FAD98D]/25 text-[#c9a227]',
    description: 'Turmeric, ginger, antioxidant-rich foods',
  },
  {
    id: 'kidney_health',
    label: 'Kidney Health',
    emoji: '🫘',
    color: 'bg-purple-50 text-purple-700',
    description: 'Low phosphorus, controlled potassium & protein',
  },
  {
    id: 'high_cholesterol',
    label: 'High Cholesterol',
    emoji: '🫁',
    color: 'bg-orange-50 text-orange-700',
    description: 'Soluble fiber, plant sterols, healthy fats',
  },
  {
    id: 'gut_health',
    label: 'Gut Health / IBS',
    emoji: '🦠',
    color: 'bg-green-50 text-green-700',
    description: 'Probiotics, prebiotics, low-FODMAP options',
  },
  {
    id: 'thyroid',
    label: 'Thyroid Support',
    emoji: '🦋',
    color: 'bg-[#D9B878]/20 text-[#0A1A2F]/70',
    description: 'Selenium, iodine, antioxidant-rich',
  },
  {
    id: 'bone_health',
    label: 'Bone & Joint Health',
    emoji: '🦴',
    color: 'bg-[#AFC7E3]/15 text-[#3C4E53]',
    description: 'Calcium, vitamin D, collagen-supporting foods',
  },
  {
    id: 'weight_management',
    label: 'Weight Management',
    emoji: '⚖️',
    color: 'bg-[#FAD98D]/15 text-[#c9a227]',
    description: 'Calorie-conscious, high satiety, lean protein',
  },
];

// Flat seed list — 5 recipes per condition = 50 recipes total
export const SEED_RECIPES = [

  // ── DIABETES ──────────────────────────────────────────────────────────────
  {
    title: 'Cauliflower Fried Rice',
    description: 'A low-carb twist on classic fried rice using riced cauliflower packed with vegetables and lean protein.',
    category: 'dinner', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 15, servings: 4, serving_size: '1.5 cups',
    calories: 210, protein: 16, carbs: 14, fat: 9, fiber: 5, sodium: 480,
    health_conditions: ['diabetes', 'weight_management'],
    ingredients: ['1 medium cauliflower head, riced','2 eggs, beaten','1 cup frozen peas and carrots','½ cup diced onion','3 garlic cloves, minced','3 tbsp low-sodium soy sauce','1 tbsp sesame oil','2 tsp fresh ginger, grated','1 cup cooked shrimp or chicken (optional)','2 green onions, sliced'],
    instructions: [
      'Rice cauliflower in a food processor or by hand using a grater until it resembles rice grains. Spread on paper towels and press to remove excess moisture — this is critical for a non-soggy result.',
      'Heat sesame oil in a large wok or skillet over high heat until shimmering, about 375°F. Add onion and cook 3 minutes until softened.',
      'Add garlic and ginger; stir-fry 60 seconds until fragrant.',
      'Add frozen peas and carrots; cook 2 minutes, stirring constantly.',
      'Push vegetables to the side. Pour beaten eggs into the cleared space; scramble until just set, about 90 seconds, then fold into vegetables.',
      'Add cauliflower rice. Stir-fry over high heat 5–6 minutes, tossing frequently, until the cauliflower is tender but still has a slight bite.',
      'Drizzle soy sauce over the rice; toss to coat evenly. Add cooked protein if using. Cook 1 minute more.',
      'Serve topped with sliced green onions.',
    ],
    cooking_tips: ['Removing moisture from cauliflower prevents steaming and ensures a fried texture.','High heat and quick tossing are the secrets to restaurant-style fried rice.','Use coconut aminos instead of soy sauce for a lower-sodium option.'],
    serving_suggestions: 'Serve immediately in warmed bowls. Pairs well with a side of steamed edamame. Leftover rice reheats well in a dry skillet.',
    is_shared: true,
  },
  {
    title: 'Lentil & Spinach Soup',
    description: 'A fiber-rich, slow-digesting soup that helps stabilize blood sugar throughout the day.',
    category: 'lunch', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 35, servings: 6, serving_size: '1.5 cups',
    calories: 245, protein: 14, carbs: 38, fat: 4, fiber: 14, sodium: 390,
    health_conditions: ['diabetes', 'heart_health', 'high_cholesterol'],
    ingredients: ['2 cups green or brown lentils, rinsed','1 large onion, diced','4 garlic cloves, minced','2 medium carrots, diced','3 stalks celery, diced','4 cups baby spinach','1 can (14 oz) diced tomatoes, no salt added','6 cups low-sodium vegetable broth','1 tsp cumin','1 tsp smoked paprika','½ tsp turmeric','Juice of 1 lemon','2 tbsp olive oil','Salt and pepper to taste'],
    instructions: [
      'Heat olive oil in a large pot over medium heat. Add onion and cook 5 minutes until softened and golden.',
      'Add garlic, cumin, paprika, and turmeric; stir 1–2 minutes until fragrant.',
      'Add carrots and celery; cook 3 minutes, stirring occasionally.',
      'Add lentils, diced tomatoes, and broth. Bring to a boil over high heat.',
      'Reduce heat to medium-low; simmer uncovered 25–30 minutes until lentils are completely tender and starting to break down.',
      'Use the back of a spoon or an immersion blender to partially mash about one-third of the soup — this thickens the base while keeping texture.',
      'Stir in spinach and cook 2 minutes until wilted.',
      'Add lemon juice; taste and adjust seasoning. The lemon brightens all the flavors.',
    ],
    cooking_tips: ['Green lentils hold their shape better; red lentils create a creamier, thicker soup.','This soup thickens overnight — add a splash of broth when reheating.','The lemon juice is non-negotiable; it transforms the flavor entirely.'],
    serving_suggestions: 'Serve with a slice of whole grain bread. Garnish with a drizzle of olive oil and fresh parsley. Freezes beautifully for up to 3 months.',
    is_shared: true,
  },
  {
    title: 'Baked Salmon with Asparagus',
    description: 'Omega-3 rich salmon paired with fiber-filled asparagus — a blood sugar-friendly one-pan dinner.',
    category: 'dinner', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 8, cook_time_minutes: 20, servings: 2, serving_size: '1 fillet + 8 spears',
    calories: 380, protein: 42, carbs: 10, fat: 18, fiber: 4, sodium: 340,
    health_conditions: ['diabetes', 'heart_health', 'anti_inflammatory'],
    ingredients: ['2 salmon fillets (6 oz each)','1 bunch asparagus, trimmed','2 tbsp olive oil','3 garlic cloves, minced','1 lemon, sliced','1 tsp dried dill','1 tsp smoked paprika','Salt and black pepper to taste','Fresh parsley for garnish'],
    instructions: [
      'Preheat oven to 400°F. Line a large baking sheet with parchment paper.',
      'Arrange asparagus spears in a single layer on one side of the pan. Drizzle with 1 tbsp olive oil, season with salt and pepper, and toss to coat.',
      'Pat salmon fillets completely dry with paper towels — this ensures a better crust. Place on the other side of the pan.',
      'Mix remaining olive oil with minced garlic, paprika, and dill. Brush generously over both sides of the salmon.',
      'Arrange lemon slices over and around the salmon. Season with salt and pepper.',
      'Roast 15–18 minutes until salmon flakes easily with a fork and reaches an internal temperature of 145°F. The asparagus should be tender with lightly charred tips.',
      'Remove from oven; rest 2 minutes. Garnish with fresh parsley.',
    ],
    cooking_tips: ['Dry salmon = better browning. Always pat fillets dry before seasoning.','Thick fillets (1 inch) need closer to 20 minutes; thinner fillets may be done at 13 minutes.','The asparagus will cook faster than the salmon — if the asparagus is thin, add it halfway through cooking.'],
    serving_suggestions: 'Serve over ½ cup cooked quinoa or with a small side of brown rice for a complete, balanced plate.',
    is_shared: true,
  },
  {
    title: 'Cinnamon Almond Overnight Oats',
    description: 'Slow-release oats with blood sugar-stabilizing cinnamon and healthy fats from almonds — a perfect diabetic-friendly breakfast.',
    category: 'breakfast', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 0, servings: 1, serving_size: '1 jar (about 1.5 cups)',
    calories: 340, protein: 14, carbs: 42, fat: 13, fiber: 8, sodium: 110,
    health_conditions: ['diabetes', 'heart_health'],
    ingredients: ['½ cup rolled oats (not instant)','¾ cup unsweetened almond milk','¼ cup plain Greek yogurt','1 tbsp chia seeds','1 tbsp almond butter','1 tsp cinnamon','½ tsp vanilla extract','1 tsp honey or stevia to taste','¼ cup fresh berries for topping','1 tbsp sliced almonds'],
    instructions: [
      'In a jar or container with a lid, add oats, chia seeds, and cinnamon. Stir to combine dry ingredients.',
      'Add almond milk, Greek yogurt, almond butter, and vanilla. Stir thoroughly until almond butter is fully mixed in.',
      'Taste and adjust sweetness with honey or stevia.',
      'Seal the container and refrigerate for at least 6 hours or overnight. The oats and chia seeds will absorb the liquid and thicken considerably.',
      'In the morning, stir the oats — they should be thick and creamy. If too thick, add a splash of almond milk.',
      'Top with fresh berries and sliced almonds just before eating.',
    ],
    cooking_tips: ['Rolled oats have a lower glycemic index than instant oats — always use rolled.','Cinnamon improves insulin sensitivity — do not skip it.','Prep 5 jars on Sunday for a full week of breakfasts.'],
    serving_suggestions: 'Eat cold from the fridge. Excellent paired with a hard-boiled egg for additional protein.',
    is_shared: true,
  },
  {
    title: 'Turkey & Vegetable Stuffed Bell Peppers',
    description: 'Lean ground turkey and vegetables in a bell pepper shell — high protein, low carb, and visually impressive.',
    category: 'dinner', diet_type: 'any', difficulty: 'medium',
    prep_time_minutes: 15, cook_time_minutes: 35, servings: 4, serving_size: '1 stuffed pepper',
    calories: 295, protein: 28, carbs: 22, fat: 10, fiber: 5, sodium: 420,
    health_conditions: ['diabetes', 'weight_management', 'high_cholesterol'],
    ingredients: ['4 large bell peppers (any color), tops cut off and seeds removed','1 lb lean ground turkey (93% lean)','1 cup cauliflower rice or cooked brown rice','1 can (14 oz) diced tomatoes, drained','1 cup diced zucchini','½ cup diced onion','3 garlic cloves, minced','1 tsp Italian seasoning','1 tsp cumin','½ cup low-sodium chicken broth','¼ cup shredded mozzarella (optional)'],
    instructions: [
      'Preheat oven to 375°F. Lightly oil a baking dish just large enough to hold the peppers upright.',
      'Blanch peppers: submerge in boiling water for 3 minutes, then transfer to ice water to stop cooking. Pat dry. This softens them slightly so they cook evenly in the oven.',
      'Cook ground turkey in a skillet over medium-high heat, breaking apart, until no pink remains, about 7 minutes. Drain any excess fat.',
      'Add onion and garlic to the same pan; cook 3 minutes. Add zucchini; cook 2 more minutes.',
      'Stir in diced tomatoes, cauliflower rice, Italian seasoning, and cumin. Add broth and simmer 5 minutes until most liquid is absorbed.',
      'Stand peppers in the prepared baking dish. Spoon filling generously into each, pressing down to pack tightly. Mound extra filling on top.',
      'Top each pepper with mozzarella if using. Cover dish with foil.',
      'Bake 20 minutes covered, then uncover and bake 10 more minutes until peppers are tender and tops are golden.',
    ],
    cooking_tips: ['Blanching the peppers first prevents that raw, crunchy texture.','Cauliflower rice keeps this very low-carb; swap for brown rice for more fiber.','These reheat beautifully — make extra for lunch the next day.'],
    serving_suggestions: 'Serve with a simple green salad dressed with lemon and olive oil. A dollop of plain Greek yogurt makes a great sour cream substitute.',
    is_shared: true,
  },

  // ── HIGH BLOOD PRESSURE ───────────────────────────────────────────────────
  {
    title: 'DASH Diet Grain Bowl',
    description: 'A potassium and magnesium-packed grain bowl following DASH diet principles — naturally supports healthy blood pressure.',
    category: 'lunch', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 15, cook_time_minutes: 20, servings: 2, serving_size: '1 bowl',
    calories: 420, protein: 18, carbs: 58, fat: 14, fiber: 11, sodium: 210,
    health_conditions: ['hypertension', 'heart_health', 'high_cholesterol'],
    ingredients: ['1 cup quinoa, cooked','1 can (15 oz) chickpeas, rinsed and dried','2 cups baby spinach','1 cup cherry tomatoes, halved','1 avocado, sliced','¼ cup pumpkin seeds','2 tbsp olive oil','2 tbsp lemon juice','1 tsp garlic powder','½ tsp black pepper','Fresh herbs (parsley or cilantro)'],
    instructions: [
      'Cook quinoa according to package directions using water or unsalted broth. Fluff with a fork and season lightly with black pepper.',
      'Rinse chickpeas and pat completely dry. Toss with 1 tbsp olive oil and garlic powder. Spread in a single layer on a baking sheet.',
      'Roast chickpeas at 400°F for 20–25 minutes, shaking the pan halfway, until golden and crispy. Watch closely after 18 minutes to avoid burning.',
      'Whisk remaining olive oil with lemon juice for the dressing.',
      'Assemble bowls: start with a base of quinoa, then arrange spinach, tomatoes, avocado, and crispy chickpeas in sections.',
      'Drizzle dressing over everything. Top with pumpkin seeds and fresh herbs.',
    ],
    cooking_tips: ['Pumpkin seeds and spinach are both excellent sources of magnesium, which directly supports blood pressure regulation.','Avocado provides potassium — a critical DASH diet mineral. Eat it fresh to prevent browning.','Chickpeas can be roasted ahead of time and stored 3 days in an open container to maintain crunch.'],
    serving_suggestions: 'Best eaten fresh while chickpeas are still crispy. Serve with unsalted sparkling water with lemon for a refreshing blood pressure-friendly meal.',
    is_shared: true,
  },
  {
    title: 'Herb-Crusted Chicken Breast',
    description: 'A flavor-packed chicken dish that proves low-sodium cooking does not have to be bland.',
    category: 'dinner', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 25, servings: 4, serving_size: '1 breast',
    calories: 265, protein: 42, carbs: 3, fat: 9, fiber: 1, sodium: 185,
    health_conditions: ['hypertension', 'diabetes', 'weight_management'],
    ingredients: ['4 boneless skinless chicken breasts (6 oz each)','3 tbsp fresh rosemary, finely chopped','3 tbsp fresh thyme leaves','4 garlic cloves, minced','2 tbsp olive oil','1 tbsp lemon zest','2 tsp lemon juice','1 tsp black pepper','½ tsp onion powder'],
    instructions: [
      'Preheat oven to 425°F. Line a baking sheet with a wire rack set over parchment paper — this allows hot air to circulate under the chicken for even cooking.',
      'Pat chicken breasts completely dry. If breasts are very thick (over 1 inch), place in a zip-lock bag and pound to even thickness with a heavy pan. Even thickness = even cooking.',
      'Combine rosemary, thyme, garlic, olive oil, lemon zest, lemon juice, pepper, and onion powder in a small bowl. Mix into a paste.',
      'Rub herb paste all over both sides of each chicken breast, pressing firmly so it adheres.',
      'Place on the wire rack and roast 20–25 minutes until the internal temperature reaches 165°F. Let rest 5 minutes — this redistributes juices and keeps the chicken moist.',
      'Slice against the grain and serve.',
    ],
    cooking_tips: ['A wire rack elevates the chicken so the bottom does not steam and go soggy.','Fresh herbs are significantly more flavorful than dried here — do not substitute.','Resting is mandatory. Cutting immediately loses half the juices.'],
    serving_suggestions: 'Serve with roasted sweet potato and steamed broccoli. A squeeze of fresh lemon over the top right before serving brightens everything.',
    is_shared: true,
  },
  {
    title: 'Banana Oat Smoothie',
    description: 'A potassium-rich breakfast smoothie — banana and spinach deliver blood pressure-supporting nutrients in minutes.',
    category: 'breakfast', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 5, cook_time_minutes: 0, servings: 1, serving_size: '16 oz glass',
    calories: 285, protein: 8, carbs: 52, fat: 5, fiber: 7, sodium: 95,
    health_conditions: ['hypertension', 'heart_health'],
    ingredients: ['1 frozen banana','1 cup unsweetened almond milk','1 cup baby spinach','¼ cup rolled oats','1 tbsp ground flaxseed','1 tsp cinnamon','½ tsp vanilla extract','4–5 ice cubes'],
    instructions: [
      'Add all ingredients to blender in this order: liquid first, then soft ingredients, then frozen items on top. This order protects the blade and ensures smooth blending.',
      'Blend on high 60–90 seconds until completely smooth. If the smoothie is too thick, add a splash more almond milk and blend 10 seconds.',
      'Taste — the banana should provide enough sweetness. If needed, add ½ a pitted date.',
      'Pour immediately and drink within 15 minutes for maximum nutrient retention.',
    ],
    cooking_tips: ['Freeze bananas in advance: peel, break in half, freeze in a zip bag. Always have some ready.','Frozen banana eliminates the need for added sugar while creating a creamy, ice cream-like texture.','Ground flaxseed adds omega-3 fatty acids; whole seeds pass through undigested.'],
    serving_suggestions: 'Drink immediately for best texture. Pair with a small handful of unsalted almonds for sustained energy.',
    is_shared: true,
  },
  {
    title: 'Garlic Herb Roasted Vegetables',
    description: 'A DASH-diet staple — this potassium-rich roasted medley is endlessly customizable and naturally low in sodium.',
    category: 'dinner', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 12, cook_time_minutes: 30, servings: 4, serving_size: '1.5 cups',
    calories: 165, protein: 4, carbs: 28, fat: 6, fiber: 7, sodium: 65,
    health_conditions: ['hypertension', 'gut_health', 'bone_health'],
    ingredients: ['1 large sweet potato, cubed','2 cups broccoli florets','1 cup Brussels sprouts, halved','1 large red bell pepper, chunked','1 red onion, wedged','5 garlic cloves, smashed','2 tbsp olive oil','1 tsp rosemary','1 tsp thyme','½ tsp black pepper','Fresh parsley to finish'],
    instructions: [
      'Preheat oven to 425°F. Line two baking sheets with parchment paper. Using two sheets keeps vegetables in a single layer — this roasts them, not steams them.',
      'Cut all vegetables to roughly the same size (about 1-inch pieces) so they cook at the same rate.',
      'Toss sweet potato and Brussels sprouts with half the oil, rosemary, and thyme. Spread on first sheet.',
      'Toss broccoli, bell pepper, onion, and garlic with remaining oil. Spread on second sheet.',
      'Season both sheets generously with black pepper.',
      'Roast 25–30 minutes total. After 15 minutes, rotate both pans and flip vegetables using tongs. They should be golden-brown on the contact sides.',
      'Combine all vegetables on one sheet for the last 5 minutes. Finish with fresh parsley.',
    ],
    cooking_tips: ['Overcrowding is the enemy of roasted vegetables — they steam instead of roast. Always use two pans.','Sweet potato takes longer than broccoli; if using one pan, add broccoli halfway through.','No salt needed — the roasting process intensifies natural sugars and flavors.'],
    serving_suggestions: 'Serve as a side with grilled chicken or fish. Leftovers are excellent tossed with whole grain pasta and a drizzle of olive oil.',
    is_shared: true,
  },
  {
    title: 'Sardine & Tomato Toast',
    description: 'Sardines are one of the highest dietary sources of omega-3s and calcium — this quick meal punches above its weight nutritionally.',
    category: 'lunch', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 5, cook_time_minutes: 0, servings: 1, serving_size: '2 slices',
    calories: 310, protein: 26, carbs: 28, fat: 11, fiber: 4, sodium: 320,
    health_conditions: ['hypertension', 'heart_health', 'bone_health'],
    ingredients: ['1 can sardines in olive oil, drained','2 slices whole grain bread, toasted','2 tbsp Greek yogurt or light cream cheese','1 medium tomato, sliced','¼ red onion, thinly sliced','1 tbsp capers, rinsed','Fresh lemon juice','Black pepper to taste','Fresh dill or parsley'],
    instructions: [
      'Toast bread until deeply golden and sturdy enough to support toppings.',
      'Spread Greek yogurt or cream cheese on each slice. It acts as a creamy base and adds extra protein.',
      'Arrange sliced tomatoes over the spread, slightly overlapping.',
      'Break sardines into large pieces with a fork. Distribute evenly over tomatoes.',
      'Top with red onion slices and capers.',
      'Squeeze fresh lemon juice over everything, add black pepper, and garnish with dill or parsley. Serve immediately.',
    ],
    cooking_tips: ['Rinsing capers removes about 40% of their sodium.','Sardines packed in olive oil have a milder flavor than those in water.','This assembly takes 5 minutes — have sardine cans stocked as pantry essentials.'],
    serving_suggestions: 'Serve with a side salad of arugula dressed with lemon and olive oil. A glass of water with sliced cucumber is an excellent pairing.',
    is_shared: true,
  },

  // ── HEART HEALTH ──────────────────────────────────────────────────────────
  {
    title: 'Walnut & Berry Overnight Oats',
    description: 'Walnuts provide ALA omega-3s while berries deliver anthocyanins — a powerful heart-protective breakfast.',
    category: 'breakfast', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 8, cook_time_minutes: 0, servings: 1, serving_size: '1 jar',
    calories: 390, protein: 15, carbs: 48, fat: 17, fiber: 9, sodium: 95,
    health_conditions: ['heart_health', 'high_cholesterol', 'anti_inflammatory'],
    ingredients: ['½ cup rolled oats','¾ cup unsweetened oat milk','¼ cup plain Greek yogurt','¼ cup mixed frozen berries','¼ cup walnuts, roughly chopped','1 tbsp ground flaxseed','1 tsp cinnamon','½ tsp vanilla extract'],
    instructions: [
      'Combine oats, flaxseed, and cinnamon in a mason jar. Stir dry ingredients together.',
      'Add oat milk, Greek yogurt, and vanilla. Stir thoroughly.',
      'Gently fold in frozen berries (they will thaw overnight and create a natural fruit compote).',
      'Top with chopped walnuts.',
      'Seal and refrigerate at least 6 hours or overnight.',
      'Stir in the morning. The oats should be thick and creamy with a beautiful berry swirl throughout. Add a splash of oat milk if you prefer a thinner consistency.',
    ],
    cooking_tips: ['Ground flaxseed is far more bioavailable than whole seeds — always use ground.','Walnuts are the only nut with significant ALA omega-3s; do not substitute with other nuts for heart health benefits.','Frozen berries release more juice than fresh, creating a more vibrant, flavorful result.'],
    serving_suggestions: 'Eat straight from the jar. Excellent as a meal-prep option — prep 3–4 jars at once.',
    is_shared: true,
  },
  {
    title: 'Mediterranean Baked Cod',
    description: 'Lean white fish baked with olive oil, tomatoes, and olives in the Mediterranean tradition — proven heart-healthy.',
    category: 'dinner', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 20, servings: 4, serving_size: '1 fillet',
    calories: 285, protein: 36, carbs: 12, fat: 11, fiber: 3, sodium: 390,
    health_conditions: ['heart_health', 'hypertension', 'anti_inflammatory'],
    ingredients: ['4 cod fillets (6 oz each)','1 can (14 oz) cherry tomatoes or diced tomatoes','¼ cup kalamata olives, pitted and halved','3 garlic cloves, minced','2 tbsp olive oil','1 lemon, half juiced, half sliced','1 tsp dried oregano','½ tsp red pepper flakes','Fresh parsley and basil to serve'],
    instructions: [
      'Preheat oven to 400°F.',
      'Heat 1 tbsp olive oil in an oven-safe skillet over medium heat. Add garlic and red pepper flakes; cook 60 seconds.',
      'Add tomatoes and olives; simmer 5 minutes until tomatoes soften and release their juices. Season with oregano.',
      'Pat cod fillets completely dry. Season with pepper only (no salt — olives and tomatoes provide plenty of sodium).',
      'Nestle cod fillets into the tomato mixture. Drizzle remaining olive oil and lemon juice over the fish. Top with lemon slices.',
      'Transfer the skillet to the oven and bake 12–15 minutes until cod is opaque and flakes easily with a fork. It should reach 145°F internally.',
      'Garnish generously with fresh parsley and basil. Serve directly from the skillet.',
    ],
    cooking_tips: ['Patting fish dry before cooking prevents it from steaming in its own moisture.','Cod is done when it turns from translucent to opaque and begins to flake at the edges.','The one-pan approach means the fish absorbs all the Mediterranean flavors as it bakes.'],
    serving_suggestions: 'Serve over a bed of wilted spinach or alongside whole wheat couscous to soak up the sauce. Crusty whole grain bread works too.',
    is_shared: true,
  },

  // ── ANTI-INFLAMMATORY ─────────────────────────────────────────────────────
  {
    title: 'Golden Turmeric Chicken Soup',
    description: 'Turmeric and ginger combine for a powerful anti-inflammatory meal that also comforts the soul.',
    category: 'lunch', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 15, cook_time_minutes: 30, servings: 6, serving_size: '1.5 cups',
    calories: 310, protein: 30, carbs: 24, fat: 9, fiber: 4, sodium: 420,
    health_conditions: ['anti_inflammatory', 'gut_health', 'thyroid'],
    ingredients: ['1.5 lbs boneless chicken breast or thighs','2 tbsp coconut oil or olive oil','1 large onion, diced','5 garlic cloves, minced','2 tbsp fresh ginger, grated','2 tsp turmeric','1 tsp cumin','½ tsp black pepper (activates curcumin in turmeric)','4 cups low-sodium chicken broth','1 can (14 oz) coconut milk, full-fat','2 medium carrots, sliced','2 cups sweet potato, cubed','2 cups kale, stems removed, torn','Juice of 1 lime'],
    instructions: [
      'Heat oil in a large pot over medium heat. Add onion; cook 5 minutes until softened.',
      'Add garlic, ginger, turmeric, cumin, and black pepper. Stir constantly for 2 minutes — the spices will become fragrant and slightly darker.',
      'Add chicken to the pot whole (it will shred later). Pour in broth and coconut milk; stir to combine.',
      'Add carrots and sweet potato. Bring to a boil, then reduce heat to medium-low.',
      'Simmer 20 minutes until chicken is cooked through (internal temp 165°F) and sweet potato is fork-tender.',
      'Remove chicken; use two forks to shred into bite-sized pieces. Return to the pot.',
      'Add kale; cook 3 minutes until wilted but still bright green. Stir in lime juice.',
      'Taste and adjust seasoning. The soup should be warmly spiced with a golden hue.',
    ],
    cooking_tips: ['Black pepper is essential — it increases curcumin (the active compound in turmeric) absorption by 2000%.','Full-fat coconut milk creates a richer broth; light coconut milk also works.','This soup improves significantly overnight as flavors meld.'],
    serving_suggestions: 'Serve in deep bowls with a wedge of lime. A small scoop of brown rice or quinoa can be added for more substance.',
    is_shared: true,
  },
  {
    title: 'Blueberry Chia Pudding',
    description: 'Chia seeds are loaded with omega-3s and antioxidants; blueberries add anthocyanins that fight cellular inflammation.',
    category: 'snack', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 8, cook_time_minutes: 0, servings: 2, serving_size: '1 cup',
    calories: 235, protein: 7, carbs: 32, fat: 10, fiber: 12, sodium: 75,
    health_conditions: ['anti_inflammatory', 'heart_health', 'gut_health'],
    ingredients: ['¼ cup chia seeds','1.5 cups unsweetened almond milk','1 cup fresh or frozen blueberries','1 tbsp maple syrup or honey','½ tsp vanilla extract','¼ tsp cinnamon','Pinch of cardamom (optional)','Fresh blueberries and mint to top'],
    instructions: [
      'Whisk chia seeds, almond milk, maple syrup, vanilla, cinnamon, and cardamom in a bowl.',
      'Stir again after 5 minutes to prevent clumping at the bottom.',
      'Cover and refrigerate at least 4 hours or overnight. The pudding should be thick and gel-like throughout.',
      'Blend 1 cup blueberries with a splash of almond milk into a smooth compote — this creates a vibrant purple layer.',
      'Layer pudding and blueberry compote alternately in glasses or jars.',
      'Top with fresh blueberries and mint. Serve chilled.',
    ],
    cooking_tips: ['The second stir at 5 minutes is critical — chia seeds clump aggressively.','A thicker pudding uses 3 tbsp chia per cup of liquid; thinner uses 2 tbsp.','Wild blueberries contain roughly twice the antioxidants of cultivated blueberries.'],
    serving_suggestions: 'Perfect as a snack, dessert, or light breakfast. Pairs beautifully with a handful of walnuts for added omega-3s.',
    is_shared: true,
  },
  {
    title: 'Ginger Salmon Stir-Fry',
    description: 'A powerhouse of anti-inflammatory ingredients — salmon, broccoli, ginger, and garlic in a light sauce.',
    category: 'dinner', diet_type: 'any', difficulty: 'medium',
    prep_time_minutes: 15, cook_time_minutes: 15, servings: 4, serving_size: '1.5 cups',
    calories: 415, protein: 38, carbs: 22, fat: 19, fiber: 5, sodium: 440,
    health_conditions: ['anti_inflammatory', 'heart_health', 'diabetes'],
    ingredients: ['1.5 lbs salmon fillet, skin removed, cubed','3 cups broccoli florets','1 cup snap peas','1 red bell pepper, sliced','3 garlic cloves, minced','2 tbsp fresh ginger, grated','2 tbsp low-sodium soy sauce','1 tbsp sesame oil','1 tbsp rice vinegar','1 tsp honey','1 tsp cornstarch mixed with 2 tbsp water','Sesame seeds and green onion to serve'],
    instructions: [
      'Mix soy sauce, rice vinegar, honey, and cornstarch-water slurry in a small bowl. Set aside as sauce.',
      'Pat salmon cubes completely dry — essential for a sear, not a steam.',
      'Heat sesame oil in a wok over high heat until smoking, about 400°F. Add salmon in a single layer; cook without moving 2 minutes per side until golden. Remove to a plate.',
      'In the same wok, add garlic and ginger; stir 30 seconds.',
      'Add broccoli; cook 3 minutes, stirring constantly. Add snap peas and bell pepper; cook 2 more minutes — vegetables should be bright and still have crunch.',
      'Pour sauce over vegetables; stir until it thickens and coats everything, about 60 seconds.',
      'Return salmon to the wok. Toss gently to coat with sauce without breaking the pieces.',
      'Serve immediately over brown rice or cauliflower rice. Top with sesame seeds and green onion.',
    ],
    cooking_tips: ['A very hot wok is the secret to stir-fry — if it is not smoking, it is not hot enough.','Cook salmon last and return it at the end to avoid overcooking.','Mise en place is essential for stir-fry — have everything cut and ready before you start heating the pan.'],
    serving_suggestions: 'Serve over brown rice or cauliflower rice. A drizzle of chili oil for heat is a wonderful addition.',
    is_shared: true,
  },

  // ── HIGH CHOLESTEROL ──────────────────────────────────────────────────────
  {
    title: 'Steel-Cut Oat Porridge with Flaxseed',
    description: 'Beta-glucan in oats is clinically proven to lower LDL cholesterol; flaxseed adds plant-based omega-3s.',
    category: 'breakfast', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 5, cook_time_minutes: 25, servings: 2, serving_size: '1 cup',
    calories: 295, protein: 9, carbs: 52, fat: 7, fiber: 8, sodium: 40,
    health_conditions: ['high_cholesterol', 'heart_health', 'diabetes'],
    ingredients: ['1 cup steel-cut oats','3 cups water or unsweetened oat milk','2 tbsp ground flaxseed','1 large apple, diced (with skin — the skin has pectin)','1 tsp cinnamon','¼ cup walnuts, chopped','1 tbsp maple syrup or 2 Medjool dates','Pinch of salt'],
    instructions: [
      'Bring water or oat milk and a pinch of salt to a boil in a medium saucepan.',
      'Stir in steel-cut oats. Reduce heat to medium-low.',
      'Simmer uncovered 20–25 minutes, stirring every 5 minutes, until oats are creamy but still slightly chewy. Steel-cut oats have a lower glycemic index than rolled.',
      'Stir in cinnamon and ground flaxseed during the last 3 minutes of cooking.',
      'Remove from heat; let rest 3 minutes to thicken further.',
      'Top with diced apple (with skin for maximum pectin), chopped walnuts, and maple syrup.',
    ],
    cooking_tips: ['Steel-cut oats have a lower glycemic index than rolled or instant oats — always choose steel-cut for heart health.','The apple skin contains pectin, a soluble fiber that directly helps lower LDL cholesterol.','Make a large batch: refrigerate for 5 days and reheat with a splash of milk each morning.'],
    serving_suggestions: 'Serve hot. Add a tablespoon of almond butter on top for extra protein and healthy fats that further support heart health.',
    is_shared: true,
  },
  {
    title: 'Avocado & Black Bean Tacos',
    description: 'Plant sterols in avocado and soluble fiber in black beans work together to actively reduce LDL cholesterol.',
    category: 'dinner', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 15, cook_time_minutes: 10, servings: 4, serving_size: '2 tacos',
    calories: 410, protein: 14, carbs: 52, fat: 18, fiber: 14, sodium: 390,
    health_conditions: ['high_cholesterol', 'heart_health', 'gut_health'],
    ingredients: ['8 corn tortillas (6-inch)','2 cans (15 oz each) black beans, rinsed','2 ripe avocados','1 cup purple cabbage, shredded','1 cup cherry tomatoes, halved','½ red onion, finely diced','1 jalapeño, seeded and minced','Juice of 2 limes','¼ cup fresh cilantro','1 tsp cumin','1 tsp garlic powder','Salt and pepper to taste'],
    instructions: [
      'Heat black beans in a saucepan over medium heat with cumin, garlic powder, and a splash of water. Cook 5 minutes, stirring, until heated through and fragrant. Lightly mash about one-third of the beans with a fork for a creamier texture.',
      'Make quick pico: combine tomatoes, onion, jalapeño, and half the lime juice. Season and let sit 5 minutes.',
      'Mash avocados with remaining lime juice, salt, and pepper. Keep some texture — not completely smooth.',
      'Warm tortillas directly over a gas flame 20 seconds per side until charred in spots, or in a dry skillet over high heat.',
      'Assemble tacos: beans first, then avocado, cabbage, pico de gallo, and cilantro.',
      'Serve two per person with extra lime wedges.',
    ],
    cooking_tips: ['Corn tortillas have significantly more fiber and are lower glycemic than flour tortillas.','Warming tortillas directly on the flame creates flavor; wrap in foil to keep warm if serving a crowd.','Purple cabbage is high in anthocyanins — an added heart-health bonus.'],
    serving_suggestions: 'Serve with a side of sliced mango for a sweet contrast. Sparkling water with lime is the perfect beverage pairing.',
    is_shared: true,
  },

  // ── GUT HEALTH ────────────────────────────────────────────────────────────
  {
    title: 'Kefir Parfait with Prebiotics',
    description: 'Kefir contains up to 30 strains of beneficial bacteria; paired with prebiotic fiber from banana and oats for maximum gut benefit.',
    category: 'breakfast', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 8, cook_time_minutes: 0, servings: 1, serving_size: '1 jar',
    calories: 315, protein: 14, carbs: 46, fat: 8, fiber: 6, sodium: 95,
    health_conditions: ['gut_health', 'bone_health'],
    ingredients: ['¾ cup plain kefir (not flavored)','¼ cup rolled oats (raw — they feed gut bacteria as prebiotics)','1 medium banana, sliced','¼ cup fresh or frozen blueberries','2 tbsp ground flaxseed','1 tbsp honey','¼ tsp cinnamon','2 tbsp walnuts'],
    instructions: [
      'Layer kefir in the base of a jar or bowl.',
      'Sprinkle raw oats directly into the kefir — they act as a prebiotic when consumed raw.',
      'Top with banana slices and blueberries.',
      'Add ground flaxseed and walnuts.',
      'Drizzle honey and sprinkle cinnamon over everything.',
      'Eat immediately or refrigerate up to 2 hours (the oats will soften slightly in the kefir).',
    ],
    cooking_tips: ['Plain, full-fat kefir has the most probiotics; avoid flavored or low-fat versions.','Prebiotics (oats, banana) are the food that probiotics (kefir) need to thrive — always combine them.','Kefir has more diverse strains of bacteria than yogurt.'],
    serving_suggestions: 'Eat in the morning on an empty stomach for best absorption of probiotics.',
    is_shared: true,
  },
  {
    title: 'Miso Soup with Tofu & Seaweed',
    description: 'Miso is a traditional fermented food rich in beneficial bacteria and enzymes that support digestive health.',
    category: 'lunch', diet_type: 'vegan', difficulty: 'easy',
    prep_time_minutes: 8, cook_time_minutes: 10, servings: 2, serving_size: '1.5 cups',
    calories: 115, protein: 9, carbs: 10, fat: 4, fiber: 2, sodium: 580,
    health_conditions: ['gut_health', 'thyroid'],
    ingredients: ['3 cups water','2 tbsp white miso paste (shiro miso — milder)','½ cup soft tofu, cubed','2 tbsp dried wakame seaweed','2 green onions, sliced','1 tsp sesame oil','Optional: 1 sheet nori, cut into strips'],
    instructions: [
      'Soak dried wakame in a bowl of cold water for 5 minutes until rehydrated. Drain and squeeze out excess water.',
      'Heat water in a saucepan to just below boiling (about 160–170°F). Never boil miso — heat destroys the beneficial bacteria and enzymes that make it medicinal.',
      'Dissolve miso paste in ¼ cup of the hot water in a separate small bowl, whisking until smooth. No lumps.',
      'Add tofu cubes and rehydrated wakame to the hot water. Heat gently 2 minutes.',
      'Remove from heat. Stir in the dissolved miso.',
      'Ladle into bowls and top with green onions, a few drops of sesame oil, and nori strips if using.',
    ],
    cooking_tips: ['The no-boil rule is critical: boiling kills the probiotic benefit of miso entirely.','White (shiro) miso is milder and slightly sweeter than red (aka) miso — better for everyday use.','Wakame seaweed provides iodine, which is beneficial for thyroid health.'],
    serving_suggestions: 'Serve alongside brown rice and a small portion of fermented vegetables (kimchi or sauerkraut) for a gut-health focused lunch.',
    is_shared: true,
  },

  // ── KIDNEY HEALTH ─────────────────────────────────────────────────────────
  {
    title: 'White Rice Bowl with Egg & Cucumber',
    description: 'For kidney health, this low-phosphorus, low-potassium bowl provides satisfying carbs and protein without overloading the kidneys.',
    category: 'lunch', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 20, servings: 2, serving_size: '1 bowl',
    calories: 330, protein: 14, carbs: 50, fat: 8, fiber: 2, sodium: 195,
    health_conditions: ['kidney_health'],
    ingredients: ['1 cup white rice (not brown — lower phosphorus)','2 large eggs','1 medium cucumber, thinly sliced','½ cup shredded carrots','2 tbsp rice vinegar','1 tsp sesame oil','1 tsp low-sodium soy sauce','1 tsp sugar','Sesame seeds to garnish'],
    instructions: [
      'Cook white rice per package directions. White rice is significantly lower in phosphorus and potassium than brown rice — an important distinction for kidney patients.',
      'Make quick-pickled cucumber: toss sliced cucumber with rice vinegar, sugar, and a pinch of salt. Let sit 10 minutes.',
      'Soft-boil eggs: lower into gently boiling water; cook exactly 7 minutes for a jammy yolk. Transfer immediately to ice water for 2 minutes, then peel.',
      'Whisk sesame oil and soy sauce for dressing.',
      'Assemble bowls: rice base, then cucumber, carrots, and halved eggs arranged neatly.',
      'Drizzle dressing and sprinkle sesame seeds.',
    ],
    cooking_tips: ['White rice over brown is specifically recommended for kidney health due to lower phosphorus content.','Leaching vegetables: boiling potassium-high vegetables and discarding the water removes up to 50% of potassium.','Always consult your nephrologist or dietitian for personalized kidney diet guidance.'],
    serving_suggestions: 'Serve warm or at room temperature. Keep portion sizes moderate to manage protein intake.',
    is_shared: true,
  },

  // ── BONE HEALTH ───────────────────────────────────────────────────────────
  {
    title: 'Sardine & Kale Caesar Salad',
    description: 'Sardines provide calcium and vitamin D; kale is one of the richest plant sources of vitamin K for bone density.',
    category: 'lunch', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 15, cook_time_minutes: 0, servings: 2, serving_size: '2 cups',
    calories: 355, protein: 28, carbs: 18, fat: 20, fiber: 4, sodium: 480,
    health_conditions: ['bone_health', 'heart_health', 'hypertension'],
    ingredients: ['2 cans sardines in olive oil, drained','4 cups curly kale, massaged and torn','2 slices whole grain bread for croutons','3 tbsp olive oil','2 tbsp lemon juice','1 garlic clove, minced','2 tsp Dijon mustard','2 tbsp plain Greek yogurt (lightens the dressing)','2 tbsp Parmesan, finely grated','Black pepper to taste'],
    instructions: [
      'Make yogurt Caesar dressing: whisk Greek yogurt, lemon juice, minced garlic, Dijon, 2 tbsp olive oil, half the Parmesan, and black pepper until smooth.',
      'Massage kale: drizzle 1 tsp olive oil over kale and massage with hands for 2 minutes until leaves darken, soften, and reduce in size by half. This breaks down tough fibers and makes kale more digestible.',
      'Make croutons: cube bread, toss with remaining olive oil, and bake at 375°F for 12 minutes until golden and crunchy.',
      'Toss massaged kale with dressing until well coated.',
      'Add croutons and remaining Parmesan; toss again.',
      'Top with sardine fillets arranged on top. Serve immediately.',
    ],
    cooking_tips: ['Massaging kale is not optional — unmassaged kale is tough and bitter.','Sardines are one of the only dietary sources of both calcium and vitamin D together — a rare combination.','Greek yogurt in the dressing cuts calories while maintaining creaminess and adds protein.'],
    serving_suggestions: 'Serve in chilled bowls. Add a glass of fortified oat milk on the side for additional vitamin D and calcium.',
    is_shared: true,
  },
  {
    title: 'Tofu & Broccoli Sesame Stir-Fry',
    description: 'Tofu and broccoli are both excellent plant-based calcium sources; this stir-fry delivers a full day of bone-supporting nutrients.',
    category: 'dinner', diet_type: 'vegan', difficulty: 'medium',
    prep_time_minutes: 20, cook_time_minutes: 15, servings: 4, serving_size: '1.5 cups',
    calories: 295, protein: 18, carbs: 26, fat: 14, fiber: 5, sodium: 410,
    health_conditions: ['bone_health', 'gut_health', 'weight_management'],
    ingredients: ['1 block (14 oz) extra-firm tofu','3 cups broccoli florets','1 red bell pepper, sliced','2 tbsp sesame oil','3 garlic cloves, minced','1 tbsp fresh ginger, grated','2 tbsp low-sodium soy sauce','1 tbsp rice vinegar','1 tbsp tahini','1 tsp honey','1 tbsp sesame seeds','2 green onions, sliced'],
    instructions: [
      'Press tofu: wrap in a clean towel and place a heavy pan on top for 15 minutes. This removes excess water and is the key to crispy tofu.',
      'Cut pressed tofu into 1-inch cubes.',
      'Heat 1 tbsp sesame oil in a wok over high heat. Add tofu in a single layer — do not crowd or move for 3 minutes. Flip; cook 3 more minutes until golden on all sides. Remove to a plate.',
      'Add remaining sesame oil to wok. Add garlic and ginger; stir 30 seconds.',
      'Add broccoli; stir-fry 4 minutes. Add bell pepper; cook 2 more minutes.',
      'Whisk soy sauce, rice vinegar, tahini, and honey. Pour over vegetables; toss.',
      'Return tofu to wok; toss gently to coat everything in sauce.',
      'Serve over brown rice. Top with sesame seeds and green onions.',
    ],
    cooking_tips: ['Pressing tofu is the single most important step for achieving crispiness — never skip it.','Tahini is a sesame paste that provides additional calcium in the sauce.','Calcium from tofu and broccoli is most bioavailable when paired with vitamin D — consider getting some sunlight after this meal.'],
    serving_suggestions: 'Serve over brown rice or soba noodles. Add a small portion of pickled ginger on the side for added gut health benefits.',
    is_shared: true,
  },

  // ── THYROID ───────────────────────────────────────────────────────────────
  {
    title: 'Brazil Nut & Salmon Power Bowl',
    description: 'Two Brazil nuts provide the full daily recommended selenium — combined with salmon\'s iodine for complete thyroid support.',
    category: 'lunch', diet_type: 'any', difficulty: 'easy',
    prep_time_minutes: 10, cook_time_minutes: 20, servings: 2, serving_size: '1 bowl',
    calories: 480, protein: 38, carbs: 42, fat: 18, fiber: 6, sodium: 310,
    health_conditions: ['thyroid', 'heart_health', 'anti_inflammatory'],
    ingredients: ['2 salmon fillets (5 oz each)','1 cup cooked quinoa','4 Brazil nuts (2 per bowl — do not exceed this)','2 cups arugula','1 cup roasted sweet potato','1 tbsp olive oil','Juice of 1 lemon','1 tsp turmeric','Salt and black pepper'],
    instructions: [
      'Season salmon with turmeric, salt, and pepper. Turmeric provides additional anti-inflammatory benefit and pairs well with salmon.',
      'Heat olive oil in an oven-safe pan over medium-high heat. Sear salmon skin-side up 3 minutes, then flip.',
      'Transfer pan to oven preheated to 400°F; roast 8–10 minutes until salmon reaches 145°F and flakes easily.',
      'Arrange quinoa and arugula in bowls. Add warm roasted sweet potato.',
      'Place salmon fillet over the bowl.',
      'Add exactly 2 Brazil nuts per bowl. Drizzle lemon juice over everything.',
    ],
    cooking_tips: ['Brazil nut caution: 2 nuts per day provides 100%+ of selenium RDA. More is not better — selenium toxicity is real.','Arugula is one of the richest iodine sources among leafy greens.','Turmeric enhances absorption of selenium from Brazil nuts.'],
    serving_suggestions: 'This is a complete meal. Eat 2–3 hours after any thyroid medication for optimal nutrient absorption.',
    is_shared: true,
  },

  // ── WEIGHT MANAGEMENT ─────────────────────────────────────────────────────
  {
    title: 'High-Protein Greek Yogurt Bowl',
    description: 'A 30-gram protein breakfast that suppresses hunger for hours — the most effective macronutrient for satiety.',
    category: 'breakfast', diet_type: 'vegetarian', difficulty: 'easy',
    prep_time_minutes: 5, cook_time_minutes: 0, servings: 1, serving_size: '1 bowl',
    calories: 310, protein: 30, carbs: 28, fat: 8, fiber: 5, sodium: 80,
    health_conditions: ['weight_management', 'diabetes', 'bone_health'],
    ingredients: ['1 cup plain Greek yogurt, 0% or 2%','¼ cup granola (low-sugar)','½ cup mixed berries','1 tbsp almond butter','1 tbsp chia seeds','½ tsp vanilla extract','1 tsp honey (optional)'],
    instructions: [
      'Spoon Greek yogurt into a bowl. Stir in vanilla extract.',
      'Add chia seeds and mix — they will add texture and extra fiber.',
      'Spoon almond butter in the center.',
      'Top with granola around the edges for crunch.',
      'Add berries over everything.',
      'Drizzle honey if desired. Eat immediately before the granola softens.',
    ],
    cooking_tips: ['Greek yogurt has 2–3x the protein of regular yogurt due to straining — always choose Greek.','Almond butter provides healthy fats that slow digestion and extend satiety significantly.','Prepare the toppings the night before to make this a 2-minute morning assembly.'],
    serving_suggestions: 'Eat immediately. Best paired with a cup of black coffee or green tea — both have been shown to support metabolism.',
    is_shared: true,
  },
  {
    title: 'Zucchini Noodles with Turkey Bolognese',
    description: 'All the satisfaction of pasta Bolognese at a fraction of the calories — zucchini noodles add volume without carbs.',
    category: 'dinner', diet_type: 'any', difficulty: 'medium',
    prep_time_minutes: 15, cook_time_minutes: 25, servings: 4, serving_size: '2 cups',
    calories: 320, protein: 32, carbs: 18, fat: 12, fiber: 4, sodium: 440,
    health_conditions: ['weight_management', 'diabetes', 'high_cholesterol'],
    ingredients: ['4 medium zucchini, spiralized or peeled into ribbons','1 lb lean ground turkey (93% lean)','1 can (28 oz) crushed tomatoes, no salt added','1 large onion, finely diced','4 garlic cloves, minced','½ cup grated carrots','2 tbsp tomato paste','1 tbsp olive oil','2 tsp Italian seasoning','½ tsp red pepper flakes','½ cup fresh basil, torn','Parmesan for serving'],
    instructions: [
      'Heat olive oil over medium heat. Add onion; cook 5 minutes until soft. Add garlic; cook 1 minute.',
      'Add ground turkey; cook breaking apart until browned, about 7 minutes. Drain excess fat.',
      'Stir in tomato paste; cook 2 minutes to develop a deeper flavor.',
      'Add crushed tomatoes, carrots, Italian seasoning, and red pepper flakes. Simmer uncovered 20 minutes until sauce thickens.',
      'Meanwhile, salt zucchini noodles lightly and let sit 10 minutes — this draws out water that would make the dish watery. Pat dry with paper towels.',
      'In a separate dry skillet over high heat, cook zucchini noodles 2 minutes only — just enough to warm through while maintaining texture.',
      'Serve zucchini noodles topped with turkey Bolognese, fresh basil, and a light dusting of Parmesan.',
    ],
    cooking_tips: ['Salting and patting zucchini dry is the most important step — watery zucchini noodles are unpleasant.','Do not overcook zucchini noodles — 2 minutes maximum or they become mushy.','The carrot in the sauce adds sweetness that replaces added sugar in traditional Bolognese.'],
    serving_suggestions: 'Serve immediately — zucchini noodles continue to release water as they sit. Leftovers are best stored with the sauce separate from the noodles.',
    is_shared: true,
  },
];
